### ISSUE TITLE
Bug Report:   from mplfinance.original_flavor import candlestick_ochl

### ISSUE THREAD

**Issue by geek8565** [matplotlib/mplfinance#100]
report ：
 error：    err = f'NOT is_color_like() for {key}[\'{updown}\'] = {colors[updown]}'

the plot code  like“
candlestick_ochl(ax, quotes, width=.6, colorup='#ff1717', colordown='#53c156')

the old version is ok！

why？

**Comment by DanielGoldfarb** [comment]
This is because your python version is less than 3.6 

so it is not recognizing mplfinance's use of fstring.  **Officially `matplotlib` support has ended for Python less than 3.6**   

Regarding `mplfinance`, as far as I know, for now, the only incompatibilities are the fstrings, so if you must use Python < 3.6 you can either modify your local installed version of mplfinance by changing all fstrings, or alternatively try installing https://pypi.org/project/future-fstrings/ ... I have not used it but it's supposed to work.

Best solution is upgrade your Python to 3.6 or higher.

The next release of `mplfinance` will include a check for the Python version and more accurately inform the user about the issue.

**Comment by DanielGoldfarb** [comment]
I may be able to do something about this ... to allow older python versions ***only*** when importing from ` original_flavor `.   I have **[posted a stackoverflow question here](https://stackoverflow.com/questions/61305031/access-to-import-statement-from-within-init-py-or-how-to-not-run-init-p)** and if I get a good answer I will implement it.

**Comment by geek8565** [comment]
ok，I get.  thanks
