### ISSUE TITLE
Setting limits for Y-axis

### ISSUE THREAD

**Issue by MarcGoulding** [matplotlib/mplfinance#106]
Hello,
I'm trying to plot MACD using mplfinance but the histogram is an issue. It was mentioned elsewhere that histograms in the lower panel are not implemented yet and a trick around it is to set the 'Volume' column to the histogram values we want to plot and set volume=True in mpf.plot(). The issue with his is that the MACD lines don't fit in the lower panel with the scale used for the volume. As a result, it would be necessary to have the MACD lines in a separate y-axis than the 'Volume' histogram.

Using make_addplots() to add lines to the lower panel, how do you make them have a different y-axis than the volume?

Thank you for your time,

Marc

**Comment by DanielGoldfarb** [comment]
Hmmm.  Yeah, good point about the limitations on the workaround.  There is code in there that specifically clips the lower part of the volume (because for very large volumes it's hard to see their differences if we let the y-axis go to zero).

Let me see what i can come up with as a quick fix, hopefully for next week.  Ultimately will add another panel (subplot) and bars, but currently finishing up some other enhancements.

**Comment by MarcGoulding** [comment]
Furthermore, a MACD histogram has negative values which when plotted using the volume trick aren't visible since the plot places the zero close to the bottom of the axis assuming all the volume values are gonna be above it (positive).

**Comment by DanielGoldfarb** [comment]
I have just added a quick-fix for this issue.  It is not on Pypi (and will not be for another week or so) but you can grab the change by cloning this repository and installing it locally.

There are now two additional kwargs to `mpf.plotting()`.  They are `set_ylim` (for the main panel) and `set_ylim_panelB` (for the lower panel).  Both kwargs expect a list or tuple of length two, where the entries are int or float, in the order `ymin, ymax`.  Thus for example:

    mpf.plot(df,...,volume=True,...,set_ylim_panelB=(-100,100))

This will, for the time being, allow you to override whatever `mplfinance` decides to do for the y-axis limits, while we come up with a better more permanent solution.   Let me know if you have any questions.   All the best.  --Daniel

**Comment by myang80** [comment]
Hello,

Thanks for the good work. But it seems "set_ylim" has been replace by "ylim". What is the new command for "set_ylim_panelB" now? I tried "ylim_panelB", but it did not work ... Thank you!

**Comment by DanielGoldfarb** [comment]
@myang80 
**You can use `ylim` in either (or both) `mpf.plot()` and `mpf.make_addplot()`**.  The `ylim` will be applied to whatever panel is set for that particular `plot()` or `make_addplot()` call (using the `panel` keyword, or allowing `panel` to default).

Please see https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb for more information on the way that panels are handled now, since the concept of "main panel" and "lower panel" or "panelB" have been deprecated (in favor of a simple panel number).

**Comment by DanielGoldfarb** [comment]
As I am thinking about this now, it seems to me, if you want to set your own `ylim` specificall for the **volume** data, and there is _no_ `make_addplot()` data on the volume panel, then you may have to add a `make_addplot()` to that panel in order to modify the `ylim` for volume.  

**Please let me know if this is an issue**.  It may make sense to add a `volume_ylim` kwarg (since there is a `volume_panel` kwarg), or come up with some other solution other than forcing the user to do `make_addplot()` only for the purpose of setting `ylim` on the volume.  Please let me know.

Thank you. --Daniel

**Comment by myang80** [comment]
Hi Daniel,

Thanks for your help! mplfinance is a really useful tool and I appreciate your excellent support on it! 

The issue I have is that I am trying to plot accumulative volume during the up (positive) and down (negative) period along with the OHLC chart. So, it is not a volume actually. When the "volume" is negative, it seems the volume range is too small to cover the whole data. Please find the screenshot below.
![image](https://user-images.githubusercontent.com/73080272/96392896-7a01d980-118b-11eb-8af7-a2dcbed4b25a.png)

I am new to python and mplfinance, and I will look into how to use make_addplot().

Thank you very much!

Meng

**Comment by DanielGoldfarb** [comment]
Meng,
Thanks for providing more details on what you are trying to accomplish.  Please let me know how it works out with `make_addplot()`.  
--Daniel
