### ISSUE TITLE
Renko plot type

### ISSUE THREAD

**Issue by miscreanity** [matplotlib/mplfinance#11]
Great start so far, solid selection of plot types. There is a group of plot types that are not defined by consistent periods of time. One of these is Renko.

It would be a fantastic benefit having the ability to simply specify:
`mpf.plot(df, type='renko')`

Information
[https://school.stockcharts.com/doku.php?id=chart_analysis:renko](https://school.stockcharts.com/doku.php?id=chart_analysis:renko)
[https://avilpage.com/2018/01/how-to-plot-renko-charts-with-python.html](https://avilpage.com/2018/01/how-to-plot-renko-charts-with-python.html)

Existing code
[https://github.com/chillaranand/stocktrends](https://github.com/chillaranand/stocktrends)
[https://github.com/mementum/backtrader/blob/master/backtrader/filters/renko.py](https://github.com/mementum/backtrader/blob/master/backtrader/filters/renko.py)

**Comment by DanielGoldfarb** [comment]
Sounds like a good addition to this package.  Will put it on the TODO list.  Thanks for the references; will make it easier.   (As always, coding contributions are also welcome).   Thanks.

**Comment by kitt-th** [comment]
1) i second the request for renko plots!
2) Thanks very much for this repository - it's just what I've been looking for!

**Comment by coffincw** [comment]
Is this feature currently being worked on? I would be interested in giving it a shot if it isn't already being implemented.

**Comment by DanielGoldfarb** [comment]
@coffincw  Caleb- No one is currently working on this, so please feel free to give it a shot. 

When you have a good idea of how you want to implement this, before you get too far along, please communicate with me (description or pseudo-code or code).  There are a couple of enhancements currently in-flight, and I would like us to coordinate so that we can avoid, or minimize, any design or merge challenges.

Again, thank you so much for [contributing to this project](https://github.com/matplotlib/mplfinance/issues/37#issuecomment-594256428)!

All the best!  --Daniel

**Comment by coffincw** [comment]
Sounds good! I'll send you an email with my plan when I get to it this weekend!

You're welcome! I've had a lot of fun contributing!

**Comment by coffincw** [comment]
https://github.com/matplotlib/mplfinance/pull/47
