### ISSUE TITLE
Bug Report: line chart has default color of 'k' (black) which does not work well with dark style

### ISSUE THREAD

**Issue by char101** [matplotlib/mplfinance#113]
Hi,

**Describe the bug**
Line chart has default color of 'k' (black) which does not work well with dark style

**Proposal**
I propose that the default value of the line color be taken from the `lines.color` property of the style.

**Comment by DanielGoldfarb** [comment]
Yes, that's definitely a problem.  It is also possible that taking from lines.color may be an issue for some other **mpf** styles.  

I am thinking about rather adding `linecolor` as an element to the [**mpf style data**](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata) and removing the `linecolor` kwarg from `mpf.plot()` (it has already caused some confusion there).

This way, each **mpf** style can be crafted to have an appropriate default line color for that style, and users can customize the color through `make_mpf_style()`

**Comment by DanielGoldfarb** [comment]
I definitely want to have the default color for `type='line'` to come from [**mpf style data**](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata), however I am going back-and-forth as to whether I want to deprecate or rename (or leave as is) the `linecolor` kwarg to `mpf.plot()`.  

I am strongly leaning towards ***not*** leaving it as is, because it is ambigious what that color applies to.   The same abiguity may also exist inside the [mpf style data](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata) but maybe less so, and we can certainly give it a more explicit name there, maybe something like `lpcolor` (line plot color) or `lineplot_color`) 

... just some current thoughts on this ...

**Comment by char101** [comment]
Personally I don't find it ambiguous. How about leaving it as it is, but take the value of `linechart` from the style data as the default value for the parameter?

But if feels a bit inconsistent that only line chart have a `linecolor` parameter. Maybe valid values for the style data can also be passed as parameters to the `plot` function? Something like

```python
def plot(..., **kwargs):
    ...
    style.update(**kwargs)  # preferable deep merge
    ....
```

**Comment by DanielGoldfarb** [comment]
I will consider leaving `linecolor` as is, ***and*** including it in the style data (from where also it will get its default value).   

Letting all `style` related kwargs into `mpf.plot()` is problematic because each method in mplfinance, that accepts kwargs, screens for which kwargs are allowed (and whether they are of the correct type).

This screening process allows for more meaningful error messages when the user makes a mistake (as opposed to having some strange exception occur much later in the code with little or no information relating that exception back to the "bad" kwarg that ultimately caused it).

The present method of "on-the-fly" modifying any style-related elements is to "clone" an existing style, and modify it; thus, for example, something like:

    s = mpf.make_mpf_style(base_mpf_style='default',**style_kwargs)
    mpf.plot(df,style=s)

That's one extra line of code.  In theory we could do something like what you are proposing with the addition of a `style_update` kwarg to `mpf.plot()`

    mpf.plot(df,style_update=dict(**style_kwargs))

**Comment by DanielGoldfarb** [comment]
I'm going to have the kwarg `linecolor` defaul to `None` which will cause it to use `rcParams.lines.color` for whatever base_mpl_style was used in the mpf_style.  I've checked all styles and this looks fine.

**Comment by DanielGoldfarb** [comment]
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) has fix for this.
