### ISSUE TITLE
Feature Request: show_nontrading: differentiating between market off days vs no transactions

### ISSUE THREAD

**Issue by char101** [matplotlib/mplfinance#116]
Hi,

**Is your feature request related to a problem? Please describe.**
Non trading days have two possibilities:

1. the market is closed or,
2. there is no transaction for that day. 

Skipping the days when the market if closed is fine but showing the gaps when there is no transaction could be useful to show the liquidity of the entity.

**Describe the solution you'd like**
I propose to add a callback parameter in the `plot` function so that the user can define (customize) the days that could be skipped. The parameter to the callback will be the datetime value.

```python
def is_nontrading(dt: np.datetime64) -> bool:
  dates = get_days_of_a_market_index()
  return dt not in dates

def plot(..., show_nontrading=False, nontrading_callback=is_nontrading):
    ...
```

**Comment by char101** [comment]
I think this can already be resolved by adding data points where the ohlc value is `-1`. Thanks.

**Comment by DanielGoldfarb** [comment]
By the way, the idea that -1 represents missing data was inherited from the old code.  It is my intention to change that, with the next release, to use NaN to represent missing data (and to regard -1 as valid).

**Comment by char101** [comment]
Thank you for the info, I will put that in mind.

**Comment by char101** [comment]
I have converted to use `np.NaN` to indicate missing data and so far it seems to work great with existing code. I have only tried with candlestick graph though.

**Comment by DanielGoldfarb** [comment]
@char101 
Charles,
By "converted", I assume you mean you modified the `mplfinance` code itself to respect NaN instead of -1.  If so, do you want to submit a pull request for the change?  That would be great, and very much appreciated.   I don't see a fork under your user name, so if you would like to contribute this change, and if you are not familiar with the standard fork/clone/push/PR workflow, [take a look at this](https://guides.github.com/activities/forking/).     

Thank you.  --Daniel

**Comment by char101** [comment]
Sorry, by converted I mean I added new data points to the OHLC data (for stock which have days without transaction), with the value of open = high = low = close = `NaN`. Previously I used `-1` in place of `NaN`. I don't modify anything with matplotlib code in this case. I haven't encountered any error so far with using `NaN` to indicate missing transaction.

**Comment by DanielGoldfarb** [comment]
Wow, that's great.  I was actually going to suggest that as a solution to this, but I wanted to test it first because I wasn't sure if it would work with no changes to mplfinance.  There is a problem with your original proposed solution because mplfinance does **not** actually skip over non-trading days.  You've probably seen this in the code:  When you tell matplotlib that the x-axis is time/dates, it automatically assumes the time is continuous and includes all dates/times even if your data skips them.  That is the case show_nontrading=True.  But to show_nontrading=False (the default case) we actually make the x-axis a simple range of floats from 0 up to the number of rows in your data, and then use a mapping function to label the axis and make it **look like** it is dates.  I really glad the NaN solution worked for you.

**Comment by char101** [comment]
I have found one problem due to the usage of `min` and `max` on `ndarray`. If the array contains `nan` then both `min` and `max` will return `nan` so it should be replaced with `np.nanmin` and `np.nanmax`.

**Comment by DanielGoldfarb** [comment]
Thanks.  I will fix that.

**Comment by char101** [comment]
Also the moving average calculation (https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L340) could returns `nan` when there is not enough value for the period, so the moving average line could have gaps. It can be fixed by adding `min_periods=1` to the `rolling` function.

**Comment by DanielGoldfarb** [comment]
Yes, I saw that before.  Not sure if we want to change that.  Maybe we should **print a warning** so the user knows that they haven't provided enough data for the moving average period that they have requested.

**Comment by char101** [comment]
Indeed it is a subjective matter. I don't think a warning is needed though. In my case the data naturally have gaps so there is nothing I can do. If you are going to support having a continuous moving average line someday maybe accepting a tuple to the `mav` value could be useful, e.g. `mav=((14, 1), (30, 1))` would mean moving average of 14 and 30 periods with both having 1 day min period.

**Comment by DanielGoldfarb** [comment]
I like that idea.   Will see about throwing it into a later release.

Regarding warnings, in general I like the idea of informing the user of what they did wrong when something goes wrong.  This (a) prevents the user from wasting time investigating and (b) prevents maintainers from wasting time investigating and/or responding to issues that the user entered.  That said, at this point no one has ever had an issue with mav not appearing because the mav length they specified was longer than the data, so unless and until we get some complaints like that, I will hold off on coding the warning.

**Comment by char101** [comment]
Yes, after comparing it I actually prefer the one with gaps. Having continuous moving average lines without actual price is confusing.

My reason to say that a warning is not needed in this case is because the gaps are to be expected. 

On the practical level, having fragments of moving average lines like in the chart below is in my opinion useless. But having the moving average line continuous is also confusing. So for now I prefer to let it as it is.

![AMIN](https://user-images.githubusercontent.com/71255/81077661-764d0400-8f17-11ea-8456-1ad3f0256421.png)
