### ISSUE TITLE
Bug Report: statistics.StatisticsError with only a single data point

### ISSUE THREAD

**Issue by char101** [matplotlib/mplfinance#120]
Hi,

**Describe the bug**
This error happens when I was generating a chart for a stock which has just been released today, so it only contains a single data point.

```
File "mplfinance\src\mplfinance\plotting.py", line 46, in decorator
  return func(*args, **kwargs)
File "mplfinance\src\mplfinance\plotting.py", line 362, in plot
  stdy = (stat.stdev(_lows) + stat.stdev(_highs)) / 2.0
File "lib\statistics.py", line 649, in stdev
  var = variance(data, xbar)
File "statistics.py", line 587, in variance
  raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points
```

I think a special case could be computed here where for a series of a single value, the stddev is 0.

**Comment by char101** [comment]
Also I might add that I did normalize the dates in the data series to a certain interval, so while there is only a single data point, there are multiple dates which contains only `-1` as the values of Open/High/Low/Close columns. 

This is required because I was generating charts for a lot of stocks and I want all the charts to have the same date interval.

**Comment by DanielGoldfarb** [comment]
@char101 
Charles,
Will look into fixing this later.  In the meantime, if you want a workaround, in your local install you can comment out [**lines 361 through 364**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L361-L364) since, presently, that code is not actually used by the package.  That should allow you to get past this issue, however I cannot guarantee that plotting a single day of trading will actually work, but give it a try and let me know how it works.  Thanks.  --Daniel

**Comment by char101** [comment]
Thank you. Yes I already have local modifications made. It is just that when dealing with financial data we can't expect the data to always be clean, so I am hoping that by reporting this issue it can make this library more robust in the future.

**Comment by DanielGoldfarb** [comment]
Agreed

**Comment by DanielGoldfarb** [comment]
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) fixes this.
