### ISSUE TITLE
Bars in Secondary Plot

### ISSUE THREAD

**Issue by voverius** [matplotlib/mplfinance#128]
Hi,

Firstly wanted to say that this is an amazing project!

Currently I'm wrapping my head around the entire program, and wanted to know if it is possible to have bar chart in the secondary plot? I see that scattering the data is no issue. 

I want to plot e.g. MACD indicator there 
https://www.investopedia.com/thmb/4PJfILCw1l2E4pKz000zH4tvUUk=/629x376/filters:no_upscale():max_bytes(150000):strip_icc()/macd3-5bfd6bd6c9e77c002669ffc2

Is this feasible?

Cheers

**Comment by DanielGoldfarb** [comment]
@voverius 
You should be able to do this easily for the MACD line and the MACD Signal line, using `mpf.make_addplot()` and specifying the `panel='lower'` in the call to `make_addplot()`.  See this tutorial for details: https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb

Sometime in the next few days I intend to release an enhancement that will allow you to have up to 3 panels on the chart, and you would say either `panel='B'` or `panel='C'` for the lower chart.

At present, it is not possible to ***directly*** plot the MACD Histogram using `make_addplot()`.  I am hoping to include that as an enancement soon.  

In the meantime, as a work-around, you can put the MACD histogram data in your dataframe in the column labeled "Volume".  Then specify `volume=True` in the call to `mpf.plot()` ***and also specify*** **`set_ylim_panelB=(ymin,ymax)`** (where ymin and ymax values that are just below and just above the min and max of you MACD Histogram values).  

The reason you need to specify `set_ylim_panelB` is because `mpf.plot()` thinks you are plotting actual volume bars, and therefore it will clip the minimum value of the bar chart to a value *above zero* in order to make the volume bars look nice.  

However a MACD Histogram can have negative values, and thus you have to adjust the ylimits to account for this.  Again, all this is just a workaround if you are in a hurry.  Soon, when `make_addplot()` properly supports bar charts, this will be a simple call to `make_addplot()` with the MACD data.

I hope that helps.   All the best.   --Daniel

**Comment by voverius** [comment]
Hi Daniel,

Thank you very much for the detailed answer! 
Considering the current situation this seems like a perfect and easy work around.

Good luck!
