### ISSUE TITLE
Bug Report: 1 candle would not display correctly.

### ISSUE THREAD

**Issue by toksis** [matplotlib/mplfinance#133]
**Describe the bug**
I am just posting one candle on a specific time. It will not post correctly.

![image](https://user-images.githubusercontent.com/5316255/82117503-73c69600-97c4-11ea-914e-cefce19c0758.png)

**To Reproduce**
Just run this code: The csv is on the example folder.
```python

import pandas as pd
import mplfinance as mpf
# df = pd.read_csv('data/SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)
df = pd.read_csv('SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)

x = df.iloc[1:2,:]

mpf.plot(x,type = 'candle')

**Expected behavior**
It should create a correct candle?

**Comment by DanielGoldfarb** [comment]
Yes, this looks bad.  Will correct it.  Thanks for the code to reproduce.

**Comment by toksis** [comment]
Maybe the issue is that there is no next X (time) variable? so you could not get the width of the body?

**Comment by DanielGoldfarb** [comment]
Yes, this is a simple thing, and already fixed in my local version.  However it was fixed in the context of implementing a new algorithm which nicely adjusts candle widths and volume-bar widths according many aspects of the data ... for example, number data points, frequency of the data (minute-by-minute, hourly, daily, weekly, etc.), whether `show_nontrading` is True or False:  All of these things affect how a particular candle width looks.  As you can imagine the algorithm needs to be thoroughly tested for all of these cases (including different ` styles `) before being released.  I hope to release it early next week.  Thank you for helping.  Much appreciated.

**Comment by abaldor** [comment]
Great to see this. I have the same issue. Looking forward to the update. Many thanks DG!

**Comment by DanielGoldfarb** [comment]
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) fixes this.
