### ISSUE TITLE
Customizing background and grid

### ISSUE THREAD

**Issue by Sile25** [matplotlib/mplfinance#134]
Hello! I'm just getting started to this library and i'm surprised at how easy to use it is while looking beautiful and modern. I'm trying to add some more customization to my chart, but i'm struggling with some parameters: i would like to change color to the background and i would like to remove the grid from my chart, but i don't know where to set those values. In addition, with the old mpl_finance, i was able to set an `alpha` parameter, can i do something similar with mplfinance? Thanks in advance!

**Comment by DanielGoldfarb** [comment]
@Sile25 
Towards the bottom of **[Customization and Styles](https://github.com/matplotlib/mplfinance/blob/master/examples/customization_and_styles.ipynb)** there is a chart listing the available kwargs for ` mpf.make_mpf_style() `.  These include `facecolor` to color the background of the axes.  And ` gridstyle ` which may be set to `None` or simply ` '' ` (i.e. two single quotes with nothing in between) in order to turn off the grid.

It's not clear where you want to set ` alpha `.  There are a couple of different alpha settings available:
- When calling ` mpf.make_market_colors() ` you can set ` alpha ` it it will affect the alpha of the candlestick faces.
- When setting [trend lines, support lines, etc](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb) you can also set ` alpha ` for the line.

I hope that helps.  All the best.   --Daniel

P.S.  Just out of curiosity (since you mentioned changing face color and turning grid lines off) are you by any chance trying to accomplish what is dissussed in this issue: [Feature Request: Remove axes completely - show data only](https://github.com/matplotlib/mplfinance/issues/48) ?

**Comment by Sile25** [comment]
@DanielGoldfarb Yes this helped me a lot, it's what i needed, thank you! I wanted to remove the grid because, since i'm adding a lot of trendlines to my chart, i wanted to see if it looked better or worse without the grid, i don't need to hide my axes for now, instead i wanted to make the labels on both the x and y axis bigger. Thank you again, the issue can be closed!

**Comment by DanielGoldfarb** [comment]
I'm glad that worked.  All the best.
