### ISSUE TITLE
How to use fig,axes with returnFig = True

### ISSUE THREAD

**Issue by alidanish127** [matplotlib/mplfinance#152]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.

Hi Daniel, First of all, thank you for this amazing Package and all the work you are doing to improve it furthre. I am trying to create a Restful API using Flask, for sending the mpl plot embedded as a ByteObject within an html page.
Using https://github.com/matplotlib/mplfinance/pull/65/commits I was able to do the following 

Can you please advise how should I proceed?

    fig, ax1 = mpf.plot(ohlc_dataframe, addplot=movingAverageCrossoverScatterPlot, volume=False, figscale=2, style='yahoo', type='candle', title=titleVal, returnfig=True, block=False)

But how to I embed the plot in html.
 I tyried following but it did no work and failed ith error
"AttributeError: 'list' object has no attribute 'plot'"

    buf = BytesIO()
    fig.savefig(buf, format=".png")
    # Embed the result in the html output.

    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return f"<img src='data:image/png;base64,{data}'/>"

    # plot_url = base64.b64encode(buf.getvalue())
    
    return render_template('test.html', plot_url=plot_url)

**Comment by DanielGoldfarb** [comment]
@alidanish127 

It's a little difficult for me to know what's going on, or even guess, because you have not provided all (or enough) of your code.  (For example, I cannot see where `movingAverageCrossoverScatterPlot` is defined in order to know whether or not its definition may be relevant; nor can I see what you are doing just before and just after using mplfinance).  

**It would also be helpful to see the full traceback from where your encountered the "Attribute Error" exception in order to know exactly where in the code that exception occured.**

Also, if the only reason you are setting `returnfig=True` is to be able to call savefig, you can do this directly using the `savefig` kwarg of `mpf.plot()` [**as show here**](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb).

**Comment by alidanish127** [comment]
Thank you for the quick response.  Much appreciated and honestly quite unexpected :) 

Here are the snippets from my code which I hope will help you understand what I am trying to do. (I am trying to superimpose buy and sell signals that I calculated over the daily candle (ohlc_df) )

    apds = [mpf.make_addplot(sell_signal, scatter=True, markersize=200, marker='v', color='r'),
            mpf.make_addplot(buy_signal, scatter=True, markersize=200, marker='^', color='g')]

    sell_signal = df['sell_signal']
    buy_signal = df['buy_signal']

    fig, ax1 = mpf.plot(ohlc_df, addplot=apds, volume=False, figscale=2, style='yahoo', type='candle', title=titleVal, returnfig=True, block=False)

    # Save it to a temporary buffer.
    buf = BytesIO()
    fig.savefig(buf, format=".png")

    # Embed the result in the html output.
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return f"<img src='data:image/png;base64,{data}'/>"

    # plot_url = base64.b64encode(buf.getvalue())
    # return render_template('test.html', plot_url=plot_url)

**Comment by DanielGoldfarb** [comment]
It's still not clear to me exactly what you are asking.  If you want help understanding why you are getting `"AttributeError: 'list' object has no attribute 'plot'"`, I would need to see all of the trace/walkback error message that gets printed along with that exception.  If you are asking for something else, please explain.

Just as a vague guess (for the above exception message) based on the extremely limited information ... it sounds like you are trying to call or reference `plot()` on a list object, but I don't see anything like that in your code ... ***unless*** somewhere in your code you have defined **`mpf`** as a list such that `mpf.plot()` would be referencing an attribute 'plot' on a list.  Alternatively, if after calling `fig, ax1 = mpf.plot(...)` you then (somewhere in code not shown) call `ax1.plot()`, or reference `ax1.plot`,  this could also give a similar error message, since `fig, ax1 = mpf.plot(returnfig=True)` will return a **`list`** of axes in the variable ax1.

**Comment by alidanish127** [comment]
Thank you for your patience and help.

I was able to get past that issue and now able to see the plot embedded in html
using the following logic. I am passing dataframe series as the add plot params generated using Moving Avg crossover and superimposing it over daily chart. 

I want to know 
1.If its possible to get a dynamic plot embedded in html
2. If yes, where can I find relevant information for doing that.

    titleVal ='\n'.__add__(ticker.upper())
    # mpf.plot(candle_df, addplot=apds, volume=False, figscale=2, style='yahoo', type='candle', title=titleVal)
    mpf.plot(candle_df, addplot=apds, volume=False, figscale=2, style='yahoo', type='candle', title=titleVal, savefig=buf, block=False)

    figure = plt.gcf()
    canvas = FigureCanvas(figure)
    canvas.print_figure(buf)
    plot_data = base64.b64encode(buf.getvalue()).decode('ascii')
    buf.seek(0)
    return render_template("output4.html", url=plot_data) 

![image](https://user-images.githubusercontent.com/22732686/83991528-5aaea080-a990-11ea-91e1-7ff61a0b7ca9.png)

**Comment by DanielGoldfarb** [comment]
Not sure what you mean by "dynamic plot" ... perhaps you mean the basic matplotlib plot window with the zoom and pan controls on it??

At any rate, your question sounds like more of a basic matplotlib question (not directly related to mplfinance).   If so, you may try asking 
- here: https://discourse.matplotlib.org/c/community/11 
- or here: https://github.com/matplotlib/matplotlib/issues 

Let me know if you hit a dead end and I will see if I can help.

**Comment by DanielGoldfarb** [comment]
Also, not sure if this will help you (as I am not familiar with it) but I found this:
https://mpld3.github.io/

**Comment by alidanish127** [comment]
Thanks for your prompt response Daniel. I was indeed looking for basic matplotlib plot window with the zoom and pan controls on it and the url in your second post 'https://mpld3.github.io/' seems to do just that. Thank you very much for your help and the awesome work you are doing. For now I am ok with the png being embedded in the html but I will be looking to port the matplotlib plot window available soon and will see how that goes. Thanks again. 
Cheers.
