### ISSUE TITLE
How to adjust borders and wipe out empty spaces

### ISSUE THREAD

**Issue by ADuden** [matplotlib/mplfinance#193]
If would be cool to have some plt.subplots_adjust(top=1, bottom=0, right=1, left=0) functionality, because I have huge white empty space around the plot. And I can't fix it even manually with "configure subplot" at the bottom. Thanks
![photo_2020-06-27_00-40-30](https://user-images.githubusercontent.com/47084730/85903478-16842280-b80f-11ea-9529-c8591fa3ed71.jpg)

**Comment by DanielGoldfarb** [comment]
Try

    mpf.plot(data,...,tight_layout=True,...)

Let me know if that works for you.

**Comment by ADuden** [comment]
Thank you for the answer, and as you can see, candles are stretched out, but the plot isn't
![Screenshot from 2020-06-27 22-57-16](https://user-images.githubusercontent.com/47084730/85931053-f4030f80-b8c9-11ea-81f6-f2db2fb8b2ab.png)

**Comment by DanielGoldfarb** [comment]
@ADuden 
I have just updated the `tight_layout=True` functionality so that it will also adjust the Figure padding surrounding the plot.

Please `pip install --upgrade mplfinance`, confirm you get version **0.12.6a2**, then try `tight_layout=True` again. and let me know if that works for you.

Thanks.   All the best.   --Daniel

**Comment by ADuden** [comment]
Thanks a lot, everything works great)
