### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by flogutz** [matplotlib/mplfinance#194]
**Is your feature request related to a problem? Please describe.**
Using this package within a loop to generate thousands of plots, it is necessary to clear the memory. 

**Describe the solution you'd like**
A very easy solution is to use the function plt.close("all") within plotting.py.
Just create a function that calls plt.close("all").

**Comment by DanielGoldfarb** [comment]
Already exists:

`mpf.plot(data,...,closefig=True,...)`

Kwarg `closefig` has three possible values:  the default value is `"auto"`, which means `mpf.plot()` will close the figure [when it thinks it is safe to do so](https://github.com/matplotlib/mplfinance/issues/131#issuecomment-626787022).  It can also be set to `True` or `False` by the caller to override the default value one way or the other.

Please note: mplfinance _only closes the figure that it creates_.  It would not be appropriate for mplfinance to `plt.close("all")` because the caller may have created other Figures which mplfinance has no right to close.
