### ISSUE TITLE
Feature Request: allow case insensitive Pandas columns naming

### ISSUE THREAD

**Issue by lusis-ai** [matplotlib/mplfinance#195]
When capturing data from sources providing open, high, low, close (all lower case), mplfinance cannot directly plot them. We need to convert first the column names with first letter as uppercase : Open, ...

The column names must be used by mpf such as if they are case insensitive for the end user.

**Comment by DanielGoldfarb** [comment]
This has been discussed many times (#82, #118, #129) .  It particular please note the following:

---
**Given a data frame with lower case names, a single line of code can capitialize the names:**
**` df.columns = [c.capitalize() for c in df.columns]`**

    In [2]: df.head(2)
    Out[2]:
                   open     high      low    close     volume
    Date
    2019-11-01  3050.72  3066.95  3050.72  3066.91  510301237
    2019-11-04  3078.96  3085.20  3074.87  3078.27  524848878

    In [3]: df.columns = [c.capitalize() for c in df.columns]

    In [4]: df.head(2)
    Out[4]:
                   Open     High      Low    Close     Volume
    Date
    2019-11-01  3050.72  3066.95  3050.72  3066.91  510301237
    2019-11-04  3078.96  3085.20  3074.87  3078.27  524848878

---
**There is a `columns` kwarg to `mpf.plot()` that allows you to pass in any column names you want:**

    mpf.plot(df,columns=['myopen','myclose','myHigh','my_low','my_VoLuMe'])

---

**That said**, I have gotten this request often enough that I have decided to do ***something*** about it.   

We will ***not*** make the column names case-insensitive, **[for the various reasons explainded here](https://github.com/matplotlib/mplfinance/issues/82#issuecomment-619585700)**.  

However, it does seem fairly common that some data sources supply the _same column names expected by_ `mplfinance` _but in lower case_.  

Therefore i have changed the code so that if your dataframe contains columns named  **"Open , High, Low, Close [,Volume]"** or named **"open , high, low, close [,volume]"**, then ***either set of names will work.***  (Note, "Volume" is optional, and only need be present in the dataframe if you request volume to be displayed).  Any other column names will require you to either change the column names in your dataframe, or provide column names using the `columns` kwarg to `mpf.plot()`.

**`pip install --upgrade mplfinance`** to pick up this change.  Check that `mpf.__version__` is **0.12.6a3** or higher.

**Please let me know if this works for you.**  Thanks very much for you interest in mplfinance.  All the best.  --Daniel
