### ISSUE TITLE
Feature Request: Pattern Recognition

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#198]
**Is your feature request related to a problem? Please describe.**
A framework for pattern recognition - with user-defined percentages on depth, days etc...

**Describe the solution you'd like**
Incorporating Pattern Recognition into charting library. Patterns: Cup, Cup with Handle, Head and Shoulders... etc.

**Describe alternatives you've considered**
Haven't found any

**Additional context**

**Comment by manuelwithbmw** [comment]
@PowerrNuller Hi, just my take on this one. I personally think this goes beyond the scope of mplfinance library, I mean this could be coded and engineered using mplfinance's broad sets of tools, I would not expect its solution to come directly from the library itself. The charting library does not know what a Cup, Cup & Handle, Head and Shoulders, etc are and cannot know it. The number of patterns are infinite, so they has to be rationalised and coded by the Trader itself, deciding percentages, constraints, tolerances etc. Just my take. Have a nice day
Manuel

**Comment by DanielGoldfarb** [comment]
Thanks @PowerrNuller for closing;  And thanks @manuelwithbmw for commenting.  I was going to add similar comments but wanting to think about it for a bit.  Here are some thoughts for the record:  Although it is common to use visualation in connection with patterns, pattern recogniztion itself is an algorithmic process looking at the numbers.  (Sometimes it is worthwhile to look at the patterns while _developing_ the algorithm, but after that it is purely a numbers game).  Which is why I would agree that it is beyond the scope of mplfinance.

That said, I would consider that once an external algorithm has identified patterns, perhaps mplfinance can provide an easy way to visualize/indicate the patterns that were found.  I believe that such and interface already exists: with [`make_addplot(type=scatter)`](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/scatter_multiple_markers.ipynb), and with the [various lines kwargs (ex: `alines` )](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb).  But if you think of an alternative interface to make it easy to visualize patterns that were discovered by some pattern recogniztion algorithm, then I am open to suggestions.

**Comment by fxhuhn** [comment]
alternatively we could start a parallel project :-)
Do you have a basic idea how to detect sideways movements?
