### ISSUE TITLE
How can I continue the script after `mplfinance.plot()`?

### ISSUE THREAD

**Issue by schorschie** [matplotlib/mplfinance#20]
When calling `mpl.plot()` in a script the program stops, until the figure is closed. How can I open figures in background? I tried `plt.ioff()` but it didn't work.

**Comment by DanielGoldfarb** [comment]
Someone else brought up this same issue in an email a couple of days ago.  I will investigate when I have time (hopefully in a week or two).  

I'm not sure, but my current hypothesis is that it has something to do with the fact that `mpf.plot()` is calling `plt.show()`, in which case adding a `noshow=True` kwarg, or the proposed [`mpf.axplot()` API](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-577482830), may fix the problem.

**Comment by DanielGoldfarb** [comment]
**[This appears to be the solution](https://stackoverflow.com/a/458295/1639359)**.  I will test it next week, and if it works will implement something similar.  

(If I understand that answer correctly, it means the caller/user of `mplfinance` will be responsible to call `plt.show()` _if they want the plot window to remain open after their script exits._)

**Comment by DanielGoldfarb** [comment]
With the next release, `mpf.plot()` will accept the kwarg `block=False` (default value is `True`) to continue the script.  You must however allow blocking on the ***last*** call to `mpf.plot()`, or otherwise somehow prevent your script from exiting.  (If you do not allow blocking, and do not prevent the script from exiting, then when the script exits all non-blocked plot windows will close.  This solution was based on **[this answer](https://stackoverflow.com/a/13361748/1639359)**.

**Comment by DanielGoldfarb** [comment]
This is now released.  `pip install --upgrade mplfinance` to pick up the enhancement.
`mpf.plot(data,block=False)` to **not** block.
