### ISSUE TITLE
how to show the whole title in the candle image?

### ISSUE THREAD

**Issue by cvJie** [matplotlib/mplfinance#213]
hi,
thanks for your great work! and I want to know if there is a way to add a text to figure,thank you
as picture,
<img width="270" alt="image" src="https://user-images.githubusercontent.com/31844043/87648835-84729880-c782-11ea-8171-03a86d4d8d8b.png">

**Comment by DanielGoldfarb** [comment]
That's unexpected.  
What version are you running? 

    print(mpf.__version__)

**Comment by cvJie** [comment]
> print(mpf.__version__)

0.12.5a3

thanks

**Comment by DanielGoldfarb** [comment]
Hmm.  There is, with that version, a way to increase the "padding" around the plot.  But you shouldn't have to, so if it's ok with you,  I'd like to try to reproduce this on my end to see what's going wrong.  Will you post the data and the code used to make this plot so that I can try to reproduce the issue here?     Please also indicate in which environment you are running.  Thanks.  --Daniel.

**Comment by cvJie** [comment]
> Hmm. There is, with that version, a way to increase the "padding" around the plot. But you shouldn't have to, so if it's ok with you, I'd like to try to reproduce this on my end to see what's going wrong. Will you post the data and the code used to make this plot so that I can try to reproduce the issue here? Please also indicate in which environment you are running. Thanks. --Daniel.

hi,daniel:
here is my main code:

mc = mpf.make_marketcolors(
        up='green',
        down='red',
        edge='i',
        wick='i',
        volume='in',
        inherit=True)

    s = mpf.make_mpf_style(
        y_on_right=False,
        marketcolors=mc)

    # 设置线宽
    mpl.rcParams['lines.linewidth'] = 1
        kwargs = dict(
            type='candle',
            volume=True,
            title="2020-07-09" + "  " + "vol: 0.987",
            figsize=(4,3.5),
            figscale=0.7
        )
       
        mpf.plot(frame_data,
                 **kwargs,
                 style=s
                 )

**Comment by DanielGoldfarb** [comment]
@cvJie ,

This may be because your plot is so small (`figsize=(4,3.5)`).
Please note (I should probably add a warning) when specifying `figsize`, then `figscale` and `figratio` are ignored.

There are a couple things you could do here to improve the appearance of your plot.
The first is to make it larger.  Try, maybe, **`figsize=(6.8,5.95)`**.

If you must use a small figure size, then you can try scaling down the font [**as was suggested here**](https://github.com/matplotlib/mplfinance/issues/38#issuecomment-590595776).

So for example, `mplf.rcParams['font.size'] *= 0.6`

Also, **modifying `rcParams` dicrectly while using `mplfinance` can have unexpected results**, since mplfinance styles also manipulate rcParams.  Instead you should pass the rcParams changes that you want into `mpf.make_mpf_stlye()`, like this:


    mc = mpf.make_marketcolors ...
    
    fsize = mpl.rcParams['font.size'] * 0.6
    rcp = { 'lines.linewidth' : 1, 'font.size': fsize }

    s = mpf.make_mpf_style(
        y_on_right=False,
        marketcolors=mc,
        rc=rcp
    )

Finally, I sometimes like to add a linefeed at the beginning of the title, to push it down a little bit:

    title="\n2020-07-09" + "  " + "vol: 0.987",

Let me know how these things work for you.  Thanks.  --Daniel
