### ISSUE TITLE
Bug Report: if a list starts with None, an error is raised even if there is some int/float data behind

### ISSUE THREAD

**Issue by fritz-smh** [matplotlib/mplfinance#214]
I have such a list with which I want to plot markets :

`[None, None, None, 133.75, None, None, None, None, None, None, None, 138.82, None, None, None, None, 137.74, ...]`

The fact that this list starts with a None value make this error  raised in plotting.py :  

```
File "/usr/local/lib/python3.8/dist-packages/mplfinance/plotting.py", line 492, in plot
    raise TypeError('apdata is list but NOT of float or int')
TypeError: apdata is list but NOT of float or int
```

The issue comes from this test that checks only the first element of the list :  
```
                if isinstance(apdata,list) and not isinstance(apdata[0],(float,int)):
                    raise TypeError('apdata is list but NOT of float or int')
```

Could you please fix this ?

Thanks,
Fritz

**Comment by DanielGoldfarb** [comment]
Will do.  This should be just checking that there is at least one (float,int) in the list, no necessarily the first element.
Thank you for reporting this.

**Comment by fritz-smh** [comment]
Thanks :) It will help a lot!

**Comment by DanielGoldfarb** [comment]
I thought this seemed strange, that this was working before, in fact in cell **`In [9]:`** [**in this notebook**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) there is an example of an addplot scatter plot in which the are _no values at the beginning of the data_ (as in your example).

Then I realized the issue is that you are passing **`None` instead of `nan`**.   
Please set your values to **`math.nan`**
(or you can use `np.nan`, or, slightly slower, `float('nan')`).

I could modify `mplfinance` to accept `None` as well as `nan`.  The problem is that internally I would anyway have to convert all the `None` to `nan`, because sooner or later, at the lower levels, math operations are done on the data for various reasons, and python can do math on a `nan` (which is effectively a `float`) but not on a `None type`.

**Comment by fritz-smh** [comment]
This is ok with np.nan.
Thanks!
