### ISSUE TITLE
Scaling between normalized y units and data units

### ISSUE THREAD

**Issue by mikessut** [matplotlib/mplfinance#227]
I'm trying to add some interactive drawing features and I can't seem to figure how how the y axis gets scaled between normalized units (from 0.0 to 1.0) to units of the data.

For example, when I mouse over a figure, the 'y' value is shown as values of 0 to 1.0.  Likewise, if I use ginput(), I always get a y value between 0 and 1.0.

Where is this mapping defined?  I think that matplotlib is doing that scaling, but I can't find where the scaling is stored.  get_ylim() isn't dependable if you have zoomed in (the zoomed limits are no longer 0 to 1.0).

**Comment by DanielGoldfarb** [comment]
Hmmm.   That should not be happening; and I think we saw this bug before and (I thought we) fixed it.
At any rate, I'll take a look in a couple of days.  In the meantime if you want to post your data and code so that I can be sure to be able to reproduce that might come in handy.  All the best.  Have a great weekend. 

Similar to Issue #145 ???

**Comment by mikessut** [comment]
Thanks for the quick reply.

I went digging to see if I had the latest versions.  I was running:
matplotlib==3.1.1 
mplfinance==0.12.6a3

I upgraded matplotlib to version 3.2.2 and that appears to have eliminated the problem.

**Comment by DanielGoldfarb** [comment]
I'm glad to hear that helped and eliminated the problem.

All the best.
