### ISSUE TITLE
Relative position to the candle within the chart window

### ISSUE THREAD

**Issue by fxhuhn** [matplotlib/mplfinance#228]
The positioning of symbols above or below a candle can be shown very well with x percent distance to the absolute price.

```
        s_low = mpf.make_addplot(df.swing_low * 0.99,
                                 scatter=True,
                                 markersize=5,
                                 color='grey')
        s_high = mpf.make_addplot(df.swing_high * 1.01,
                                  scatter=True,
                                  markersize=5,
                                  color='grey')
```

But the percentage distance at a price of $10 is different than at $1000. Especially if the 'chart' calculates the scaling depending on the absolute price range, of course.

Is it possible to use a special offset for this, so that the distances are always similar in every chart?

**Comment by DanielGoldfarb** [comment]
Markus,
Yes this is possible.  I don't have time to work on this for a while, but I can give you the basic algorithm that I would be inclined to use, and you can either use it outside of `mplfinance`, similar to what you are doing above, or if you would like to contribute to mplfinance perhaps you can write the code to accept such an offset kwarg.

Anyway the basic idea is that you want to move some percent of the ***chart***, rather than some percent of the price (which, as you have indicated, doesn't scale nicely depending on the price).

An approximate (but pretty good) way to do this is to calculate the difference between the max and min of your data, and then take some small percent of that number and ***add*** or ***subtract*** that from your data (instead of multiplying as a factor).

For example, something like this:

    span = max(df.High) - min(df.Low)

    delta = 0.02 * span

    s_low = mpf.make_addplot(df.swing_low - delta,
                                 scatter=True,
                                 markersize=5,
                                 color='grey')
    s_high = mpf.make_addplot(df.swing_high + delta,
                                  scatter=True,
                                  markersize=5,
                                  color='grey')

You can play around with the percentage factor (0.02 in the above example) to see what works best for a lot of different plots.  

Give that a try and let me know what you think.    

Thanks.  --Daniel

**Comment by fxhuhn** [comment]
Sorry @DanielGoldfarb , that's to easy :-)
A value between 0.01 and 0.02 seems to be optimal.

```
        offset = 0.01 *(df.High.max() - df.Low.min())
        s_low = mpf.make_addplot(df.swing_low - 1 * offset,
                                 scatter=True,
                                 markersize=5,
                                 color='grey')
        s_high = mpf.make_addplot(df.swing_high + 1 * offset,
                                  scatter=True,
                                  markersize=5,
                                  color='grey')



```
![ice_cbk_de](https://user-images.githubusercontent.com/49436733/89105500-f6eda480-d421-11ea-9754-52a990c85b38.png)
![ice_aapl_us](https://user-images.githubusercontent.com/49436733/89105507-04a32a00-d422-11ea-9af1-4ad5895494d3.png)

**Comment by DanielGoldfarb** [comment]
Glad to hear that helped.  And thank you for posting your plots.  I always enjoy seeing the creative things people are doing with mplfinance.  All the best.
