### ISSUE TITLE
Bug Report: mplfinance doesn't import in jupyter notebook

### ISSUE THREAD

**Issue by elizabethexpialadocious** [matplotlib/mplfinance#230]
**Describe the bug**
mplfinance doesn't import in jupyter notebook

**To Reproduce**
1. at shell: jupyter notebook
2. in browser in jupyter, launch a notebook that imports mplfinance
3. run a line containing "import mplfinance as mpf" 
4. error results: ModuleNotFoundError: No module named 'mplfinance'
5. note that "import mplfinance as mpf" works as expected in ipython

**Expected behavior**
nothing (no error should occur)

**Screenshots**
![image](https://user-images.githubusercontent.com/20966617/89100742-d7db1c80-d3f9-11ea-840c-3ec619786773.png)

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster) 
 - Browser Firefrox 68.10.0esr (32-bit)
 - Version Linux xxx 5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020 aarch64 GNU/Linux, Python 3.7.3 (virtualenv), jupyter notebook --version 6.1.0
file /usr/bin/python3.7:
/usr/bin/python3.7: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=f6973949a18fc12743cc4397016f28a9580a1417, stripped

Error persists when running 32-bit kernel.

**Comment by elizabethexpialadocious** [comment]
I was curious if this bug was related to my running a 64-bit kernel on a predominantly 32-bit system, so I rebooted using the 32-bit kernel; the issue persisted.

**Comment by DanielGoldfarb** [comment]
In my experience, unless the module has been misspelled (which doesn't appear to be the case based on your screenshot above), `ModuleNotFoundError` usually indicates that the **install location** is not within the **search path** for importing modules.

Since this is working for you under ipython, so have a simple way to find where your system installed mplfinance:

    In [1]: import mplfinance as mpf
    In [2]: mpf.__file__

To find out where your system is searching for modules

    import sys
    print(sys.path)

If you run the above for both `ipython` and in your `jupyter notebook`, I am guessing that you will find that **`sys.path`** is _different_ for your ipython installation than it is for your jupyter notebook (and that the notebook's search path does not include the install location).  This could be for various reasons such as environment variables, where jupyter is installed, whether you are running virtual and/or conda environments, etc.  You can read more about the module search path here: https://docs.python.org/3/tutorial/modules.html#the-module-search-path

Let me know if the above gives you enough information to resolve the issue.  If not, please provide the output from the above commands and I will do what I can to help further.  All the best.  --Daniel

**Comment by elizabethexpialadocious** [comment]
That did it! Thank you Daniel! A little investigating got me to https://github.com/jupyter/notebook/issues/3311 which suggested my deleting ~/.local/share/jupyter/kernels/python3/kernel.json; I don't know how that got there. 
![image](https://user-images.githubusercontent.com/20966617/89117914-db29e300-d4a1-11ea-83d1-56e3f63918c6.png) works great! thank you!

**Comment by DanielGoldfarb** [comment]
Elizabeth, 
Glad to hear it.  All the best!
--Daniel
