### ISSUE TITLE
TypeError while plotting data for selected range?

### ISSUE THREAD

**Issue by johnbest5673** [matplotlib/mplfinance#24]
Hi Daniel,

I am learning Python, to be very honest and trying to plot the chart simultaneously. I am trying to plot the chart of SPX (data taken from you) for selected time frame. Here's the code- 

`sDate = datetime(2008, 2, 1)         #Start  Date`
`eDate = datetime(2008, 9, 30)       #End Date`

`#Data for Ephmeris`
`dfE = pdE.read_csv("eph.csv", parse_dates=['dt'])`
`dfE = dfE[(dfE['dt'] >= sDate) & (dfE['dt'] <= eDate)]`

`df1 = mpf.make_addplot(dfE['Sun'])`

`dfS = pdS.read_csv("SPX.csv", parse_dates=['Date'])`
`dfS = dfS[(dfS['Date'] >= sDate) & (dfS['Date'] <= eDate)]`
`mpf.plot(dfS, volume=False, addplot=df1)`

I am getting **TypeError** - Expect data.index as DatetimeIndex, generated by the last line!!!

Regards

**Comment by DanielGoldfarb** [comment]
John, 
The index of the DataFrame needs to be a DatetimeIndex.   My guess is that your DataFrame looks something like this:

               Date     Open     High      Low    Close     Volume
    Date                                                            
    0    2019-11-01  3050.72  3066.95  3050.72  3066.91  510301237
    1    2019-11-04  3078.96  3085.20  3074.87  3078.27  524848878
    2    2019-11-05  3080.80  3083.95  3072.15  3074.62  585634570

Notice that you have a date column, but the index of the data frame (the row keys on the left) are just integer.   The DataFrame Index needs to be dates (that's what `mpf.plot()` expects).  

There are several ways to do that.  One possibility is:

In `read_csv()` instead of 

`parse_dates=['dt']` and  `parse_dates=['Date']`  

do instead:   

`index_col=['dt'],parse_dates=True` and 
`index_col=['Date'],parse_dates=True`  

or 

`index_col=['dt'],parse_dates=['dt']` and 
`index_col=['Date'],parse_dates=['Date']`  

should also work.

Note that if you make this change, then you will no longer have a 'dt' or 'Date' column, so `dfE = dfE[(dfE['dt'] >= sDate) & (dfE['dt'] <= eDate)]` will have to change accordingly to use the index itself instead of referencing the data column.

Thus 

    dfE = dfE[(dfE['dt'] >= sDate) & (dfE['dt'] <= eDate)]

Becomes :

    dfE = dfE[(dfE.index >= sDate) & (dfE.index <= eDate)]

**Or more simply, with a DattimeIndex, you can just slice by Date:**

    dfE = dfE[sDate:eDate]

**Comment by johnbest5673** [comment]
Hi Daniel,

Thanks now able to view the chart. But, need the Double axis to view it properly. Below link of imgur
will help you to understand better.

https://imgur.com/a/ASYczxv

If the stock prices are plot on left side Y-axis, then the other data should **scale** on another Y-axis, right side one. The bold one, "scale", is an important factor so that one can view them rightly. 

I understand that your project basically is for Stock Charting and suddenly I came up with this idea. :)


Regards

**Comment by DanielGoldfarb** [comment]
Glad to hear that worked.  The ability to have a secondary y-axis scale is coming soon.  Hopefully within another week.

**Comment by johnbest5673** [comment]
That's great... I am waiting.....

Regards

**Comment by DanielGoldfarb** [comment]
secondary_y axis is now in production.  `pip install --upgrade mplfinance`
see bottom of https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb for examples, etc.
