### ISSUE TITLE
overlay sideways volume histogram and savefig

### ISSUE THREAD

**Issue by davidm2k** [matplotlib/mplfinance#258]
Greetings,

Is it possible to overlay a sideways volume histogram now that there is the external axes feature?  I looked at your 5 examples I just could not get it to work.  I was able to do it with the old mpl_finance. (Please see attached pic, histogram in light blue)

Also once I am in external axes mode I couldn't get 'savefig' to work.  Outside of external axes mode 'savefig' works.

Any advice would be appreciated, thanks.
![mpl_finance_histogram](https://user-images.githubusercontent.com/5743666/92332807-06ac7880-f0b3-11ea-892f-ef7030660cd6.png)

**Comment by DanielGoldfarb** [comment]
@davidm2k 

- Using external axes, you should be able to overlay horzontial volume by calling [**`.barh()`**](https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.axes.Axes.barh.html) on the Axes object.  (I'm guessing that you will want to set `alpha` to less than one when calling `.barh()`)

- The `savefig` kwarg is ignored in External Axes mode, since you, the user, have full control over the Figure and Axes, you can simply call [**`.savefig()`**](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.savefig) on the Figure object.

Let me know if the above is helpful, or if you need more information.  Thanks. --Daniel

**Comment by davidm2k** [comment]
Hi Daniel,

Thanks for the tips, it worked like a charm.  I used axes.hist with alpha=0.1

import pandas as pd
import numpy as np
from matplotlib import gridspec
import mplfinance as mpf

df = pd.read_csv(something)
data = df['close'].values
spec = gridspec.GridSpec(ncols=1, nrows=2, height_ratios=[2, 1])

fig = mpf.figure(figsize=(15,15))

ax1  = fig.add_subplot(spec[0])
ax11 = ax1.twiny()
ax11.hist(data, color='blue', orientation='horizontal', alpha=0.1, bins=np.arange(min(data), max(data), 0.01))
ax2 = fig.add_subplot(spec[1])

mpf.plot(CurrentDF, ax=ax1, type='candle', volume=ax2)
fig.suptitle("title", fontsize=16)
fig.savefig("output.png")

Again, thanks a bunch.
