### ISSUE TITLE
How to handle nan values when plotting signals

### ISSUE THREAD

**Issue by neothegod75** [matplotlib/mplfinance#259]
I am trying to plot signal markers for buy and sell with Candle. The code works when the list has atlease one value to plot but returns value error when all the the values in the dataframe are np.nan. Anyway to override this error to continue plotting if dataframe for any one signal is empty ( has all nan values)?

**Comment by DanielGoldfarb** [comment]
I assume you are calling `mpf.make_addplot()` to plot the signals; in which case (correct me if I am wrong) I would expect the error you are getting (which you have not specified) is coming directly from matplotlib (not mplfinance) in that `plt.scatter()` is being called with all nan values and matplotlib does not like that.  Please let me know if these assumptions are incorrect.

At any rate, calling a plot method and asking that method to plot **nothing** doesn't make much sense; randomly speaking, there is as much of a chance that it is an error as that it was intentional.  Therefore, philosophically imo, the libary should not remain silent. 
 Perhaps the library could issue a **warning** (instead of raising an exception) and then continue as if nothing happened.  Or alternatively we could require a kwarg for the user to say explicitly that passing in no data is intentional.  Either way, if my assumption is correct that the error is from matplotlib, this ***would require mplfinance to*** have specical code to check if all the values are nan, and if so it would then _bypass_ calling matplotlib and essentially ***ignore what it was otherwise told to do***.  

I'm not yet convinced that this appropriate behavior for the library.  I am more of the philosophy that ***if a method exists to plot data, and you have no data to plot, then don't call that method***.  Although putting a check for the all nan case into the library goes against this philosophy, I am not entirely opposed to it, ***IF*** I were convinced that it would be a ***very*** common occurence and that a large percentatage of users would frequently benefit.

In the meantime, your alternative is to check that `not all([x == np.nan for x in values])` before calling `mpf.make_addplot()` and call it only if `not all` is True.

**Comment by fxhuhn** [comment]
It's exactly the same as I mentioned in the following issue:

https://github.com/matplotlib/mplfinance/issues/103

**Comment by neothegod75** [comment]
> I assume you are calling `mpf.make_addplot()` to plot the signals; in which case (correct me if I am wrong) I would expect the error you are getting (which you have not specified) is coming directly from matplotlib (not mplfinance) in that `plt.scatter()` is being called with all nan values and matplotlib does not like that. Please let me know if these assumptions are incorrect.
> 
> At any rate, calling a plot method and asking that method to plot **nothing** doesn't make much sense; randomly speaking, there is as much of a chance that it is an error as that it was intentional. Therefore, philosophically imo, the libary should not remain silent.
> Perhaps the library could issue a **warning** (instead of raising an exception) and then continue as if nothing happened. Or alternatively we could require a kwarg for the user to say explicitly that passing in no data is intentional. Either way, if my assumption is correct that the error is from matplotlib, this _**would require mplfinance to**_ have specical code to check if all the values are nan, and if so it would then _bypass_ calling matplotlib and essentially _**ignore what it was otherwise told to do**_.
> 
> I'm not yet convinced that this appropriate behavior for the library. I am more of the philosophy that _**if a method exists to plot data, and you have no data to plot, then don't call that method**_. Although putting a check for the all nan case into the library goes against this philosophy, I am not entirely opposed to it, _**IF**_ I were convinced that it would be a _**very**_ common occurence and that a large percentatage of users would frequently benefit.
> 
> In the meantime, your alternative is to check that `not all([x == np.nan for x in values])` before calling `mpf.make_addplot()` and call it only if `not all` is True.

Thanks for looking into this.  You are spot on in your understanding the issue. I understand that the issue originates from matplotlib. In order to go around the behaviour, I am using 3 IF conditions 1 for each buy and sell signal and 3rd for the green path when values are present in both buy and sell list. 

By the way thanks for taking up the ownership of maintaining mplfinance. This is a great library and of immense help to traders.
