### ISSUE TITLE
Volume plot looks weird sometimes

### ISSUE THREAD

**Issue by schorschie** [matplotlib/mplfinance#26]
Did somebody experience this kind of look in the volume plot? The volume bars are so thick, that they overlap each other and they also seem to not match the time stamps of the candle bars:

![200205_1day](https://user-images.githubusercontent.com/13631749/73882719-dffb3a80-4862-11ea-8c30-5aab7893e7c6.png)

If I use no_xgaps, then it looks better, but that is not the behaviour I expected:
![200205_1day](https://user-images.githubusercontent.com/13631749/73882844-1cc73180-4863-11ea-9578-d66c0df594c2.png)

**Comment by DanielGoldfarb** [comment]
Without even looking at the code, I feel 98.44% certain that I know what the issue is.  The width of the bars need to be adjusted based on the amount of time between points.  I wrote code in `mpf.plot()` to do this for the candlesticks, but in my own testing I did not have volume for intraday data, so it apparently did not occur to me to do the same for volume.

**Comment by DanielGoldfarb** [comment]
**If you can attach the data you used for these two plots, that would be very helpful in finding and fixing this issue.**  

no_xgaps works by evenly spacing the data as integers along the x-axis (and then labeling them as datetimes) so that would explain why it looks better with no_xgaps == True (since the spacing between points is "wider" relative to the width of the volume bars.  

(By the way, with the next release (hopefully within a week) no_xgaps will always default to True).

**Comment by schorschie** [comment]
I tried Dataframe.to_dict() yesterday, but the string was to long and the Timestamp() function didn’t work immediately, as well. 

Would a pickle file without the Bollinger bands be OK? I could provide it this evening (CET). 

Regards 
Gregory 

PS thank you for reading and and answering every comment that quickly! I’m learning the code and hope I will be able contribute with pull requests soon.

**Comment by schorschie** [comment]
ok, got it:

```python
import mplfinance as mpl
import pandas as pd

a_frame = pd.read_pickle('data.pkl')

mpl.plot(data=a_frame,
         volume=True,
         savefig='xgaps.png')

mpl.plot(data=a_frame,
         volume=True,
         savefig='no_xgaps.png',
         no_xgaps=True)
```
[data.pkl.gz](https://github.com/matplotlib/mplfinance/files/4166667/data.pkl.gz)

**Comment by DanielGoldfarb** [comment]
Thanks.  That works.  I am able to reproduce, so I will be able to confirm that the fix works for your data.  Much appreciated.

**Comment by schorschie** [comment]
Hello,
so I reinstalled ```mplfinance``` like this:
```bash
git submodule add  git@github.com:matplotlib/mplfinance.git 
pip3 install virtualenv
virtualenv _venv
source _venv/bin/activate
cd mplfinance
python3 setup.py install
```
But if I try to debug into mplfinance it tells me
```Could not load source '<__array_function__ internals>': Source unavailable.```
How can I fix this?

UPDATE: sctually solved it myself: it is a Visual Studio Code issue, the configuration as to be set to:
```json
"configurations": [
    {
        "justMyCode": false
    }
]
```
https://code.visualstudio.com/docs/python/debugging

regards
Gregory

**Comment by DanielGoldfarb** [comment]
I've fixed this, but (due to time constraints on other projects) I am not going to release the fix for another week or two.  In the meantime, if you want to implement the fix yourself this is it:

In `plotting.py` find this line of code:

    ax2.bar(xdates,volumes,width=0.7)

And change to this instead

    width = 0.5*avg_dist_between_points
    ax2.bar(xdates,volumes,width=width)

Alternatively you can, of course, just set `no_xgaps=True` as a workaround.

**Comment by schorschie** [comment]
Thank you it worked.
