### ISSUE TITLE
Animating mplfinance candle

### ISSUE THREAD

**Issue by asim800** [matplotlib/mplfinance#262]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.

I am trying to animate/blit plot(type=candle) with FuncAnimation. As I understand it, typically requires the plot function to return an artist that can be updated with new data.
Right now, I am running mpf.plot in a for loop after clearing axes but it seems too slow.

Should I go back to older mpl_finance because 'candlestick_ochl' seems to return a tuple of (lines, patches).

Any guidance will greatly appreciated.
Thanks
Asim

**Comment by DanielGoldfarb** [comment]
If you look into the animation examples in the [**examples folder**](https://github.com/matplotlib/mplfinance/tree/master/examples) and [**listed here**](https://github.com/matplotlib/mplfinance/blob/master/markdown/animation.md#animation-support-in-mplfinance), you will see that all of those examples _repaint the entire plot_ with each animation cycle.  This is because, as stated in the example `.py` files

> ... presently mplfinance does not support "blitting" (blitting makes animation
more efficient).  Nonetheless, the animation is efficient enough to update at least
once per second, and typically more frequently depending on the size of the plot.

I want mplfinance to support blitting at some point.  As you pointed out, it requires returning the Artists, and (if I understand it correctly) for maximum efficiency it would require the ability to update only those artist that change with each animation cycle.  The first challenge is that, with all the flexibility that mplfinance offeres, there potentially can be a large number of various Artists in the Figure.  It will take some time to restructure the mplfinance code to keep track of all the Artists, and presently I do not have that much time available to dedicate to supporting blitting.  

Alternatively you may consider setting `returnfig=True` and calling `.get_children()` on the Figure, and then [recursively calling `.get_children()`](https://stackoverflow.com/a/43638885/1639359) on each child returned, to generate a full list of all the Artists in the Figure.

If you have some time to look into this to determine the best way to make blitting work with mplfinance, I will be very grateful and will implement the solution you find (or you can submit a PR).  

If you decide to use the old API in the meantime, keep in mind that you do _not_ have to install the old package, but can access the old API from this current package via 
```python
from mplfinance.original_flavor import candlestick_ochl
```

HTH.  Let me know.  Thanks.

**Comment by asim800** [comment]
Thank you so much for a very helpful response.

**Comment by dir** [comment]
Hey there @DanielGoldfarb, 

Has blitting been implemented yet? If it hasn't I would like to take my hand at helping out with this, as it is very necessary for one of the programs I am writing. 

Cheers,
Luke
