### ISSUE TITLE
X-Axis not appearing on Intraday data

### ISSUE THREAD

**Issue by mjessa12** [matplotlib/mplfinance#269]
I'm trying to plot simple intraday data, however, the x-axis is not appearing correctly.  I have converted the date+ time into a pandas datetime object, but still not displaying correctly. Everything else works fine.

![2020-10-02 14_36_57-main py – main py](https://user-images.githubusercontent.com/72001246/94957988-c3300900-04bc-11eb-888a-735d85f648bf.png)

**Comment by DanielGoldfarb** [comment]
@mjessa12 

It looks like your datetimes are not properly converted.  The DataFrame index must be of type `pandas.DatetimeIndex` (***not*** type `pandas.datetime`).

If I could see your whole code, including where you read the data into the DataFrame and how you construct the DataFrame, then I may be able to provide more advice.  You also have not displayed the top portion of the output from your `print(iday.head(5))` which is also important to see.  But from everything that I can see, you DataFrame index is not correctly formed, and the problem is with that (not with the plot).

In addition to the information mentioned above that would be important to see (i.e. how you read and construct your dataframe, and the *full output* from the head of your DataFrame), it would be helpful also to see the full output from:

```python
print(type(iday.index))
print(type(iday.index[0]))
```

Thank you.

**Comment by mjessa12** [comment]
Hi Daniel,

yes you are correct - for some reason the indexing was adding another column (the 1970-01-xxxxx) but the solution using datetime is to add : infer_datetime_format=True.  Otherwise, It worked when I switched to Datetimeindex.

Thank you!
