### ISSUE TITLE
Volume not display for mplfinance.plot

### ISSUE THREAD

**Issue by Peekay19** [matplotlib/mplfinance#271]
I have a data frame of daily QQQ historical prices. I resampled the "Adj Close" to 10-day and the volume with a sum function.  I added the resampled volume to the "Adj Close" data frame.
I'm able to plot the "Adj Close" with mplfinance, with volume=True, the volume is not displaying, but I'm receiving an error message, even with Volume being part of the data set.

Here are some of the code:
```python
df_olhc = df1['Adj Close'].resample('10D').ohlc()
df_volume = df1['Volume'].resample('10D').sum()
df_olhc['Volume']= df_volume
df_olhc.to_csv('data\\10DAYQQQ.csv')
df_olhc1 = pd.read_csv('data\\10DAYQQQ.csv', parse_dates=True, index_col=0)
#df_volume.head()
#df1['Volume'].tail()
df_olhc1.tail()

#df_olhc1.tail(5)
#df_olhc.tail(5)
#df1.tail(5)
#mpf.plot(df1.tail(30),volume=True )
mpf.plot(df_olhc1.tail(30),volume=True)
```
Output:
```python
                         open	         high	         low	                 close	        Volume
Date					
2020-08-14	272.160004	281.869995	272.160004	281.869995	173603700.0
2020-08-24	283.630005	302.760010	283.630005	302.760010	314559100.0
2020-09-03	287.410004	287.410004	269.950012	270.450012	539760600.0
2020-09-13	275.160004	279.059998	266.869995	272.480011	388633900.0
2020-09-23	264.160004	282.250000	264.160004	274.309998	434717600.0

ValueError                                Traceback (most recent call last)
<ipython-input-66-27e13a1ddb63> in <module>
     24 #df1.tail(5)
     25 #mpf.plot(df1.tail(30),volume=True )
---> 26 mpf.plot(df_olhc1.tail(30),volume=True)

~\anaconda3\lib\site-packages\mplfinance\plotting.py in plot(data, **kwargs)
    330 
    331     if config['volume'] and volumes is None:
--> 332         raise ValueError('Request for volume, but NO volume data.')
    333 
    334     if external_axes_mode:

ValueError: Request for volume, but NO volume data.

<Figure size 800x575 with 0 Axes>
```

**Comment by DanielGoldfarb** [comment]
Peter,

I am ***guessing*** it is because of the mixed case of your column names.  
With mplfinance you have **three** choices for your column names:
1. All capitalized ('Open', 'High', 'Low', 'Close', 'Volume')
2. All lower case: ('open', 'high', 'low', 'close', 'volume')
3. Specify your own column names with the `columns=` kwarg:  
You must provide a tuple or list of 5 strings which will then be mapped to correspond to 'Open', 'High', 'Low', 'Close', and 'Volume' (in that order).  **In your code** example, it seems to me the following will probably work:
```python
mpf.plot(df_olhc1.tail(30),volume=True,columns= ('open', 'high', 'low', 'close', 'Volume'))
```

Please let me know if one of the above three solutions works.  All the best.   --Daniel

---

If you are interested in some mplfinance history on this topic, and why only the above three options are available, please read the following two comments:
1. https://github.com/matplotlib/mplfinance/issues/195#issuecomment-650837064
2. https://github.com/matplotlib/mplfinance/issues/82#issuecomment-619585700

**Comment by Peekay19** [comment]
Thank you, Daniel. Your suggestion fixed the issue.
