### ISSUE TITLE
Logarithmic price scale

### ISSUE THREAD

**Issue by whyrv** [matplotlib/mplfinance#272]
Hi Daniel, Is it possible to set the Y axis to use log price scale (default seems to arithmetic, unless I'm mistaken). thanks

**Comment by DanielGoldfarb** [comment]
At present there is no direct setting for a logarithmic scale.
 
You have to gain access to the Axes and then "manually" set the yscale to 'log' yourself.

There are two ways to gain access to the Axes objects [**as described here**](https://github.com/matplotlib/mplfinance/issues/219#issuecomment-671292326).

For an example, see https://github.com/matplotlib/mplfinance/issues/21#issuecomment-621000567.

Please let me know if you are interested in implementing this feature for mplfinance so that users can simply write:
```python
mpf.plot(df,yscale='log')
```

**Comment by whyrv** [comment]
Thanks Daniel, I will look into the previous comments.  (I am not proficient enough to do the implementation for mplfinance yet.)
