### ISSUE TITLE
Feature Request: stack another indicator on the mpf.plot() with axes.twinx()

### ISSUE THREAD

**Issue by ggg5269** [matplotlib/mplfinance#282]
Is it able to plot a data from pd.DataFrame() (or pd.Series()) object on the axes after mpf.plot()? like plot on to the secondary y axis.

actually the figure i'm going to plot is place a drought index on to corn futures ohlc candlestick plot, somehow it shows up an error with datetime format.

sorry about my grammar, i can post the error message tomorrow and also source data or screenshots.

**Comment by DanielGoldfarb** [comment]
Did you read the documentation?

Please read, completely, the following, *in this order*, and then see if maybe your question is answered:

1. https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb
2. https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb
3. https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md

Thanks.  All the best.  --Daniel

**Comment by ggg5269** [comment]
Hi Daniel,
thanks for your reply. 
I've read all the doc and example code, and make some adjustment of my code.

```
fig = mpf.figure(figsize=(16, 7), tight_layout=True,style='default')
ax1 = fig.add_subplot(111)
apds = [
    mpf.make_addplot(drought.sum(1), ax=ax1, secondary_y=True),
]

mpf.plot(c,addplot=apds, ax=ax1,volume=False)
```
![image](https://user-images.githubusercontent.com/37011770/97250523-1a699500-1841-11eb-8f4a-e022db15ca3b.png)

this is what i get after setting secondary y axis, but still have the candlestick at the bottom.
where is my mistake?

**Comment by DanielGoldfarb** [comment]
@ggg5269 
In my experience, problems similar to this are usually caused by data (not code), either because of the data itself, or possibly the way the data is formatted.  I do not see anything *obviously* wrong with the code.  

(That said, as a general rule I would strongly recommend *against* creating and using Figure and Axes, as you are, unless you are trying to accomplish something that is otherwise not supported by mplfinance; however it appears to me that what you are trying to do is definitely supported by a simple use of `mpf.make_addplot()` and `mpf.plot()` *without* any need to access the Figure or Axes directly.  *But, for now, don't bother changing the code*, because it should be working the way you have it.  First let's address the problem you are seeing.)

So in order to help you solve this problem, I would need to see the data you are using, and the code that processes the data.  

**Please attach you data** (preferably as csv files, or as whatever format you are using), ***and include also all of the code*** that prepares that data, reading it in, and placing it into the variables that get passed to mplfinance.

Thank you.  --Daniel

**Comment by ggg5269** [comment]
[agri.xlsx](https://github.com/matplotlib/mplfinance/files/5448894/agri.xlsx)
here's how iI read the excel file for **corn future price**.
```
import pandas as pd

c = pd.read_excel("price_data/agri.xlsx", sheet_name='C 1 Comdty')
c.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
c = c.set_index('Date')
```
And for the **drought index**,  
[dm_export_20000101_20201026.zip](https://github.com/matplotlib/mplfinance/files/5448905/dm_export_20000101_20201026.zip)

```
drought_df = pd.read_csv("dm_export_20000101_20201026.csv", parse_dates=['MapDate']).sort_values('MapDate').iloc[:, [0, 3, 4, 5, 6, 7]]
drought_df.columns = ['Date', 'D0', 'D1', 'D2', 'D3', 'D4']
drought_df = drought_df.set_index("Date")

drought_df = drought_df.apply(lambda x: x.str.replace(',','')).astype(float, errors='ignore')
```
And then I do some manipulation to make sure they got **same index range**
```
drought = pd.DataFrame(index=c.index)
drought = pd.concat([drought, drought_df], 1).fillna(method='ffill')
```
Finally I get the fig which was shown in the previous comment.

**Comment by DanielGoldfarb** [comment]
> And then I do some manipulation to make sure they got same index range

Can you please dhow this code too?  I just want yo make sure it is not having some unexpected accidental side-effect on the data. 

I want to be sble to completely reproduce, on my own machine, the problem you are seeing. 

Thanks you.

**Comment by DanielGoldfarb** [comment]
OK.  I was able to reproduce and I found the problem.  
**The problem is indeed that you are passing in your own Axes objects**, in which case mplfinance can only assume you want to use the specific Axes objects that you pass, which means `secondary_y=True` must be ignored (because *a secondary_y is actually another Axes object*).

**I strongly recommend** that you ***do not*** create your own Figure and Axes.

**Instead, keep your code simple, as shown in "Fix Number 1" below.**
(However if you really want to create and use your own Axes, it can still be done that way; see "Fix Number 2" below.)

---
**To fix the problem, do ONE of the following:**

---

## Fix Number 1 (preferred)

**Instead of:**
```python
fig = mpf.figure(figsize=(16, 7), tight_layout=True,style='default')
ax1 = fig.add_subplot(111)
apds = [mpf.make_addplot(drought.sum(1), ax=ax1, secondary_y=True),]
mpf.plot(c,addplot=apds, ax=ax1,volume=False)
```
**Do the following:**
```python
apds = mpf.make_addplot(drought.sum(1),secondary_y=True)
mpf.plot(c,addplot=apds,volume=False,figsize=(16, 7),tight_layout=True)
```
**Here is the result:**

![image](https://user-images.githubusercontent.com/11164790/97386798-078baa80-18ab-11eb-914f-b5eefb8b07ae.png)


---

## Fix Number 2 (NOT preferred)

**Add the line: `ax2 = ax1.twinx()` and use `ax2` in `make_addplot()`, thus:**
```python
fig = mpf.figure(figsize=(16, 7), tight_layout=True,style='default')
ax1 = fig.add_subplot(111)
ax2 = ax1.twinx()
apds = [mpf.make_addplot(drought.sum(1), ax=ax2, secondary_y=True),]
mpf.plot(c,addplot=apds, ax=ax1,volume=False)
```

**Here is the result:**

![image](https://user-images.githubusercontent.com/11164790/97386977-6ea95f00-18ab-11eb-823f-436b441b3481.png)

---

**NOTICE THAT** in "Fix Number 2" you can see a vertical line on the left side at the beginning of the `drought` data.  This is because the first row in the `drought` data is all `NaN`.  (Therefore, you may want to drop the first row from both data sets).  You can see this more clearly if you plot only the first 150 rows (and use plot `type='candle'`) ...

![image](https://user-images.githubusercontent.com/11164790/97387958-77029980-18ad-11eb-80bc-4d4848958463.png)

**Comment by ggg5269** [comment]
wow, thanks for your detailed answer.
now I know what's going on with the axes, 
I'll change my code to the first one~

**Comment by ChrisChiasson** [comment]
This is the most outstanding help from a package maintainer I have read in a very very long time.
