### ISSUE TITLE
Animation external Axes Panel

### ISSUE THREAD

**Issue by fremaxter** [matplotlib/mplfinance#288]
Hey, Im using the animation function for plotting live Data. In order to do so, mpf.plot needs external axes mode. There is an example where mpf.plot returns the figure and axes and one where axes and figure are created externally.

For exampe, i want to make a macd chart design, but want to modify the figure (e.g change the tab/figure name). Is there any way to do so?

**Comment by DanielGoldfarb** [comment]
It sounds like you want the Figure Title to change as part of the animation.  (please correct me if I am wrong about that).

First, regarding the anitmation examples, one ... 
> ... where mpf.plot returns the figure and axes and one where axes and figure are created externally.

This is irrelevant to your question (if I correctly understand your question to be able animating the Figure Title).  Regarding these two styles of mplfinance animation, there is essentially no difference from the animation point of view.  It just a matter of whether or not you want mplfinance to create the Figure and Axes using the "Panels" method so that you (the user) don't have to worry about carefully stacking up your Axes objects into nicely sized and aligned panels.

Regarding animating the Figure Title, this would be easy if there were a way to pass the Figure object into `mpf.plot()`.  We can certainly add that ability.  But also, there are two relatively easy workarounds:
1. use kwarg `axtitle` *instead of* `title`.
2. use matplotlib's `fig.suptitle()` method external to `mpf.plot()`

---
Here are some code changes that you can make to [**the MACD animation example**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py) to ***demonstrate*** **each of the above workarounds**:

---
#### 1. Use kwarg `axtitle` *instead of* `title`.
- Modify [**line 51**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py#L51) by changing kwarg **`title`** ***to*** **`axtitle`**
- Just **before** [**line 86**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py#L86) add the following line of code:
```python
title_str = "\n\n== MACD " + str(ival) + " =="
```
- Modify [**line 86**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py#L86) to add kwarg `axtitle=title_str` like this:
```python
mpf.plot(data,type='candle',addplot=apds,ax=ax_main,volume=ax_volu,axtitle=title_str)
```

---
#### 2. Use matplotlib's `fig.suptitle()` method external to `mpf.plot()`

Just **below** [**line 86**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py#L86) add the following two lines of code:
```python 
title_str = "\n\n== MACD " + str(ival) + " =="
fig.suptitle(title_str,size='x-large',weight='semibold',va='center')
```

---
Please let me know if that helps.
All the best.  --Daniel

**Comment by fremaxter** [comment]
Thanks for your detailed answer.
I tested it right now, not excately what I meant, but somehow a fix.

It was kinda what I meant, but i had another general Question.
I also wanted to change the name of the whole Window (static would be enough mostly). For example in the example or generally most mplfinance plots, it says figure1 at the top, and in linux/windows the tab of the window shows "figure1" as name.


If i use normal matplotlib i can give the figure a name, and also with mpf e.g. fig = mpf.figure("figure name, for example Apple", style=s...). In the macd function, the figure is a result of mpf.plot() and therefore I cant or dont know how to change a attribute.

I don't want to cause you much trouble or effort, but if you have the time.
If you unsure, what I mean, just ask bevore making an effort.
Thanks -fremaxter

**Comment by DanielGoldfarb** [comment]
Aha.  Got it.   I was wondering about your use of the word "tab" in  "tab/figure name."  Now I understand.  
So you want to change the title of the *Window* that the Figure is in.

There are two ways to do that:

1. When using the **`returnfig=True` method of external axes mode**, then **immmediately after** [**line 52**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py#L51-L52) insert a call to `fig.canvas.set_window_title()`, for example:
```python
fig.canvas.set_window_title("THIS IS MY MACD WINDOW")
```

2. When using the **`mpf.figure()` method of external axes mode**, then set the Window title **when calling `mpf.figure()`**. <br> For example, using [**animation_demo1**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo1.py) as an example, **modify** [**line 18**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo1.py#L18) by either passing in the Window Title/Name as the first argument, **or** using kwarg **`num=`**.  Thus either of the following will work:
```python
fig = mpf.figure("MY WINDOW NAME",style='charles',figsize=(7,8))
```
```python
fig = mpf.figure(style='charles',figsize=(7,8),num="MY WINDOW NAME")
```

Hope that helps.  Let me know.  Thanks.  
--Daniel

**Comment by fremaxter** [comment]
Thanks alot, the 1. one was what is was looking for.

Solved


Could you maybe tell me how you figured that out, or how you tried to work it out. Im just curious, and want to improve learning on my own. 
I mean, I figured the 2. way was possible, but then I coudn't use the multiGraph Panel (like in macd) from mplfiance. 
And i didn't know how you could change the figure returned by mplfinance, searched it but found no solution, so thought it's not possible. 

Thanks again for your effort.
--fremaxter

**Comment by DanielGoldfarb** [comment]
No problem.  Glad it worked.   I just googled "matplotlib figure window title".   **I think the key was having the word "window" in the search**.  The first two search results contained the necessary info:
- https://stackoverflow.com/questions/5812960/change-figure-window-title-in-pylab
- https://github.com/jupyter/notebook/issues/919

I then tried each approach out on my own machine to make sure they worked.
