### ISSUE TITLE
Can I create clustered Bar chart using mplfinance 

### ISSUE THREAD

**Issue by sunilfussey** [matplotlib/mplfinance#293]
Dear Sir,

Can I create clustered bar chart like the one shown below.  screenshot and excel file data/attached herewith.

Strike | Call OI | Put OI | Call Price | Put Price
-- | -- | -- | -- | --
1000 | 3000 | 2400 | 75.00 | 11.00
1100 | 2500 | 3500 | 73.35 | 17.75
1200 | 2800 | 2240 | 65.00 | 25.00
1300 | 2900 | 2320 | 61.75 | 35.00
1400 | 4000 | 5000 | 55.00 | 40.00
1500 | 3000 | 2400 | 50.00 | 45.00
1600 | 2000 | 1600 | 44.00 | 43.50
1700 | 500 | 700 | 40.00 | 41.00
1800 | 3000 | 2400 | 23.85 | 45.00
1900 | 2500 | 2000 | 25.00 | 49.25
2000 | 1000 | 2000 | 10.00 | 55.75

![image](https://user-images.githubusercontent.com/71934449/100387195-7ba5a380-304d-11eb-8e7a-727bebdf600d.png)

![image](https://user-images.githubusercontent.com/71934449/100387252-a7288e00-304d-11eb-931d-10a1ff3a38de.png)

[OI vs Price Strike wise.xlsx](https://github.com/matplotlib/mplfinance/files/5604747/OI.vs.Price.Strike.wise.xlsx)

**Comment by DanielGoldfarb** [comment]
Hi Sunil,
mplfinance is specifically designed to expect datetimes on the x-axis.  However what you want to do should be easy using Pandas Dataframe plot().  (You can also certainly do it with matplotlib directly, but this is a little more complicated).

In theory, the following should work, but for some reason, for me, it is not displaying the line plots of the prices.
I put your data into a CSV file called oi_vs_strike.csv, then
```python
import pandas as pd
df = pd.read_csv("oi_vs_strike.csv",index_col=0)
ax = df.plot(y=['Call OI','Put OI'],kind='bar')
df.plot(y=['Call Price','Put Price'],kind='line',linewidth=4,ax=ax,secondary_y=True)
```

![image](https://user-images.githubusercontent.com/11164790/100405270-42f7d100-3031-11eb-93f9-ca2dc8b8d94f.png)

***As far as I know, the above code should work.  Still trying to figure out why the line plots of price are not appearing.***

---
***If I change the code to make all line plots (instead of bar plus line) then it works like this:***
```python
ax = df.plot(y=['Call OI','Put OI'],kind='line',figsize=(9,6))
df.plot(y=['Call Price','Put Price'],kind='line',linewidth=4,ax=ax,secondary_y=True)
```
![image](https://user-images.githubusercontent.com/11164790/100405424-91a56b00-3031-11eb-901e-7be70875776b.png)

**Comment by DanielGoldfarb** [comment]
I got it to work, following the instructions here: https://stackoverflow.com/a/63667160/1639359

It seems (perhaps due to a change to pandas), that now, in order to mix bar and line charts, pandas requires the x-axis data to be of type string, so you have to add the line: **<br>&nbsp;&nbsp;`df.index = df.index.astype(str)`**

I also added the `color` kwarg to the second call to `df.plot()`; and `width=0.8` just to make the bars look better.

```python
import pandas as pd
df = pd.read_csv("oi_vs_strike.csv",index_col=0)
df.index = df.index.astype(str)
ax = df.plot(y=['Call OI','Put OI'],kind='bar',width=0.8,figsize=(9,6))
df.plot(y=['Call Price','Put Price'],kind='line',linewidth=4,ax=ax,secondary_y=True)
```
The result:

![image](https://user-images.githubusercontent.com/11164790/100406930-1645b880-3035-11eb-91fb-fbec98a1c65d.png)

**Comment by sunilfussey** [comment]
Hi Daniel,  

Thanks a lot for replying to my query and providing a solution.  Yes, it's working now as expected.  
Sorry to give you one more trouble.  
Strike values on X-axis are displayed as float instead of integer and they look joined or overwritten. The screenshot is given below. Please provide code to remove extra values from strike i.e. remove ".0" as suffix to strike value and text-align of Strike values vertically.  I searched on google and various websites for hints but it didn't help me.  

Below is the code that I am using and may be modified to incorporate the above request. Once again many many thanks!

import pandas as pd
import pyodbc 
import matplotlib.pyplot as plt
import matplotlib.ticker
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
                      'Database=NSESQL;'
                      'Trusted_Connection=yes;')

cursor = conn.cursor()

sql_query1 = '''
select Strike_Pr as Strike,Option_Typ as OptionType,[Timestamp] as [Date],[Open], [High], [Low], [Close], OPEN_INT as OpenInterest,CHG_IN_OI as OIChange
from dbo.DailyMarketDataFO where 
Symbol='NIFTY'
and Option_Typ in ('CE','PE')
and EXPIRY_DT='26-Nov-2020'
and [TIMESTAMP] = '25-Nov-2020'
'''
df1 = pd.read_sql(sql_query1,conn)
df2 = df1[df1['Strike'].between(12500,13500)]
#df2

# Renaming the column names using DataFrame.swaplevel with map and join:
df2 = df2.pivot(index='Strike', columns='OptionType', values=['OpenInterest', 'Close']).swaplevel(0,1,axis=1)
df2.columns = df2.columns.map('_'.join)
# print (df2)


# since we have mix bar and line charts, converting x-axis to string

df2.index = df2.index.astype(str)
ax = df2.plot(y=['CE_OpenInterest','PE_OpenInterest'],kind='bar',width=0.8,figsize=(9,6))
df2.plot(y=['CE_Close','PE_Close'],kind='line',linestyle='-', marker='o', linewidth=4,ax=ax,secondary_y=True)

# formatting Y axis to avoid long integer conversion to scientific numbers/notations
ax.ticklabel_format(useOffset=False, style='plain', axis='y')

plt.xlabel('Option Open Interest')
plt.ylabel('Option Price')
plt.title('Call and Put OI vs Price\nStrike wise')
plt.show()

![image](https://user-images.githubusercontent.com/71934449/100447123-0631e580-30d6-11eb-968a-e60fbcb6ae49.png)

**Comment by DanielGoldfarb** [comment]
Try the following:
- Change `df2.index = df2.index.astype(str)` to **`df2.index = df2.index.astype(int).astype(str)`**
- Add **`ax.tick_params(axis='x',rotation=45)`**

**Comment by sunilfussey** [comment]
It works.  Thanks a lot!
