### ISSUE TITLE
Custom marker symbol

### ISSUE THREAD

**Issue by amiaty** [matplotlib/mplfinance#30]
Hi Daniel,

Thank you for your effort. I want to use custom marker symbols in mplfinance.make_addplot when scatter somethings. Is it possible to use a custom character as in matplotlib?

https://matplotlib.org/examples/pylab_examples/scatter_symbol.html
 or even SVG:
https://stackoverflow.com/questions/14324270/matplotlib-custom-marker-symbol

**Comment by DanielGoldfarb** [comment]
Thank you for your appreciation and interest in `mplfinance`.  This issue is not a priority for me at this time, relative to other changes that need to be done.   It might possibly work already, since the `mpf.plot()` code simply passes the value of the `marker` kwarg into `matplotlib` function `Axes.scatter()`  ... that's my impression having glanced at the two links you provided.  However, you will have to make a small code change to even test if it will work; see below.

If you would like to test and see if you can get it working that's fine with me; if so, I will merge the code.  The only issue is that [the code here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L465-L484) prevents all but certain values from being passed in with the kwarg `marker`.  

Therefore, in order for you to test, you can clone the code and modify [the kwarg Validator for `marker`](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L483) to allow pretty much any value through.  One way to do that would be to change the line:

    'Validator'   : lambda value: value in valid_markers },

to 

    'Validator'   : lambda value: not isinstance(value,bool) },

That will allow you to pass anything except a bool as the `marker` and that will allow you to test whether passing in a custom marker works for you.  Let me know how it turns out.  I will keep this issue open until you are someone else works on it (but as I said I have other items to work on at this time).

**Comment by amiaty** [comment]
Hi Daniel,
I did your suggestion and it works properly with svg and other kind of symbols.
Now, what is the point of valid_markers list when using this new validator?

**Comment by DanielGoldfarb** [comment]
Thanks.  I agree; now there is no point to the valid_markers list.  May as well let anything through.  That said, I am thinking my suggestion of "`not isinstance(value,bool)`" is a bit kludgy.   Perhaps "`is not None`" would be cleaner/better.  Please test with "`value is not None`" and let me know if that works.  If so, please also delete the `valid_markers_list`, test and push both of those changes to your fork which should automatically propagate them through to the pull request.  Keep me posted.  Thank you for your contribution.

**Comment by amiaty** [comment]
Thank you Daniel, I think `value is not None`  does not make sense, since it is only false when `marker=None` 
Maybe, `lambda value: isinstance(value,str) and bool(value and value.strip())` would be a better choice, because it could reject empty string or string of blanks symbol.
```
print is_not_blank("")    # False
print is_not_blank("   ") # False
print is_not_blank("ok")  # True
print is_not_blank(None)  # False
```
if you are agree with this, I can send new pull request.

**Comment by DanielGoldfarb** [comment]
I am confused.  The idea behind "`value is not None`" was basically to allow the user to pass *any type* in via kwarg "`marker=`" (i.e effectively no validation at all for that kwarg).  

I was thinking, when you said "it works properly with svg and other kind of symbols," that maybe you wanted to pass in objects *other than strings.*  But if all custom marker symbols (svg and otherwise) can be adequately described by a string, then your validator is fine.  

I was also partially confused by this answer here: https://stackoverflow.com/a/58552620/1639359 which seems to indicate that you can also pass in type `matplotlib.path.Path` via `marker=`.   If you are satisfied with strings alone in the validator, please confirm and I will merge the PR.  Or let me know if you want to add `matplotlib.path.Path`.  Thanks again for your contribution to this project.  Much appreciated.

**Comment by amiaty** [comment]
yes, you are right. I forgot to check SVG marker with this validator `lambda value: isinstance(value,str)`, I though it is also string like latex markers.

I agree `not isinstance(value,bool)` is a bit kludgy, but it works for all type of markers that I have test.

**Comment by DanielGoldfarb** [comment]
This is now released to Pypi.   Btw, there is now a new internal function, ["`_bypass_kwarg_validation()`"](https://github.com/matplotlib/mplfinance/blob/6d2638f8d490742f57d24e53ae0f99d19116a3aa/src/mplfinance/_arg_validators.py#L59-L66), which can be used as the kwarg validator in order to allow any value through, [as is being done here for `marker`](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L480).  

In general [`_bypass_kwarg_validation()`"](https://github.com/matplotlib/mplfinance/blob/6d2638f8d490742f57d24e53ae0f99d19116a3aa/src/mplfinance/_arg_validators.py#L59-L66) is for cases where the rules for kwarg validation are either not completely known, or are complex and not worth doing before the kwarg is actually used (in which case if it is invalid it will fail anyway).
