### ISSUE TITLE
Display mutliple figures in different windows at once

### ISSUE THREAD

**Issue by helloworldnoob** [matplotlib/mplfinance#302]
I would like to show different graphs, on different windows all at once.

At the moment I am using 3 mpf.plot() candlestick graphs, which displays one, then I close the first, get the 2nd etc.

Sorry if it is a noob question, I have looked for a while online and can't seem to find anything on it.

**Comment by DanielGoldfarb** [comment]
when calling `mpf.plot()` add kwarg `block=False`:
```python
mpf.plot(data,...,block=False)
```

You may want to ***not*** add `block-=False` to the **last** `mpf.plot()`, or some by some other means (for example, by requesting input) prevent your script from exiting, otherwise when the script exits all three windows will go out of scope and close.

**Comment by helloworldnoob** [comment]
Thank you very much!  I had block=True before, obviously wasn't working!

If anyone is confused from the answer, I added the kwarg `block=False ` to each plot I didn't want to show one by one, except the final mpf.plot(data), which then gave me all figures at once as expected.

**Comment by helloworldnoob** [comment]
Thank you very much! Did respond and I closed the question, not sure what happened there...
