### ISSUE TITLE
I always get line plot no matter what plot type i choose, am i missing something or it's a bug?

### ISSUE THREAD

**Issue by ddtuan99** [matplotlib/mplfinance#307]
**Describe the bug**
On Jupyter Notebook, I try to plot a stock dataframe which has DatetimeIndex as index and 4 column Open, High, Low, Close. But no matter what `type` i choose, i always get a line plot. I've noticed that `type` appear as keyword of Python's builtin funtion (which return type of an object) in the notebook editor.

**Screenshots** and **To Reproduce**
![image](https://user-images.githubusercontent.com/48643969/103355113-5a4d3280-4aa5-11eb-83b1-fad1d0400bc0.png)
![image](https://user-images.githubusercontent.com/48643969/103355122-63d69a80-4aa5-11eb-8bb7-24f692d43ea3.png)

**Expected behavior**
Get a candlestick plot

**Comment by ddtuan99** [comment]
I actually get canddlestick but my dataframe has alot of records. The graph appears like a line plot.
Is there a way to make candlestick more visible?
Really appreciate your time!

**Comment by DanielGoldfarb** [comment]
As you noticed, you actually do have candlesticks, but you have so many of them in a small space they are difficult to see.  This is a limitation that you will encounter with every graphics or plotting package, but there are a few things you can do, depending on what your goals are.

First, understand you are plotting (what looks to me to be) about 20 years worth of daily candlesticks, which means that you are trying to view over 5000 candlesticks on a chart maybe 20 centimeters wide.  That means each candlestick is at best 0.05 millimeters, which is less than the resolution limit of the human eye.  That's assuming your monitor has an even higher resolution, which is likely not the case.  Consider my own monitor, the resolution is 1920x1080, less than a half pixel per candlestick assuming my plot is full screen.  There is no way I would be able to distinguish that many individual candlesticks at that resolution.

So what can you do?  Here are a few ideas:  
1. First you can try making the figure larger (with the `figscale=` kwarg), and plot the figure on a high resolution monitor or print it with a high resolution printer.  Given the amount of data you are trying to plot, it is unlikely that this will help much.  
2. Plot less data, or zoom in on some specific period of time that is of interest to you.  Do you really need to see 20 years worth of data?  Or would 3 to 6 months of daily data be adequate for what you are trying to accomplish.  
3. Alternatively if you *do* really want to examine a 20 years of data, are ***daily*** OHLC values going to be significant in the context of 20 years of data?  Probably not.  Consider [**resampling your data**](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas) so that each candle represents the Open, High, Low, and Close for a ***a single month, or even a single quartly***.  For 20 years of data, quartly candlesticks still means some 80 candles on the screen to eyeball.  That's a lot.  And if monthly then that's 240 candlesticks, which is do-able, but still a lot to look at and make sense of with your eye.

As an example, consider the 9.25 years of Intel prices [in the examples folder](https://github.com/matplotlib/mplfinance/blob/master/examples/data/yahoofinance-INTC-19950101-20040412.csv) of this repository, and the following code to plot it as is (daily) and resampled as weekly, monthly, and quarterly data:
```python
import pandas as pd
importa mplfinance as mpf
df = pd.read_csv('data/yahoofinance-INTC-19950101-20040412.csv',index_col=0,parse_dates=True)
df.shape
aggregation = {'Open'  :'first',
               'High'  :'max',
               'Low'   :'min',
               'Close' :'last',
               'Volume':'sum'}
dfw = df.resample('1W').agg(aggregation)
dfm = df.resample('1M').agg(aggregation)
dfq = df.resample('1Q').agg(aggregation)
kwargs=dict(volume=True,type='candle',tight_layout=True)
mpf.plot(df,**kwargs,title='\nINTC Daily   ')
mpf.plot(dfw,**kwargs,title='\nINTC Weekly     ')
mpf.plot(dfm,**kwargs,title='\nINTC Monthly        ')
mpf.plot(dfq,**kwargs,title='\nINTC Quarterly         ')
```
---
### The results are as follows:
(This is all exactly the same data, only resampled at various frequencies.  Personally I think for the almost 10 years of data, the *monthly* resample looks best.  However I'm guessing that for 20 years of data, I would find a *quarterly* resample easiest to understand from a visual analysis perspective.)

---
![image](https://user-images.githubusercontent.com/11164790/103370727-8a8fd380-4a9b-11eb-94ee-4a019e9f14c3.png)

---
![image](https://user-images.githubusercontent.com/11164790/103370734-8fed1e00-4a9b-11eb-8aa2-9a834073df6f.png)

---
![image](https://user-images.githubusercontent.com/11164790/103370747-97acc280-4a9b-11eb-91db-c5644faff665.png)

---
![image](https://user-images.githubusercontent.com/11164790/103370762-a004fd80-4a9b-11eb-9de3-897a3e5ffb42.png)

**Comment by ddtuan99** [comment]
Thank you so much for this and for your time mantaining this package. Your respone is really helpful to me. I've been familiar Pandas and data processing for a while but haven't learnt resampling concept. You gave me alot of useful information, even code and screenshot. 
Thank you very much.
I wish you have a happy, healthy and productive year in 2021.

**Comment by DanielGoldfarb** [comment]
@ddtuan99  Thank you.  Same to you and yours ... a happy, healthy and good new year.
