### ISSUE TITLE
How to  improve the speed of saving pictures

### ISSUE THREAD

**Issue by jaried** [matplotlib/mplfinance#360]
I need to cycle hundreds of times to save pictures. At present, the speed of saving pictures is about one picture per second. Is there any way to improve the speed of saving pictures?

I heard that I can create figure reuse, and then use plt.clf () instead plt.close ("all"), how to do it? I can't find the official document

**Comment by DanielGoldfarb** [comment]
@jaried 
As a general rule, when working with mplfinance, it's best ***not*** to use `pyplot` or `plt` based functions.  These functions use global variables which can conflict with some of the stuff mplfinance is doing.  

As much as possible use the methods  provided by the Figure and Axes objects.  So, for example, instead of calling `plt.clf()` you should call [`fig.clf()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.clf) where `fig` is either a Figure that you have created, or the [Figure created by `mpf.plot()`](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects).

Unfortunately, many times the matplotlib documentation will point you to the `plt` version.  In such a case, I usually go to the documentation for the [**Figure class**](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html) or for the [**Axes class**](https://matplotlib.org/stable/api/axes_api.html) to see if there is an equivalent method.  

It is very easy to [**gain access to the mplfinance Figure and Axes objects**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects), in order to have direct access to matplotlib's various Figure and Axes methods.

---

Now regarding the speed, I have not looked into the idea of calling `.clf()` instead of `.close()`, but it makes sense if `.close()` destroys the object but `.clf()` does not.  If so, then `.clf()` would certainly be more efficient than repeatedly, allocating memory, hundreds of times, for creating and then destroying each Figure.  It definitely seems worth a try.

I would also suggest saving the Figure yourself, rather than asking mplfinance to do it.  This way you can profile how much time is spent on the actual save operation, versus mplfinance drawing the plot.  You can do this easily [**by calling `.savefig()`**](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.savefig) on the Figure object returned by or passed into mplfinance.

On that note, I would suggest that you do all this experimentation with [**mplfinance external axes mode**](https://github.com/matplotlib/mplfinance/blob/master/examples/external_axes.ipynb).  That way you will be able to re-use the Figure object.  To get the Figure for external axes mode, you can either call set `returnfig=True` the first time you call `mpf.plot()` and then use external axes mode on all subsequent calls, or you can simply call `mpf.figure()` to create your Figure object at the start.

Please let me know if this information is helpful or if you have any more questions after experimenting a bit to try to make it faster with the above suggestions.

**Comment by jaried** [comment]
I use figure=mpf.figure() to create a figure. When saving the picture, I use figure.plot() to prompt me：
AttributeError: 'Mpf_Figure' object has no attribute 'plot'
Please point out my problem

`def save_picture_init():
    global fig
    mc = mpf.make_marketcolors(
        up='red',
        down='#54ffff',
        edge='i',
        wick='i',
        volume='in',
        inherit=True)
    s = mpf.make_mpf_style(
        gridaxis='both',
        facecolor='black',
        gridstyle='-.',
        y_on_right=False,
        marketcolors=mc)
    mpl.rcParams['axes.prop_cycle'] = cycler(
        # color=['white', 'yellow',
        #        '#ff00ff'])
        color=['white', 'yellow',
               '#ff00ff', '#00ff00', '#c0c0c0', 'darkorange',
               'indigo'])
    mpl.rcParams['lines.linewidth'] = 1
    fig = mpf.figure(style=s)
    return

def Save_picture(df, path, end_date, count, symbol, d_month, futures_model, lines):
    start = time()
    df = pd.DataFrame.from_records(df, index=pd.to_datetime(df['trade_date']))
    df.rename(
        columns={
            'trade_date': 'Date', 'open': 'Open',
            'high': 'High', 'low': 'Low',
            'close': 'Close', 'oi': 'Volume'},
        inplace=True)
    kwargs = dict(
        type='candle',
        volume=True,
        title='\nStock_index_futures %s candle_line (%s),d_month: %s, enddate:%s' % (
            symbol, futures_model, d_month, end_date),
        ylabel='Candles',
        ylabel_lower='oi',
        figratio=(15, 10),
        figscale=1.5)
    add_plot = mpf.make_addplot(df[lines], secondary_y=False)
    global fig
    fig.plot(df,
             **kwargs,
             addplot=add_plot,
             # style=s,
             show_nontrading=False,
             savefig=path + '\\%03d_%s_%s_candle_line' % (count, symbol, futures_model) + '.jpg')
    #    plt.show()
    # plt.close("all")
    plt.clf()
    stop = time()
    global savepicturetime
    savepicturetime = savepicturetime + stop - start
    return
`

**Comment by jaried** [comment]
I use `fig= mpf.figure(style=s)` to create the figure, when drawing, I use `fig.plot(savefig='file.jpg')`
Tip me: 'Mpf_Figure' object has no attribute'plot'
Please point out my problem

**Comment by DanielGoldfarb** [comment]
You should be using `mpf.plot()` to draw the figure (there is no `.plot()` method as part of the Figure object in matplotlib)

Then use `fig.savefig()` to save it.

Try this:
```python
fig = mpf.figure(style=s)
ax1  = fig.add_subplot(1,1,1)
mpf.plot( ohlc_dataframe, ax=ax1 )
fig.savefig('file.jpg')
```

**Comment by jaried** [comment]
I followed your method. Without the kwargs of ax, it takes 0.5 seconds to save each picture.

**Comment by DanielGoldfarb** [comment]
> At present, the speed of saving pictures is about one picture per second. 

> I followed your method. Without the kwargs of ax, it takes 0.5 second to save each picture.

It sounds like it is now twice as fast, correct?

**Comment by DanielGoldfarb** [comment]
If you really need to pick up a lot of speed, and you have multiple cores on your machine, you may also benefit from python's multiprocessing module: https://docs.python.org/3/library/multiprocessing.html

**Comment by jaried** [comment]
> If you really need to pick up a lot of speed, and you have multiple cores on your machine, you may also benefit from python's multiprocessing module: https://docs.python.org/3/library/multiprocessing.html

Yes, it's now twice as fast.
And my computer has 20 cores and 40 logic processors. Multiprocessing is a good idea, thank you!
