### ISSUE TITLE
Feature Request: Ability to plot step /staircase lines

### ISSUE THREAD

**Issue by pankaj3009** [matplotlib/mplfinance#367]
**Is your feature request related to a problem? Please describe.**
I am attempting a migration from [R]. I have charts within [R] where I use step charts to display price levels/signals over periods of time. A screenshot of current charting is attached - with step charts in both  main panel as well as panel 1. 

When I plot in mplfinance, the display in panel 1 is not intuitive. In the absence of a step chart type, mplfinance tries to create a diagonal line between two y-values and loses information provided by a step/staircase diagram. 

**Describe the solution you'd like**
Addition of type  = 'step' in make_addplot which calls matplotlib.plotpy.step() ? Or any other 'workaround' would be very helpful.
**Describe alternatives you've considered**
Matplotlib allows creation of a step chart via function matplotlib.pyplot.step(), but i am really unable to figure out a way of using this function within mplfinance. 

**Additional context**
Image from [R] showing step charts in panel0 (main panel) and panel1 are attached. My attempt with mplfinance is also attached. 
![R](https://user-images.githubusercontent.com/4762728/113187018-fdb10d80-9275-11eb-8352-fd9075ae55a1.jpg)
![mplfinance](https://user-images.githubusercontent.com/4762728/113187032-01dd2b00-9276-11eb-8f56-2ddcdb4ba002.JPG)

**Comment by DanielGoldfarb** [comment]
@pankaj3009 
This is a nice idea.  This should be relatively easy to do, using `Axes.step()` (instead of `pyplot.step()`, which calls `Axes.step()` anyway).  Perhaps first try implementing this outside of mplfinance doing something similar to this:
```python
fig, axlist = mpf.plot(df,returnfig=True,num_panels=2)
axlist[2].step(...)
mpf.show()
```
[Click here for information on `returnfig` to gain access to th Figure and Axes objects](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects#1-set-returnfigtrue-when-calling-mpfplot--this-is-the-preferred-way).

Once you get it working, I can show you where to integrate the code into `mpf.make_addplot()`.  

All the best.  --Daniel

**Comment by pankaj3009** [comment]
Thanks for the pointer Daniel. I tried the suggestion 
fig, axlist = mpf.plot(df,type = 'candle',volume = False,style = 'yahoo',returnfig=True,num_panels=2)
axlist[2].step(t.index,t['trend'],where = 'pre') # t is a dataframe with the  steps that need to be plotted with a timestamp index.

Panel1 got the stair chart, but Panel0 is now empty. Will relook at this over the weekend -  need to understand the matplotlib internals a bit I suspect.

Thanks,

**Comment by DanielGoldfarb** [comment]
@pankaj3009 
I suspect that Panel 0 is not really empty, but that the x-axis is incompatible with what you have passed into `Axes.step()` for the x values, so the data in Panel 0 is pressed into a very small area.  

Why?  Because `mpf.plot()` defaults to `show_nontrading=False`, which cause the x-axis to actually be the row number in your dataframe, even though it is formatted as datetimes.  (That is how missing datetimes (non trading) are removed, by plotting only the existing rows).

There are two different ways you can fix this:
1. Set kwarg `show_nontrading=True`, ***or***
2. Instead of passing `t.index` as x in `.step()`, pass **`range(len(t.index))`**.

Please let me know if that helps.  Thanks. --Daniel

**Comment by pankaj3009** [comment]
That was the issue Daniel. The charts are coming through now. I have integrated changes to mplfinance (i hope correctly). The new charts with mpfinance attached. This replicates my [r] environment. Thanks very much for your help.
![mplfinance-1bar](https://user-images.githubusercontent.com/4762728/113474401-6d4d1580-948d-11eb-9658-4275c491e987.JPG)
