### ISSUE TITLE
output to buffer

### ISSUE THREAD

**Issue by rspadim** [matplotlib/mplfinance#37]
i need to save to io.buffer
something like:

```python
buf = io.BytesIO()
mpf.plot(
candles,
type='candle',
mav=(3, 6, 9),
volume=True,
show_nontrading=True,
figratio=(6, 6),
title="Graph",
style='yahoo',
savefig=buf
)
buf.seek(0)
```

**Comment by DanielGoldfarb** [comment]
This may be possible now.  Presently I don't have time to look into it; maybe in a few weeks.
In the meantime, you may try passing in the value of the `savefig=` kwarg as a `dict` ([see documentation here](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb), where cell # 7 shows passing in a dict).  I think that might work.  If that doesn't work, try modifying the [savefig kwarg validator here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L113) to allow the correct type for an io buffer through.  If that works you can submit a pull request for the change.  Otherwise, as I mentioned, I may be able to look into this in a few weeks.  All the best.  Thanks for your suggestion.  I think its a great idea.

**Comment by coffincw** [comment]
Added with https://github.com/matplotlib/mplfinance/pull/41

**Comment by DanielGoldfarb** [comment]
This is now released to Pypi.  Thank you Caleb Coffin @coffincw for implementing this enhancement, and for including examples in the [savefig examples notebook](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb)
