### ISSUE TITLE
How can I update chart after specific interval

### ISSUE THREAD

**Issue by tkanhe** [matplotlib/mplfinance#383]
How can I update chart after 1 minute? It can be after closing original chart and replotting based on new data. or live update the original chart.

Here is my code:
(I'm reading csv inside of loop because its getting updated every minute.)
```python
while True:
  df = pd.read_csv(r'data.csv', index_col=0, parse_dates=True)
  df1 = df.resample('1Min').ohlc()
    df1.columns = df1.columns.droplevel(0)
    mpf.plot(df1, type='candle', style='charles')
    sleep(60)
```

With matplotlib I drew live chart which updates after 1 minute as following:

```python
fig = plt.figure()
fig.show()
while True:
    x = [x for x in df1['Time']]
    y = [x for x in df1['Diff']]
    plt.plot(x, y)
    fig.canvas.draw()
    sleep(60)
```

**Comment by DanielGoldfarb** [comment]
@tkanhe 
So that I can understand the full context of this question, can you tell me if you have already read through [**this information about animation support in mplfinance**](https://github.com/matplotlib/mplfinance/blob/master/markdown/animation.md#animation-support-in-mplfinance) ***including*** all of the links there, *and* worked through the examples listed there??

If not, please do that first, and see if that information answers your question.  After that, if you still have questions about this, please post here and I will try to help.  Thanks.  All the best.  --Daniel

**Comment by tkanhe** [comment]
Yes, I have worked through the examples; what given animation support does is that it animates already available data, but when I update the data by adding a row at the end after each minute, it updates the chart only after I close the first chart (as it is running through the loop).

Here is the code:
while True:
    df = pd.read_csv(r'data.csv', index_col=0, parse_dates=True)
    df = df.resample('1Min').ohlc()
    df.columns = df.columns.droplevel(0)

    fig = mpf.figure(style='charles',figsize=(7,8))
    ax1 = fig.add_subplot(1,1,1)

    def animate(ival):
        data = df.iloc[0:(20+ival)]
        ax1.clear()
        mpf.plot(data,ax=ax1,type='candle')

    ani = animation.FuncAnimation(fig, animate, interval=5000)
    mpf.show()
    sleep(60)

**Comment by DanielGoldfarb** [comment]
@tkanhe 
If I understand your situation correctly, since some other processes is updating your csv file, and therefore you have to re-read the csv file to get the new data, then it seems to me that ***the re-reading of the csv file should be*** **inside** ***your `animate()` function***.  

I also think there is no need for the `sleep(60)`, rather, when calling `FuncAnimation()` you can set `interval=60000`.

Alternatively the periodic reading of the csv file, and the animation, could be two separate processes (or threads) with the dataframe being a shared global between them, so when the dataframe is updated by the read_csv() process (or thread), then the animation process (or thread) would see this update automatically (since the dataframe is shared between them).  

That said, I believe my original suggestion is much simpler: implement an initial `read_csv()` *outside* of `def animate()`, and *all subsequent* `read_csv()` calls *inside* of `animate()`.

Let me know if that helps.   Thanks.  --Daniel

**Comment by tkanhe** [comment]
Wow, thank you, Sir. Yes, the first method worked. Have a nice day. You are an inspiration!!!

Here is the code:

fig = mpf.figure(style='charles')
ax1 = fig.add_subplot(1, 1, 1)
while True:
    def animate():
        df = pd.read_csv(r'data.csv', index_col=0, parse_dates=True)
        df1 = df.resample('1Min').ohlc()
        df1.columns = df1.columns.droplevel(0)
        data = df1.iloc[-20:]
        ax1.clear()
        mpf.plot(data, ax=ax1, type='candle')

    ani = animation.FuncAnimation(fig, animate, interval=10000)
    mpf.show()

Thank You.
