### ISSUE TITLE
Problem with Bollinger Bands

### ISSUE THREAD

**Issue by Stealthm8** [matplotlib/mplfinance#388]
Hi, I'm having a problem with the upper Bollinger band being misaligned, and I suspect that it is because the upper band is being treated as a lower band when I graph it. When I print the dataframe, the values seem correct, but the graph is definitely incorrect.

Here are both bands together:
![output](https://user-images.githubusercontent.com/46169780/116847144-f2743900-abb7-11eb-8e62-4e8b34f13015.png)
Here is the Lower Band (which seems correct):
![output1](https://user-images.githubusercontent.com/46169780/116847231-1e8fba00-abb8-11eb-8f9d-cafe1f7d8497.png)
Here is the Upper Band (which seems incorrect):
![output2](https://user-images.githubusercontent.com/46169780/116847258-3404e400-abb8-11eb-99c8-39f623726bd0.png)
Here is the line of code that creates the graph:
```python
mpf.plot(df2, type='candle', style='charles', hlines=dict(hlines=[0],linestyle='-.'), axisoff=True,
         addplot=mpf.make_addplot(df2[['UpperB', 'LowerB']]), savefig=newpath)
```
I'm not sure if this is a bug, or if I am just doing something wrong, but any help would be greatly appreciated.

**Comment by DanielGoldfarb** [comment]
Since you have `axisoff=True` it is difficult to tell if the following *is* the problem, but here is my guess:  

mplfinance tries to *guess* whether or not any addplot data should be on the same y-axis as the original dataframe passed into `mpf.plot()`, or whether (based on the min and max values in the addplot data) it should be plotted on a secondary y-axis.  Sometimes it guesses wrong.  To correct for this you can set kwarg `secondary_y=True` or `secondary_y=False` in the call to `make_addplot()`.

I suggest that you first try **`secondary_y=False` in your call to `make_addplot()`**.  

That should work, but if it doesn't, then try plotting the upper and lower bands in *two* separate `make_addplot()` calls, *and* also still set `secondary_y=False` in both `make_addplot()` calls.

**Comment by Stealthm8** [comment]
Adding secondary_y=False worked, thank you.
