### ISSUE TITLE
x and y must have same first dimension, but have shapes

### ISSUE THREAD

**Issue by turbo1618** [matplotlib/mplfinance#396]
I just started using mplfinance and the charts are working great! However, when I addplot, I get the following error message: x and y must have same first dimension, but have shapes  (482,) and (12682,).

I have one ticker in a csv file with data going back to 1971. I have another ticker in another csv file with data going back to 1990.

I merged 'Adj Close' and '% Change from ticker2 into the dataframe of ticker1.
`df2 = pd.merge(df,
               df1[['Adj Close', '% Change']],
               on='Date',
               how='left')
df2`

Here is the addplot I would like to chart along with a line chart for ticker1.
`df2['Ratio'] = df2['Adj Close_x'] / df2['Adj Close_y']`

`apd = mpf.make_addplot(df2['Ratio'])`

`mpf.plot(df2[12200:12682],type='line', style='yahoo', figsize=(15,11), addplot=apd)`

The line chart for ticker1 plots great, but it is not plotting the 'Ratio' for the addplot.
My dataframe looks to have Nan values for all the missing.

`df2.shape`
`(12682, 13)`

`df2.isna().sum()`
`Open              0`
`High              0`
`Low               0`
`Close             0`
`Adj Close_x       0`
`Volume            0`
`% Change_x        1`
`Adj Close_y    4776`
`% Change_y     4777`
`Ratio          4776`
`dtype: int64`

**Comment by DanielGoldfarb** [comment]
It's difficult to tell what is going on based on the small amount of information you have provided.  Particularly I would like to see what `df2` looks like.  (head(),tail(), describe(), etc., or better yet save and attach the csv file).

That said, I can take a guess which may or may not be on track:

Since you have
`mpf.plot(df2[12200:12682],type='line', style='yahoo', figsize=(15,11), addplot=apd)`

The I would recommend that you change this line:
`apd = mpf.make_addplot(df2['Ratio'])`
**To this:**
**`apd = mpf.make_addplot(df2['Ratio'][12200:12682])`**

See if that helps.

This is pretty simple.  The length of the DataFrame passed into `mpf.plot()` and the length of any data passed into any calls to  `mpf.make_addplot()` must be the same length.  It is OK if some of the rows in either data set contain `float('nan')` values, but the overall length *must* be the same.

**Comment by turbo1618** [comment]
Yes, thank you very much, that was the problem. Changing the dates for `mpf.plot` **AND** `apd` did the trick.

`apd = mpf.make_addplot(df2['Ratio']['01-01-2020':'05-17-2021'], color='g',panel=1,type='scatter', markersize=10,marker='^')

mpf.plot(df2.loc['01-01-2020':'05-17-2021'],type='line', style='yahoo', figsize=(15,11), addplot=apd, panel_ratios=(1,1)) `
