### ISSUE TITLE
Bug Report: problems with drawing an additional plot

### ISSUE THREAD

**Issue by beginner000001** [matplotlib/mplfinance#414]
**Describe the bug**
the green line in the chart is drawn incorrect.
![ZYXI](https://user-images.githubusercontent.com/86872242/125137334-c2439c00-e10c-11eb-8b0b-b39620fcb3ac.png)

the green line is an additional plot

```
        apdict = mpf.make_addplot(df_history['HistEK'], color='g', width=2)


        mpf.plot(df_history, show_nontrading=True, figratio=(10,7), figscale=1, datetime_format='%d.%m.%y', #figscale=1 oder 2, für PDF=0.5
                 xrotation=90, tight_layout=False, # xlim=(xmin,xmax),
                 alines=dict(alines=seq_of_points, colors=seq_of_colors, linestyle='-', linewidths=1),
                 type='candle', savefig=bildpfad, addplot=apdict, style=s, # title=index,
                 update_width_config=dict(candle_linewidth=0.5))
```

the data of df_history: [df_history.txt](https://github.com/matplotlib/mplfinance/files/6794011/df_history.txt)

please let me know, If I do something wrong or if there is a workaroud.

Thanks a lot.

**Expected behavior**
the chart should be drawn correctly, the min of the green line should be 1.73 and the maximum 13.92

**Desktop (please complete the following information):**
 - OS: windows 10 pro

**Comment by DanielGoldfarb** [comment]
Thanks for posting the data and code so that I can reproduce.   Before I try to reproduce, I'm going to take a guess at what is going on here.  Notice that you have a separate Y axis on the right side, which appears to have the green line's max and min that you mentioned.

About half way through the [addplot tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) you will see a section describing the "secondary_y" kwarg to `mpf.make_addplot()`.  This kwarg has three possible values: True, False, and 'auto', where 'auto' is the default value.  Make_addplot "automatically" tries to determine whether your addplot should be on the same, or a secondary, y-axis as your prices.  In this case (I am guessing) it got it wrong (or at least it decided _not_ according to what you wanted to see.

Try adding `secondary_y=False` to your call to `mpf.make_addplot()`.
Please let me know if that works.

Thanks.  All the best.  --Daniel

**Comment by beginner000001** [comment]
I must have been blind, I never noticed the second Y-Axis. Only just now, because you pointed it out. All my other charts had none, thats probably why. Well, everything works fine, it was just me doing it wrong. Sorry. Thank you once again Mr. Goldfarb. I appreciate it very much, always to get a help from you either on stackoverflow or on here. Thanks again.
[Christian](https://www.spelzer.de/en)
