### ISSUE TITLE
make drawing trend lines simpler

### ISSUE THREAD

**Issue by dattran2346** [matplotlib/mplfinance#42]
Is there anyway that I can get the matplotlib axes/figure object and add my custom plotting on top. 

I currently want to draw trendlines like this

```
ac = ([dateA, dateC], [priceA, priceC])
l = mlines.Line2D(*ac)
ax.add_line(l)
```

The result look like
<img width="1082" alt="Screen Shot 2020-03-03 at 23 47 12" src="https://user-images.githubusercontent.com/17774491/75798559-53806100-5da9-11ea-8471-5f95c11a6c78.png">

**Comment by DanielGoldfarb** [comment]
You should be able to do this using the `addplot=` keyword to `mpf.plot()`.  
[Please click here for documentation/examples](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).   

The tend line data will need to be in a list, or pandas series or dataframe, that has the same length and datetime index as your original OHLC data.   If there are dates over which you do not want the lines to extend (as in the picture you have provided) you can simply use NaN values at the dates over which you do not want to see the trend lines.

Let me know if that works for you.

**Comment by DanielGoldfarb** [comment]
a couple of thoughts on this:
- For this to work as noted in my previous comment above, you will have to generate a time series of data (rather that specify only two points as you did in your example).  
  - However I see that is inconvenient, so I am thinking perhaps _just for the simple case of trend lines_, we could provide a kwarg `trend=` that accepts two dates and two prices as in your example.  It could also accept _a list_ of date/price pairs to be able to plot multiple trend lines.  
  - This is not a priority at present, since there is the `addplot()` alternative, however if you would like to contribute such an enhancement I would consider reviewing and merging the code.

- there is a possibility, as was mentioned [in this issue](https://github.com/matplotlib/mplfinance/issues/17), that there will be an enhancement to allow `mpf.plot()` to return the Figure and Axes that it creates.  In the meantime, you can do what is described above.

**Comment by DanielGoldfarb** [comment]
I did some experimenting with returning Figure and Axes.  It didn't really work to allow me to add to the plot after calling `mpf.plot()`.  And, it seemed to me, the issues that arose became only more challenging when I tried to make it work.

Anyone who wants to should feel free to experiment with returning Figure and Axes and let me know if you can get it to work without fundamentally changing the design of `mplfinance`.  Keep in mind that [the old API](https://github.com/matplotlib/mplfinance#oldapi) is still available and the approach of the old API is to give you full control and responsibility for the Figure and Axes.  So if you really want access to Figure and Axes you can also just use the old API, since it is fundamentally designed for that.

Now, regarding **trend lines**, as I noted in a comment above, it is definitely possibly to plot them using the [`make_addplot()` ](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) functionality.  However the caller must generate the data for the trend line.  This, it seems to me, is at least not particularly convenient.  **So I am going to leave this issue open as an enhancement to make drawing trend lines simpler.**  

I am considering an implementing this as a kwarg to [`make_addplot()` ](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)
- `trend=` ... a tuple or list of two dates or four dates.  If two dates, then the two dates define the trend line, going from close to close on the two sepcified dates.  If four dates are provided then the second pair of dates extend the trend line somewhat beyond the two dates that define slope of the trend line.

**Comment by dattran2346** [comment]
As you noted above, I currently use the old `candlestick_ohlc` api to and plot the channel on the return figure/axes object. 

Regarding the new trend line api as you suggested, I am thinking that it is more flexible to pass the list of points that users want to draw lines, and also more favorable to change `trend=`... to `lines=`...,  since user may want to connect multiple interesting points on the chart, i.e, `make_addplot(lines=[(dateA, priceA), (dateB, priceB), (dateC, priceC), ...])`.

For example, I currently want to plot the double bottom pattern on the chart.
![BINANCE_BATBTC_D](https://user-images.githubusercontent.com/17774491/76010756-071e5800-5f46-11ea-8842-c60bd901ff74.png)

Ps: I would like to help you implement this enhancement,. let my know your opinion.

**Comment by thegamecat** [comment]
Can't it work the same as plt so:
				mpf.scatter(trade_list_idx,trade_list_price,c='b')
					mpf.plot(pr1, c='r')
					mpf.plot(hsr1, c='b')
					mpf.plot(lsr1, c='y')

**Comment by DanielGoldfarb** [comment]
@thegamecat 

I have no idea what you are trying to say with:

> Can't it work the same as plt so:
> mpf.scatter(trade_list_idx,trade_list_price,c='b')
> mpf.plot(pr1, c='r')
> mpf.plot(hsr1, c='b')
> mpf.plot(lsr1, c='y')

[This present issue](https://github.com/matplotlib/mplfinance/issues/42) is about plotting **trend lines** (not a scatter plot of trades).

**Comment by DanielGoldfarb** [comment]
@dattran2346 
I think I have a way to make this [as simple as you proposed](https://github.com/matplotlib/mplfinance/issues/42#issuecomment-595373806).  Something like this:

    ap = mpf.make_addplot( [(dateA, priceA), (dateB, priceB), (dateC, priceC), ...] )
    mpf.plot( df, addplot=ap)

Will keep you posted.  Have a couple other things to finish up first.

**Comment by DanielGoldfarb** [comment]
just a note, so I don't forget; i am thinking of implementing this as a `LineCollection` and, internally, the same implementation could be used for issue #54

**Comment by putraxor** [comment]
> @dattran2346
> I think I have a way to make this [as simple as you proposed](https://github.com/matplotlib/mplfinance/issues/42#issuecomment-595373806). Something like this:
> 
> ```
> ap = mpf.make_addplot( [(dateA, priceA), (dateB, priceB), (dateC, priceC), ...] )
> mpf.plot( df, addplot=ap)
> ```
> 
> Will keep you posted. Have a couple other things to finish up first.

it doesn't work
```python
                lines = []
                for line_date, line_row in data.iterrows():
                    lines.append((line_date, line_row['signal']))

                pattern_line = mpf.make_addplot(lines)

                signals = mpf.make_addplot(
                    window['signal'], scatter=True, markersize=97)
                mpf.plot(window, volume=True, type='candle',
                         addplot=[signals, pattern_line], style='yahoo')
```

Raises error:
```sh
Traceback (most recent call last):
  File "peaks_valleys.py", line 156, in <module>
    addplot=[signals, pattern_line], style='yahoo')
  File "/home/putraxor/.local/lib/python3.7/site-packages/mplfinance/plotting.py", line 35, in decorator
    return func(*args, **kwargs)
  File "/home/putraxor/.local/lib/python3.7/site-packages/mplfinance/plotting.py", line 323, in plot
    raise TypeError('apdata is list but NOT of float or int')
TypeError: apdata is list but NOT of float or int
```

**Comment by DanielGoldfarb** [comment]
@putraxor - This is not implemented yet.   I am almost finished with this enhancement; *should be ready sometime next week.*   I decided to add kwargs to **`mpf.plot()`** (no need to call make_addplot()).

This is how I expect it to work:  There will be three (or four) kwargs:

- `hline=` ... specify one or a list of prices to generate a ***horizontal line*** at that price level
- `vline=` ... specify one or a list of dates/datetimes to generate a ***vertical line*** at that point in time
- `aline=` ... specify one or more ***arbitrary line*** as
  - list of two or more ***x,y values*** (multiple lines are contiguous)
    - examples:
 `[(dateA,priceA),(dateB,priceB)]`
 `[(dateA,priceA),(dateB,priceB),(dateC,priceC),(dateD,priceD),...]`
  - list of one or more ***x,y value pairs*** (multiple lines need not be contiguous)
where a ***single x,y pair*** is like `((dateA,priceA),(dateB,priceB))`
    - examples: 
`aline=((dateA,priceA),(dateB,priceB))`
`aline=[((dateA,priceA),(dateB,priceB)),((dateC,priceC),(dateD,priceD)),...]`

- `tline=` ... ***trend line*** (still deciding whether to implement this).
  - specify two (or more) dates or datetimes:  mplfinance will ***automatically draw trend lines between the dates***.  An additional kwarg `tline_value` or something like that may specify which algorithm to use for calculating the trend line between any two dates.

**Comment by chuckf201** [comment]
Daniel - I don't need anything - just wanted to thank you and the rest of the team for your (real-time) development.  Thank you.

**Comment by DanielGoldfarb** [comment]
> Daniel - I don't need anything - just wanted to thank you and the rest of the team for your (real-time) development. Thank you.

@chuckf201 
You're welcome.  Thanks for expressing your appreciation.
