### ISSUE TITLE
Missfit of tlines

### ISSUE THREAD

**Issue by TheGrowingPlant443** [matplotlib/mplfinance#425]
I may have done something wrong but this may also be a bug. 

I have data from yahoofinance of the ticker symbol AMC from (2021-07-22 09:30:00-04:00 to 2021-07-28 15:59:00-04:00). I want to use the function tlines() but I get something that is not suppose to happen. 

Code: 
```
import yfinance as yf
import pandas as pd
import mplfinance as mpf

tickername = "AMC"

Ticker = yf.Ticker(tickername)

df = Ticker.history(period='1d', interval='1m', start='2021-07-22', end='2021-07-28')

datapairs = [('2021-07-22 09:38:00-04:00', '2021-07-22 09:58:00-04:00'), 
             ('2021-07-22 09:58:00-04:00', '2021-07-22 10:02:00-04:00'),
             ('2021-07-22 10:02:00-04:00', '2021-07-22 10:15:00-04:00'),
             ('2021-07-22 10:15:00-04:00', '2021-07-22 10:24:00-04:00'),
             ('2021-07-22 10:24:00-04:00', '2021-07-22 10:33:00-04:00'),
             ('2021-07-22 10:33:00-04:00', '2021-07-22 10:36:00-04:00'),
             ('2021-07-22 10:36:00-04:00', '2021-07-22 11:22:00-04:00')]

mpf.plot(df, tlines=[dict(tlines=datapairs,tline_use='high',colors='g')])
```
My problem is that the fit is wrong how do I fix this?

![2021-07-22 09 30 00-2021-07-22 11 12 00](https://user-images.githubusercontent.com/57142309/127483903-f217cec3-e6b6-4dcc-96eb-fda95d4c52de.png)

**Comment by DanielGoldfarb** [comment]
@TheGrowingPlant443 

Can you please, after `df = Ticker.history(period='1d', interval='1m', start='2021-07-22', end='2021-07-28')`, call
```python
df.to_csv('AMC_20210722_20210728.csv')
```

... and then post the csv file here, or put it somewhere that I can get to it (or email to dgoldfarb.github@gmail.com) so that I can be sure I am working with the exact same data you are working with.  I will take a look.  Thank you.  --Daniel

**Comment by TheGrowingPlant443** [comment]
[AMC_20210722_20210728.zip](https://github.com/matplotlib/mplfinance/files/6900328/AMC_20210722_20210728.zip)

@DanielGoldfarb 

Thanks for the quick response. I have linked to a zip-folder with the csv file in it.

**Comment by DanielGoldfarb** [comment]
This is indeed a bug tha was [reported previously here](https://github.com/matplotlib/mplfinance/issues/314).

The explaination is as follows:  Whenever plotting a time series with matplotlib, the datetimes must be converted to low-level matplotlib dates.  Mplfinance does this for you.  Normally this works fine, but when your dataframe's datetime index contains a timezone offset. matplotlib's date conversion always converts the time zone to UTC.  (I'm not sure why matplotlib does that).

In order to avoid this automatic conversion to UTC, mplfinance detects if a timezone offset is present in the dataframe index, and if so, then it "localizes" the pandas Timestamp objects.  This generally works fine.

The **bug** is this: when I added code to localize the pandas Timestamps, (See issue https://github.com/matplotlib/mplfinance/issues/236), I forgot to add code to also localize any datetimes passed in as `tlines` and/or `alines` specifiers.  Effectively then, your trend lines are being drawn using price data that is offset by the datetime offset (in your case, 4 hours).

This will definitely be fixed eventually.  In the meantime there are a couple of workarounds that you can try:

1. The simplest workaround is to set kwarg `tz_localize=False` when calling `mpf.plot()`.  This will allow your `tlines` date specifiers (like `'2021-07-22 09:38:00-04:00'`) to match the offset in your data.  Your trend lines will be correct, but your trading day will appear to start at 13:30 looking something like this:

![image](https://user-images.githubusercontent.com/11164790/127577876-d4b67c73-6a3e-4fa2-aac4-eedd7cafef53.png)

2. Alternatively you can write some code to remove the time zone offset from your dataframe index, and then specify your `tlines` datetimes using ***no*** timezone offset:

    ```python

    df = Ticker.history(period='1d', interval='1m', start='2021-07-22', end='2021-07-28')

    # Remove offsets from timestamps in the dataframe index:
    df.index = pd.DatetimeIndex(df.index.tz_localize(None).to_pydatetime())
    
    # Now continue as before, but with no timezone offsets in the `tlines` specification:
    datapairs = [('2021-07-22 09:38:00', '2021-07-22 09:58:00'),
                 ('2021-07-22 09:58:00', '2021-07-22 10:02:00'),
                 ('2021-07-22 10:02:00', '2021-07-22 10:15:00'),
                 ('2021-07-22 10:15:00', '2021-07-22 10:24:00'),
                 ('2021-07-22 10:24:00', '2021-07-22 10:33:00'),
                 ('2021-07-22 10:33:00', '2021-07-22 10:36:00'),
                 ('2021-07-22 10:36:00', '2021-07-22 11:22:00')
                ]

    mpf.plot(df, tlines=[dict(tlines=datapairs,tline_use='high',colors='g')])
    ```

The result is:
![image](https://user-images.githubusercontent.com/11164790/127578505-56a42929-8dae-4366-ae9d-b52401e47ddb.png)

**Comment by TheGrowingPlant443** [comment]
Thank you so much for the help. This works perfektly 👍
