### ISSUE TITLE
How to draw candlesticks on canvas

### ISSUE THREAD

**Issue by hanfon2020** [matplotlib/mplfinance#440]
How to draw the mplfinance cnadlesticks drawing to the canvas instead of generating the blank canvas k-line drawing as shown in the figure, but drawing it in the plot output bar of python,how to correct it?

```python
import time
import pandas as pd
import matplotlib
import mplfinance as mpf
import matplotlib.pyplot as plt
import sqlite3
import datetime
import abstract
import numpy as np
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from tkinter import *
import tkinter as tk
win=tk.Tk()
win.geometry("950x850")
#figure=plt.figure()
#ax=figure.add_subplot(111)
strtemp=""
str1=""
str3=""
str2=""
i=0
iday = []
conn = sqlite3.connect('indexfuturecom.sqlite') # 建立資料庫連線
strtemp= "select * from table1"
df = pd.read_sql(strtemp,conn,parse_dates=True)
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)
iday=df.loc['2001-01-02  08:46:00':'2021-07-31  13:45:00',:]


def Plot_data():
    fig = mpf.figure(figsize=(1,1), dpi=100)
    chart=fig.add_subplot(111)
    canvas=tk.Canvas(win,background='white',width=900,height=800)
    chart_canvas = FigureCanvasTkAgg(fig, master=win)
    chart_canvas.get_tk_widget().place(relx = .05, rely=.25)
    kwargs=dict(title='Candle plot',figratio=(15,10),figscale=5)
    mc=mpf.make_marketcolors(up='red',down='green',edge='i',wick='i',volume='in',inherit=True)
    s=mpf.make_mpf_style(gridaxis='both',gridstyle='-.',y_on_right=False,marketcolors=mc)   
    mpf.plot(iday,type='candle',style=s, volume=True,addplot=[])

Plot_data()
win.mainloop()
```

![ouptpu](https://user-images.githubusercontent.com/87791255/131778890-3c99cf72-d919-413a-ba77-54e1cbfafec2.jpg)

**Comment by hanfon2020** [comment]
I used the trial and error method myself and found that plog_data function was changed to the following

def Plot_data():
    fig = mpf.figure(figsize=(1,1), dpi=100)
    chart=fig.add_subplot(111)
    chart_canvas=tk.Canvas(win,background='white',width=900,height=800)

    kwargs=dict(title='Candle plot',figratio=(15,10),figscale=5)
    mc=mpf.make_marketcolors(up='red',down='green',edge='i',wick='i',volume='in',inherit=True)
    s=mpf.make_mpf_style(gridaxis='both',gridstyle='-.',y_on_right=False,marketcolors=mc)   
    fig,ax=mpf.plot(iday,type='candle',tight_layout=True,style=s, volume=True,returnfig = True)
    chart_canvas = FigureCanvasTkAgg(fig,master=win)
    chart_canvas.draw()
    chart_canvas.get_tk_widget().place(relx = .05, rely=.25)

Then the required output form appears:
![Uploading carvas.jpg…]()

**Comment by DanielGoldfarb** [comment]
There are two ways to do this.  The [second approach you have above](https://github.com/matplotlib/mplfinance/issues/440#issuecomment-911630679) is generally better because it does not limit mplfinance functionality (as does the first approach).  This second approach is to set `returnfig=True`, and then use the Figure returned to create the canvas, as you have done `chart_canvas = FigureCanvasTkAgg(fig,master=win)`

[The first approach](https://github.com/matplotlib/mplfinance/issues/440#issue-986074004) where you create the Figure first, ***can work*** but limits some mplfinance functionality.  It also requires that you pass in the Axes object to `mpf.plot()`:  After `chart=fig.add_subplot(111)` then `mpf.plot(iday,type='candle',style=s, volume=True,addplot=[])` should be:
```python
mpf.plot(iday,type='candle',style=s, volume=True,ax=chart)
```

Again, just to emphasize, the [second approach (`returnfig=True`)](https://github.com/matplotlib/mplfinance/issues/440#issuecomment-911630679) is generally easier to use, and allows mplfinance to do more of the work for you.

**Comment by DanielGoldfarb** [comment]
Let me know if you have any further questions.
