### ISSUE TITLE
How to redraw canvas on event

### ISSUE THREAD

**Issue by SerialIterator** [matplotlib/mplfinance#442]
```
import pylab as plt
import numpy as np

X = np.linspace(0,2,1000)
Y = X**2 + np.random.random(X.shape)

plt.ion()
graph = plt.plot(X,Y)[0]

while True:
    Y = X**2 + np.random.random(X.shape)
    graph.set_ydata(Y)
    plt.draw()
    plt.pause(0.03)
```

This is a simple example from [ion() example](https://www.geeksforgeeks.org/how-to-update-a-plot-in-matplotlib/) that updates the plot at unbelievable fps (which is mainly unnecessary but what I am trying to accomplish). I can't seem to adapt this to mpf. Can the mpf canvas be redrawn similar to this and if so how can this be adapted to mpf candles?

**Comment by DanielGoldfarb** [comment]
This would take me some time looking into, and I don't expect to have that much time in the next couple of weeks.  However perhaps I can point you in a direction to try to figure this out:

First, take a look at [**Acessing mplfinance Figure and Axes objects**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) and the links therein.  I recommend first making a good effort to get the `returnfig=True` method to work, since this will maximize the mplfinance functionality for you.

Then take note of the source code for [**plt.draw()**](https://matplotlib.org/stable/_modules/matplotlib/pyplot.html#draw) ... it simply calls `.canvas.draw_idle()` on the current figure, which suggests that something along the following lines may work:
```python
    fig, axlist = mpf.plot(df,...,returnfig=True)
    ...
    while True:
        ...
        fig.canvas.draw_idle()
```

There may be a problem with the above that could possibly be challenging to overcome (and may require modifications to the mplfinance code).   It appears to me that `graph` is a [`Line2D`](https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) Artist object.  

mplfinance does not return Artist objects, and even if it did, candlesticks are not Line2D objects, but are rather a collection of Line2D objects together with a collection of polygon objects.  There is some mention of this within the [animation documentation](https://github.com/matplotlib/mplfinance/blob/master/markdown/animation.md) particularly if you look at the comments at the top of each of the examples, for example [here](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo1.py) where it says "Note that presently mplfinance does not support "blitting" (blitting makes animation more efficient)."  

As I understand it, this is because this type of plot update requires access to the Artist objects.  In theory it should be easy enough to modify mplfinance to return the Artist objects (given a kwarg that request it) however as mentioned above candlesticks are not simple Line2D Artists, so one would have to figure out, based on the example you provided, the analogous update to the mplfinance Artist objects.  Certainly it seems to me it can be done.  

I hope one day to have the time to research and do this, but for now that's either on the back burner, or perhaps someone like yourself will be willing to delve into it.  If anyone is interested, and if I am correct that this requires access to the mplfinance Artist objects, note that `_construct_candlestick_collections()` [returns the Artist objects here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L91-L92) after [constructing them here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L597-L610).  

Good luck, and all the best!

**Comment by SerialIterator** [comment]
Thanks for the direction! I'll fiddle with it and I'll let you know what I find

**Comment by SerialIterator** [comment]
I messed around with it for a while but regular animations are fast enough. Thank you for your help
