### ISSUE TITLE
I need pixel olhcv charts

### ISSUE THREAD

**Issue by mablue** [matplotlib/mplfinance#447]
Hi. I need to reduce size of plot to something like that:![Untitled](https://user-images.githubusercontent.com/5004900/134331300-6f95b34c-5a2b-48c3-9430-3b5ef032ec16.png)
No need to axise no need to other texts and lines just pure plot in pixel sizes
Smallest version of a pic with green and red colors for open and close and dark green and red for high and low. How can I do that? Also I need to drow other thigs on it like ma and etc...i think yes we can change fig size but it have some limitation and when I drow multi moving averages them have very big sizes that can cover the olhcv...how can I set all sizes to one pixel?or 2 or 3...
Lets zoom on my small photo:
![IMG_20210922_142751](https://user-images.githubusercontent.com/5004900/134331812-49627717-195a-4690-b2fb-62e4d5ecd0e5.jpg)

Other example
![Untitled](https://user-images.githubusercontent.com/5004900/134333097-663a62b4-08cf-442a-a493-0d4189641f55.png)
![Untitled_997_1596](https://user-images.githubusercontent.com/5004900/134333102-f8f0cf1b-121d-4665-a552-6385c04f232d.png)

**Comment by DanielGoldfarb** [comment]
@mablue 
Masoud,
I can make some suggested to get a smaller plot, but first let me say the following:  It appears that you have already decided that a reduced plot size is the solution to the problem you are trying to solve, or to what you are trying to accomplish.  This may be, but also it may not be.  If you can give a bigger picture here, others may have a better solution for you.  Please describe the overall big picture of what you are trying to accomplish, or what problem you are trying to solve, *and why you think having a very small plot is the best or appropriate solution.*

In the meantime, if I was trying to do this, I would probably do the following:  Make a normal size plot, so that it can contain whatever details are needed, and then use `savefig` to save as a `.jpg` file (or `.png` or whatever you prefer).   Then reduce the size of the `.jpg` file either using photo editing software, or use a python package such as PIL to read and reduce the image size.  Here are a couple of links that explain how you can resize images using python: 
- https://auth0.com/blog/image-processing-in-python-with-pillow/
- https://opensource.com/life/15/2/resize-images-python
- https://www.holisticseo.digital/python-seo/resize-image/

Good luck.  And remember, as suggested, it may be more helpful for you to describe the overall big picture of what you are trying to accomplish, *and why you think having a very small plot is the best or appropriate solution.*

**Comment by mablue** [comment]
Thanks for your help. Tbh yes i decided decrease the size under 1 can work. I tried and yes it works. But speed and quality is the main problem when we thinking to make small things..and my problem is that speed of chart generation is very important and quality of candles high and low and mavs are important to me and when i resize something I cant get it...there is not important accurancy of data or exact  numbers to me...i dont need accurate numbers i need waves

**Comment by DanielGoldfarb** [comment]
I read again your original post
>smallest version of a pic with green and red colors for open and close and dark green and red for high and low. How can I do that?

If I understand what you are asking for, these are not candlesticks but just vertical bars of (single pixels) boxes.  you may want to try using [**matplotlib**](https://matplotlib.org/) directly for something like this.  Perhaps using [**`Axes.scatter()`**](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html) or [**`Axes.bar()`**](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html).  We have no plans to support this type of a plot in mplfinance.
