### ISSUE TITLE
Scatter plots on all panels?

### ISSUE THREAD

**Issue by mcnwilliams** [matplotlib/mplfinance#459]
> Is it possible to use scatter plots on any panel or is it restricted to panels 0 and 1?

**Comment by DanielGoldfarb** [comment]
Method `mpf.make_addplot()` will allow you to put a scatter plot on any panel.

I strongly suggest you first review both the [**addplot**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) tutorial and the [**panels**](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb) tutorial.  Will take you 5 to 10 minutes each.  Then let me know if you have any questions *after* reviewing those two tutorials.  Thanks.  All the best.  --Daniel

**Comment by mcnwilliams** [comment]
Hi Daniel,

Thank you for your response. I had come across a remark somewhere while on the web, (I forget where) that said it could not be done, hence I nervously added the question for re-assurance.

You have said a few times you are interested in what people are using MPLFinance for. As such I will describe non-exhaustively what I am up to. I am in the early stage of developing a trading platform that will do some of the usual things you see on the market and add some new ideas of my own. I aim to go a level beyond the usual technical indicators (although they will be supported for use by themselves) and create a new layer of intelligence above them, that allows trading strategies to be developed. I will also develop and/or implement other intelligent strategies that represent current trading methods and analysis used by serious traders. Eventually this will permit the user to assign a strategy to automatically trade a stock. I will be using MPLFinance to for the visualization it provides.

I have been writing real time software (in C) for some 40 years now and I am retired so I do this in part because I like development and also because I have finally time (when the garden does not call) to engage in aspects of computing science I could never touch in my day job such as data science and Python.

On the technical environment side the application:

1) Is GUI based using PyQt5 and uses the Qt5 back end that Matplotlib provides.
2) I use ib_insync to connect to Interactive Brokers to obtain real time tick data and make trades.
3) The GUI application and ib_insync both share the same asyncio event loop.
4) MPLFinance is tasked with displaying candle stick chart updates, indicator updates, and trade updates. These updates can arrive at a fastest rate of every 5 seconds.
5) MPLFinance will also be used for data mining, strategy, and back testing visualization.

Should I use the Panel or the External Axes method?:

1) It seems with the fastest update rate of 5 seconds either method could be used but the ease of implementation needs to be better understood. 
2) I also have to consider GUI application scenarios such as technical indicator studies when the user changes the order of their displayed axes, adding new indicator axes to the display and deleting indicator axes (causing lower axes to shuffle up).

This project has so many legs I think It will keep me busy for quite a while,

I am very thankful you have provided all this capability for everyone to use. I hope what learn from this develo[pment my experience will be useful to others.

cheers,

Martin.

**Comment by DanielGoldfarb** [comment]
@mcnwilliams 
Martin,
Thank you so much for sharing.  Sounds like a very ambitious project, especially for one person, but also sounds like you have the experience and patience to pull it off.  Keep me posted.  I very much enjoy hearing these things, and as well it helps me to prioritize enhancements to mplfinance based on users needs (or at least on the needs of the most vocal and sharing users, which is a tip-of-the-iceberg sample, hopefully reflecting the overall user base).

Regarding using Panels or External Axes, either can work.  I am only somewhat familiar PyQt5, but as I understand it you will have to at any rate [gain access to mplfinance's Figure object](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) to display the plot withing PyQt5.  (If you know another way of doing so, please let me know.  

If you can do gain this Figure access with `returnfig=True` (instead of external axes mode) then mplfinance can do a lot of the matplotlib work for you.  At the very least you won't have to worry about lining up the Axes panels nicely, nor will you have to worry about non-trading time period gaps along the x-axis (just to mention two things).  My pholosophy is this, when you must have access to to the Figure and/or Axes objects, then always first try to do so with `returnfig=True` to be able to benefit from everything mplfinance has to offer.  Only if trying to accomplish something that isn't yet supported would I presonally use external axes mode.  (On the other hand, some users already familiar with matplotlib, prefer external axes mode because they are used to working that way.  You can think of mplfinance as a layer of abstraction on top of matplotlib, and you can choose to work exclusively, or almost exclusively, at that level, if you want to).

Thanks again for sharing.  If at some point you are willing to share a screen grab of a cool plot that will also be much appreciated.  All the best.   --Daniel

**Comment by mcnwilliams** [comment]
Issue closed. Thank you.
