### ISSUE TITLE
mpf.plot(daily) crashes spyder kernel

### ISSUE THREAD

**Issue by chuckf201** [matplotlib/mplfinance#461]
```python
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  1 10:22:52 2021

@author: monro
"""

# -*- coding: utf-8 -*-
"""
Created on Mon Nov  1 10:19:44 2021

@author: monro
"""
import pandas as pd
import mplfinance as mpf
import pandas_datareader as webreader

import yfinance

import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
print('mplfinance: ', mpf.__version__)
print('pandas version: ', pd.__version__)
print('pandas_datareader: ', webreader.__version__)
print('yfinance: ', yfinance.__version__)
mpf.available_styles()
#%%
daily = pd.read_csv('data/SP500_NOV2019_Hist.csv',index_col=0,parse_dates=True)
print('daily.descr',daily.describe())
print('daily.info',daily.info(max))
daily.index.name = 'Date'
daily.shape
daily.head(3)
daily.tail(3)
#%%
import mplfinance as mpf
mpf.plot(daily)
```
---

output:

```bash
all cells compete except last cell: mpf.plot(daily)
monro/.spyder-py3/pythonProject1')
matplotlib: 3.4.3
mplfinance:  0.12.7a17
pandas version:  1.3.4
pandas_datareader:  0.10.0
yfinance:  0.1.64
python:3.8.12
```
last several lines:
```bash
#   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    20 non-null     float64
 1   High    20 non-null     float64
 2   Low     20 non-null     float64
 3   Close   20 non-null     float64
 4   Volume  20 non-null     int64  
dtypes: float64(4), int64(1)
memory usage: 960.0 bytes
daily.info None

Restarting kernel...
```
 
But there is no error message except "restarting kernel".
I don't know how to proceed from here. 
Can you help?

**Comment by DanielGoldfarb** [comment]
I've edited your question to try to make it clear where the code ends and the output begins.  Please correct it if I've gotten anything wrong.

I am not very familiar with spyder, but I know it handles some things in unusual ways.  

Have you tried running this script outside of spyder on the same machine?   Please let me know if it works.

We have seen some [bugs with spyder before](https://github.com/matplotlib/mplfinance/issues/183).   I was able to reproduce that one and eventually tracked it down to how pylab mode handled something differently.

Unfortunatley I am unable to reproduce this in spyder on my machine.  It runs fine for me.

Perhaps also see if you can run a simple matplotlib plot:
```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax  = fig.add_axes([0.1,0.1,0.85,0.85])

x = (0.,1.,2.,3.)
y = (2.,6.,3.,5.)

ax.plot(x,y)

plt.show()
```

Let me know how the the simple matplotlib plot above works.  

If it works fine, then you may want to take the mplfinance code and modify `plotting.py` function `def plot(...):` and put print statements throught to see how far it gets before the kernal restarts.  see if you can isolate what line of code is doing it.  make sure you have the modified version of plotting.py installed from where you are importing mplfinance.  perhaps make a virtual environment if you need to.

**Comment by chuckf201** [comment]
tried code in python shell and it also failed. [<matplotlib.lines.Line2D object at 0x000002BCD1685610>]
Tried `pip install --upgrade matplotlib` which gave me an error message: " Error parsing requirements for python-lsp-black: [Errno 2] No such file or directory: 'c:\\users\\monro\\anaconda3\\lib\\site-packages\\python_lsp_black-1.0.0.dist-info\\METADATA'"
I suspect the libraries have been compromise using pip and conda to update packages. My troubleshooting continues.

**Comment by DanielGoldfarb** [comment]
It definitely sounds like something is awry in your environment/setup.   I have found issues myself when trying to mix conda and plain ordinary pip/python.   I generally avoid conda except when I need to test something specifically with regard to use in a conda environment.  

If you really want to use conda, perhaps try creating a ***new*** clean conda environment.  Then try
```bash
conda install -c conda-forge mplfinance
```
This should also install matplotlib and pandas automatically since mplfinance depends on them.
If not, you can run 
```bash
conda install -c conda-forge matplotlib
conda install -c conda-forge pandas
```

I suggest that for now, until you get it working, you avoid importing matplotlib, pandas-dataread, yfinance, etc.  Try to get it working with the simplest code (since you are already reading the sample data file from mplfinance) ... you only need import pandas and mplfinance.

---

Alternatively, if you have plain python3 installed you can try running `pip install` and `python` from command prompt and and things should work there.  Only you must be careful that you are not actually running in a conda environment for this to work.  I have found that with a normal anaconda/conda install, it typically automatically sets things up so that a 'base' conda environment is automatically running every time you log in.  On my own machine I had to disable that so that I can run a conda environment only when I choose to.  hth.

**Comment by chuckf201** [comment]
EXCELLENT: It worked. I will stay away from conda-installs. It caused too many conflicts. I removed conda and reinstalled as well. pip will be the way to go.
Thanks for your help.

**Comment by DanielGoldfarb** [comment]
wondering if perhaps this is related: 
https://stackoverflow.com/questions/69786885/after-conda-update-python-kernel-crashes-when-matplotlib-is-used
