### ISSUE TITLE
Feature Request: Add 1 to 2 indicator windows

### ISSUE THREAD

**Issue by sunjar2020** [matplotlib/mplfinance#464]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

Although we can manually add a second plot to draw data on the canvas, it is more complex, and there are multiple X-axis alignment and scaling problems. It would be great if mplfinance can add 1 or 2 indicator windows, just like drawing volume, read data from a certain column in dataframe, and then display it as a line chart or a histogram, which is very beneficial to users Research and analyze your own indicators. Will you consider this feature in the future?

**Describe alternatives you've considered**

**Additional context**

**Comment by DanielGoldfarb** [comment]
Have you read and _worked completely_ through these two tutorials?  
- [**Panels Tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)
- [**Addplot Tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)

How is what you're asking for any different from what can be accomplished through the combined techniques of these two tutorials?

What you have described sounds like it can be done easily with mplfinance.

**Comment by sunjar2020** [comment]
> Have you read and _worked completely_ through these two tutorials?
> 
> * [**Panels Tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)
> * [**Addplot Tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)
> 
> How is what you're asking for any different from what can be accomplished through the combined techniques of these two tutorials?
> 
> What you have described sounds like it can be done easily with mplfinance.

Hi, Daniel:

Sorry I am not very familiar with github. I did not find those two web pages. The information you provided is very useful. I will take a moment to study them first. thank you!

**Comment by DanielGoldfarb** [comment]
> Sorry I am not very familiar with github. I did not find those two web pages.

No worries.  If you scroll down on the github page for *any* repository (for example [**mplfinance**](https://github.com/matplotlib/mplfinance)) you will usually see a README document.  If you want to learn about a repository, then it's often a good idea to read the entire README document, since someone took the time to create it.  

In the case of  [**mplfinance**](https://github.com/matplotlib/mplfinance) you will also see (there in the README document) a [**Contents and Tutorials section**](https://github.com/matplotlib/mplfinance#contents-and-tutorials) with links to many other documents to teach you all about mplfinance.   All the best, and good luck.   --Daniel
