### ISSUE TITLE
Is there a description of all the parameters of the function "plot"?

### ISSUE THREAD

**Issue by starsun7** [matplotlib/mplfinance#469]
The function "plot" has 56 arguments. Where can I learn how to use these parameters?
Preferably a document that contains instructions for all parameters.
Thank you.

**Comment by DanielGoldfarb** [comment]
@starsun7 

Thanks for your interest in mplfinance.  Documentation *with examples* for the parameters (available kwargs) to `mpf.plot()` are not all in one place *but rather are organized **according to topic*** [**here in the list of examples/tutorials**](https://github.com/matplotlib/mplfinance#tutorials).  

[**Just follow the links**](https://github.com/matplotlib/mplfinance#tutorials) (and any additional links therein).

It is well worth setting aside *one full hour* to work through those examples/tutorials.  You will learn quite a lot about using mplfinance.  They are mostly jupyter notebooks, so that you can also clone or download the repository and play with the code, experiment with making various changes, etc. (highly recommended).

I would estimate that 98% of the available parameters are documented within those examples.  The remaining 2% are documented [**within the various issues**](https://github.com/matplotlib/mplfinance/issues?q=is%3Aissue+) (soon to be documented in the examples) so if you have a specific question its a good idea to first search through the issues to see if you question as already been answered.

I strongly recommend taking the above approach, however (full disclosure) within the code itself there is a [**"valid kwargs table"**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L87-L276) that lists all possible kwargs.  And there is an [enhancement in progress](https://github.com/matplotlib/mplfinance/pull/416) to provide a function call to get help on any kwarg.

All the best.   --Daniel

**Comment by DanielGoldfarb** [comment]
One more comment, but before the additional comment I'll repeat myself and strongly recommend *first* working through the [**list of examples/tutorials**](https://github.com/matplotlib/mplfinance#tutorials).  

If you find a kwarg that you want to know about and, in the unlikely event it is not apparent in the [list of examples/tutorials](https://github.com/matplotlib/mplfinance#tutorials), then you can always search the repository, for example, searching for `return_calculated_values` among the issues brings up several descriptions as to how this kwarg is used:
**https://github.com/matplotlib/mplfinance/search?q=return_calculated_values&type=issues**
