### ISSUE TITLE
How to plot mplfinance animation in pyqt5?

### ISSUE THREAD

**Issue by starsun7** [matplotlib/mplfinance#476]
I tried plot mplfinance animations in PyQt5. But I ran into some problems. The animated func is never called after FuncAnimation have been created. I really need you to help me figure out what's going on. My code is as follows.

```
import mplfinance as mpf
import pandas as pd
import matplotlib as mpl
mpl.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import *
import sys
from matplotlib.animation import FuncAnimation


class MyFigure(FigureCanvas):
    def __init__(self, width=12, height=8, dpi=100):
        mcolors = mpf.make_marketcolors(up='red',
                                        down='green',
                                        edge='in',
                                        wick='in',
                                        volume='in')
        my_style = mpf.make_mpf_style(base_mpf_style='binance',
                                      marketcolors=mcolors,
                                      facecolor='white',
                                      mavcolors=['blue', 'red', 'yellow'])

        self.fig=mpf.figure(style=my_style, figsize=(width,height), dpi=dpi)
        super(MyFigure,self).__init__(self.fig)
        self.df = pd.read_csv('./data/SPY_20110701_20120630_Bollinger.csv', index_col=0, parse_dates=True)
        self.fig.subplots_adjust(left=0, bottom=0, right=1, top=0.95, hspace=0)
        self.ax1, self.ax2 = self.fig.subplots(nrows=2, ncols=1, sharex=True)
        mpf.plot(self.df.head(50), ax=self.ax1, type='candle', volume=self.ax2, mav=[5, 10, 30], axtitle='customize plot', tight_layout=True)

class MyWin(QWidget):
    def __init__(self):
        super().__init__()
        self.myfig=MyFigure()
        self.setWindowTitle('plot candle figure')

        self.btn1 = QPushButton('start')
        self.btn1.clicked.connect(self.on_start)
        self.btn2 = QPushButton('stop')
        self.btn2.clicked.connect(self.on_stop)
        hbox = QHBoxLayout()
        hbox.addWidget(self.btn1)
        hbox.addWidget(self.btn2)

        layout=QVBoxLayout()
        layout.addWidget(self.myfig)
        layout.addLayout(hbox)
        self.setLayout(layout)

    def on_start(self):
        self.ani = FuncAnimation(self.myfig.fig, self.update_candle, frames=100, interval=100)

    def on_stop(self):
        self.ani._stop()

    def update_candle(self, steps):
        end = 50 + steps
        self.myfig.fig.clear()
        self.myfig.ax1, self.myfig.ax2 = self.myfig.fig.subplots(nrows=2, ncols=1, sharex=True)
        mpf.plot(self.myfig.df.iloc[0:end], ax=self.myfig.ax1, type='candle', volume=self.myfig.ax2,
                 mav=[5, 10, 30], axtitle='customize plot', tight_layout=True)


if __name__=='__main__':
    app=QApplication(sys.argv)
    winform=MyWin()
    winform.show()
    sys.exit(app.exec())

```

**Comment by DanielGoldfarb** [comment]
I am only superficially familiar with PyQt5, so I am afraid I can't be of much help without first doing a lot of research and experimentation on my own.   That said, I did poke around a little bit and found what looks somewhat promising to me:

Take a look at this **and please let me know if it helps: https://stackoverflow.com/questions/36665850/matplotlib-animation-inside-your-own-gui**.

**Comment by starsun7** [comment]
Thank you for taking the time to help me find a solution.
I looked at the case you helped me with, but I didn't get it.  But I finally figured out why my code didn't work.
Set blit to True for funcanimation.  Func then sets the return value, and that's it.  As below: 
'''
    def update_candle(self, steps):
        print(steps)
        end = 50 + steps
        self.myfig.fig.clear()
        self.myfig.ax1, self.myfig.ax2 = self.myfig.fig.subplots(nrows=2, ncols=1, sharex=True)
        mpf.plot(self.myfig.df.iloc[0:end], ax=self.myfig.ax1, type='candle', volume=self.myfig.ax2,
                 mav=[5, 10, 30], axtitle='customize plot', tight_layout=True)
        return [self.myfig.ax1, self.myfig.ax2]

    def on_start(self):
        self.ani = FuncAnimation(fig=self.myfig.fig, func=self.update_candle, blit=True, interval=10)
'''
But I have a question. In the mpf animation demo, it states that mplfinance does not support "blitting". In my code, blit is set to True and works fine.  I was puzzled.  Maybe one day, I'll find out.

**Comment by starsun7** [comment]
Thank you for taking the time to help me find a solution.
I looked at the case you helped me with, but I didn't get it.  But I finally figured out why my code didn't work.
Set blit to True for funcanimation.  Func then sets the return value, and that's it.  As below: 

   ```
 def update_candle(self, steps):
        print(steps)
        end = 50 + steps
        self.myfig.fig.clear()
        self.myfig.ax1, self.myfig.ax2 = self.myfig.fig.subplots(nrows=2, ncols=1, sharex=True)
        mpf.plot(self.myfig.df.iloc[0:end], ax=self.myfig.ax1, type='candle', volume=self.myfig.ax2,
                 mav=[5, 10, 30], axtitle='customize plot', tight_layout=True)
        return [self.myfig.ax1, self.myfig.ax2]

    def on_start(self):
        self.ani = FuncAnimation(fig=self.myfig.fig, func=self.update_candle, blit=True, interval=10)
```

But I have a question. In the mpf animation demo, it states that mplfinance does not support "blitting". In my code, blit is set to True and works fine.  I was puzzled.  Maybe one day, I'll find out.

**Comment by DanielGoldfarb** [comment]
> But I have a question. In the mpf animation demo, it states that mplfinance does not support "blitting". In my code, blit is set to True and works fine. I was puzzled. Maybe one day, I'll find out.

I have the same question!  And hope that one day I will also find out.   As I understand it, according to the [matplotlib documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html) blitting is used to optimize drawing by only re-drawing those Artist objects on the plot *that have changed or were added*.  Per the documentation: "`If blit == True, func must return an iterable of all artists that were modified or created.`"

The reason I say that mplfinance does not support "blitting" is because the lower level mplfinance functions *do not return the artist objects*.  It would take a non-trivial refactoring of mplfinance to return the Artist collections that it creates.  Maybe someday if there is a strong demand for it.  

Instead of blitting, the mplfinance animation examples **clear** the Axes, and redraw all Artist objects on the plot.  This is somewhat inefficient but it keeps the code *much simpler*, and I have found that the entire redraw typically takes only a hundred to few hundred milliseconds, which for most market applications is more than adquate.  (I would seriously question anyone who claims they need their chart to refresh more often than once or twice per second).

I don't know why your code did not work with the default value of `blit=False`.  Perhaps PyQt5 requires `blit=True`?  I don't know.  I notice however that your animation function is returning a list containing the Axes objects, which, strictly speaking is an "iterable of all artists that were modified or created" in that "all artists" involved in the animation *are included* in the Axes objects, which themselves are derived from matplotlib Artist objects.  Beyond that, I have very limited knowledge of animation and blitting.  When I first read the documentation that "If `blit == True`, func must return an iterable of all artists ..." then I assumed I would have to specifically return the collections of rectangles and lines that make up the candlesticks.  It never occured to me to return the Axes objects, but perhaps that is a way that mplfinance can support blitting in the future.

I am happy to hear you got this working.  Please, if you don't mind, would love to see a short screen video clip of your chart animating (as I always enjoy seeing the amazing things people are doing with mplfinance).  All the best.  --Daniel

**Comment by starsun7** [comment]
Thank you again for your answer. Mplfinance is really an amazing package.
