### ISSUE TITLE
Potential for 'labeling' candlesticks on a candlestick chart 

### ISSUE THREAD

**Issue by AlexSopa** [matplotlib/mplfinance#484]
I'm looking to label the candlesticks but have been unable to find a way to do so. You can see an example below where they're labeled as 1s and 2s.
![image](https://user-images.githubusercontent.com/56882081/147361505-02180bc1-11b3-42fb-96da-b5bd50a67793.png)

Is there any possible way to create this type of outcome with the current mplfinance library? 

Thanks in advance

**Comment by DanielGoldfarb** [comment]
@AlexSopa 
Alex, I assume since you closed this, you found some of the other posts with work-around solutions.  I'll add a few of the links here so that if someone finds this one they will be led to the others:

- https://github.com/matplotlib/mplfinance/issues/97
- https://stackoverflow.com/a/70342687/1639359
- https://github.com/matplotlib/mplfinance/issues/123
