### ISSUE TITLE
Why does the "xtick" label is not date when I only use one candle per plot?

### ISSUE THREAD

**Issue by anbarief** [matplotlib/mplfinance#505]
Here I modified the animation example in `examples`  folder to animate just one candle per frame. But the x-axis does not show the date time when there is only one candle used.

```
import pandas as pd
import mplfinance as mpf
import matplotlib.animation as animation

idf = pd.read_csv('data/SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)
idf.shape
idf.head(3)
idf.tail(3)
df = idf.loc['2011-07-01':'2011-12-30',:]

fig = mpf.figure(style='charles',figsize=(7,8))
ax1 = fig.add_subplot(2,1,1)
ax2 = fig.add_subplot(2,1,2)

##modification:
lowest_low = min(df['Low']); highest_high = max(df['High'])
ax1.set_ylim([lowest_low, highest_high])
##

def animate(ival):
    if (20+ival) > len(df):
        print('no more data to plot')
        ani.event_source.interval *= 3
        if ani.event_source.interval > 12000:
            exit()
        return

    ##modification:
    data = df.iloc[(ival)]; data=pd.DataFrame([list(data.values)], columns = list(data.keys()),index=[data.name]);
    data.index.name='Date'
    ##

    ax1.clear()
    ax2.clear()

    ##modification:
    mpf.plot(data,ax=ax1,volume=ax2,type='candle', style='yahoo', ylim = (lowest_low, highest_high))
    ##

ani = animation.FuncAnimation(fig, animate, interval=250)

mpf.show()
```

**Comment by DanielGoldfarb** [comment]
This has to do with how matplotlib determines how many and where to place tick marks on the x-axis.  It does this using an instance of a Tick Locator class.  Matplotlib provides several [Tick Locator](https://matplotlib.org/stable/gallery/ticks/tick-locators.html) classes, or you can write your own.  

The default tick locator does not expect a single data point.  I expect this may be why it does not display the tick label (date). 
 Presently mplfinance does not give you access to the matplotlib tick locator class (for you to possibly change which tick locator is being used) however as a workaround you can "manually" set the tick location (and tick label) yourself.  Here is a version of your code that does that:

Notice that, when creating the Axes objects, the code **shares** the x-axis so that both Axes have the same x-axis.
The code also (knowing that it is plotting only one date) manually sets a single tick on the x-axis (`ax1.set_xticks([0.,])`), and manually formats the date label for that tick: `dtlabel = str(data.index[0])[0:11]; ax1.set_xticklabels([dtlabel,])`.  I think the following code does what you want.  Please test it and let me know.

```python
import pandas as pd
import mplfinance as mpf
import matplotlib.animation as animation

idf = pd.read_csv('data/SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)
df = idf.loc['2011-07-01':'2011-12-30',:]

fig = mpf.figure(style='yahoo',figsize=(7,8))
ax2 = fig.add_subplot(2,1,2)
ax1 = fig.add_subplot(2,1,1,sharex=ax2)

lowest_low = min(df['Low']); highest_high = max(df['High'])
ax1.set_ylim([lowest_low, highest_high])

def animate(ival):
    if (20+ival) > len(df):
        print('no more data to plot')
        ani.event_source.interval *= 3
        if ani.event_source.interval > 12000:
            exit()
        return
    data = df.iloc[ival:(1+ival)]
    ax1.clear()
    ax2.clear()
    dtlabel = str(data.index[0])[0:11]
    mpf.plot(data,ax=ax1,volume=ax2,type='candle',ylim=[lowest_low, highest_high], xrotation=0)
    ax1.set_xticks([0.,])
    ax1.set_xticklabels([dtlabel,])

ani = animation.FuncAnimation(fig, animate, interval=250)

mpf.show()
```
---

---


And here is a diff to highlight the changes that I made to implement the tick locator work-around:


```diff

8,9c8
< fig = mpf.figure(style='charles',figsize=(7,8))
< ax1 = fig.add_subplot(2,1,1)
---
> fig = mpf.figure(style='yahoo',figsize=(7,8))
10a10
> ax1 = fig.add_subplot(2,1,1,sharex=ax2)
22,25c22
<
<     data = df.iloc[(ival)]; data=pd.DataFrame([list(data.values)], columns = list(data.keys()),index=[data.name]);
<     data.index.name='Date'
<
---
>     data = df.iloc[ival:(1+ival)]
28,29c25,28
<
<     mpf.plot(data,ax=ax1,volume=ax2,type='candle', style='yahoo', ylim = (lowest_low, highest_high))
---
>     dtlabel = str(data.index[0])[0:11]
>     mpf.plot(data,ax=ax1,volume=ax2,type='candle',ylim=[lowest_low, highest_high], xrotation=0)
>     ax1.set_xticks([0.,])
>     ax1.set_xticklabels([dtlabel,])

```

**Comment by anbarief** [comment]
Okay thanks sir, so that is done manually using `AxesSubplot.set_xticklabels`. I was planning to make an animation like in this video I made manually using matplotlib 2 yrs ago: https://www.youtube.com/watch?v=hx-W7McYywY , but only for one candle (or date) each frame.

**Comment by DanielGoldfarb** [comment]
Thanks.  Would love to see your video using mplfinance when done.   Please post it here.  Thank you.
