### ISSUE TITLE
Bar chart draws bars incorrectly and x axis dates are wrong.

### ISSUE THREAD

**Issue by Madman600** [matplotlib/mplfinance#508]
I am drawing several indicator subplots that I'd like to be bar charts. If I use line chart everything is fine. If I use bar chart it draws the bars incorrectly, and the x axis is wrong.

line chart:
![image](https://user-images.githubusercontent.com/38760981/158072511-c87b9c64-e4c3-4915-ba48-482855748f83.png)

bar chart, all that has changed is type = 'bar':
![image](https://user-images.githubusercontent.com/38760981/158072552-cb4a92f6-9149-42f5-af13-a861a8923a21.png)

**Comment by DanielGoldfarb** [comment]
Need to see your data, and your code.  Please post your code here.  And either post data here pre-formatted, *or better yet* save data to csv file and post csv file to a gist or other place where it can be easily accessed.

**Comment by DanielGoldfarb** [comment]
I suspect that you may have too many data points too close together so your bars are running together in time.  But could possibly be another issue also.  Need to see data and code to tell.

**Comment by Madman600** [comment]
Here you go: https://gist.github.com/Madman600/b3ddfee7d75fe0d84dfc8ac16ffab456#file-df-txt

**Comment by DanielGoldfarb** [comment]
This is an interesting problem.   I imagine, since you have discovered using `type='step'` (instead of `type='line'`) you now have a plot that works for you.  I've been experimenting around with the bar plot, and I am begining to think that this is something at the matplotlib level, perhaps the result of `Axes.bar()` treating dates and/or the x-axis differently than does `Axes.plot()` or `Axes.step()`.   Notice in the two plots below that the x-axis lower (left) and upper (right) limits are different in the bar chart than they are in the step chart, despite the data being the same.  

I'm going to do some more experiments with `Axes.step()` and `Axes.bar()` and see if I can reproduce the issue in a case of a much simpler data set, and calling these matplotlib functions directly.


![issue508_step](https://user-images.githubusercontent.com/11164790/158085692-b41b8489-a356-47c8-8b04-f9d02e3619a5.png)

![issue508_bar](https://user-images.githubusercontent.com/11164790/158085706-95955fcf-4604-45cf-9c88-d66a556a13d9.png)

**Comment by DanielGoldfarb** [comment]
The problem is that with a **bar chart**, *matplotlib assumes the width setting of the bars is relative to the *x-axis **data*** itself.  

The default bar width (in mplfinance) is 0.8, which is *much, much larger than the x-axis difference between any two data points*.   

Since `show_nontrading=True`, the x-axis values are **matplotlib datetimes** (which as you may know are floating point number of days plus fractions of a day since year 1).

Thus, the first few datetimes
```text
2021-09-27 08:30:00
2021-09-27 08:31:00
2021-09-27 08:32:00
2021-09-27 08:33:00
2021-09-27 08:34:00
```
Are therefore actually:
```text
18897.35416667 
18897.35486111 
18897.35555556 
18897.35625000
18897.35694444
```

As you can see, the difference between any two data points on the x-axis is approximately `0.00069`.  The bar width should be set to approximately the same order of magnitude.

If, in your function **`price_plot()`** you change the following line of code:
```python
return mpf.make_addplot(df[[column]], type='step', color='g', ax=ax)
```
to
```python
return mpf.make_addplot(df[[column]], type='bar', width=0.001, color='g', ax=ax)
```

Then you will get the following plot:

![issue508_barfix001](https://user-images.githubusercontent.com/11164790/158088507-60c0260b-11c4-4fc7-9bc7-538e2ffd959a.png)

**Comment by DanielGoldfarb** [comment]
The volume bars, and candles, used to have issues (see https://github.com/matplotlib/mplfinance/issues/115) 

I wrote a bunch of code to automatically adjust widths according to the average distance between points.  It might be worthwhile (someday) to provide users with an automatic width for any bars, but it could be tricky.  Perhpas the user has to "opt in" by setting a kwarg, because ultimately mplfinance doesn't know what the user is plotting when calling `mpf.make_addplot()` (whereas with candlesticks and volume bars mplfinance does know what it's plotting).

For more information, you can [see the width adjusting code here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_widths.py#L105-L166), and there is also a [tutorial about it here](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb).

**Comment by DanielGoldfarb** [comment]
@Madman600 
Thanks for reporting this.  Was definitely interesting to try to solve, and gave me some ideas how mplfinance may automatically adjust this for users.

**Comment by praksharma** [comment]
Wow, I just had the same issue. Thanks guys.

**Comment by Jamesong7822** [comment]
Thanks for the solution. i was able to automatically adjust for the bar width via:
```python
macdHistWidth = techAnalysis["MACD"]["macdHist"].index.to_series().apply(lambda x: mdates.date2num(x)).diff().mean()
```
