### ISSUE TITLE
Does mplfinance support simple line diagram without K line?

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#524]
Does mplfinance support simple line diagram without K line?

The data is as follows. There is no OHLC, but there is a date series. I want to draw a line diagram. Can such data be plotted with mplfinance?

dt	price
2022-04-28 21:36:00	20815.0000
2022-04-28 21:32:00	20860.0000
2022-04-28 21:32:00	21530.0000
2022-04-28 21:29:00	218540.0000
2022-04-28 21:28:00	4193.0000
2022-04-28 21:25:00	21565.0000
2022-04-28 21:24:00	219750.0000
2022-04-28 21:24:00	7206.0000
2022-04-28 21:23:00	5349.0000
2022-04-28 21:23:00	4216.0000

**Comment by DanielGoldfarb** [comment]
mplfinance currently does not support plotting *without* OHLC data.   However it has been requested once or twice before, so probably we will support it sometime in the future.

In the meantime, as a workaround, you can create a "dummy" OHLC dataframe, with only one datapoint in it (the rest must be NaNs so that it has the correct length).  Here is some example code.  The input file "line_only.csv" contains the data you have provided above:

```bash
dino@DINO:~/code/mplfinance/examples$ cat line_only.csv
Date,Price
2022-04-28 21:36:00,20815.0000
2022-04-28 21:32:00,20860.0000
2022-04-28 21:32:00,21530.0000
2022-04-28 21:29:00,218540.0000
2022-04-28 21:28:00,4193.0000
2022-04-28 21:25:00,21565.0000
2022-04-28 21:24:00,219750.0000
2022-04-28 21:24:00,7206.0000
2022-04-28 21:23:00,5349.0000
2022-04-28 21:23:00,4216.0000
```

```python
#!/usr/bin/env python
import pandas as pd
import mplfinance as mpf

infile = 'line_only.csv'
line   = pd.read_csv(infile, index_col=0, parse_dates=True)

length = len(line)

o = [float('nan')]*length
h = [float('nan')]*length
l = [float('nan')]*length
c = [float('nan')]*length

o[0] = 0.0
h[0] = 0.0
l[0] = 0.0
c[0] = 0.0

df = pd.DataFrame(dict(Open=o,High=h,Low=l,Close=c))
df.index = line.index

ap = mpf.make_addplot(line,secondary_y=False)

mpf.plot(df,addplot=ap)
```

The above code produces the following figure:

![Figure_1](https://user-images.githubusercontent.com/11164790/166078338-eedc78df-9237-4e80-a84d-b9c1ef7e5dbc.png)


Alternatively, you could simplify the code like this:

```python
#!/usr/bin/env python
import pandas as pd
import mplfinance as mpf

infile = 'line_only.csv'
line   = pd.read_csv(infile, index_col=0, parse_dates=True)

length = len(line)

o = [0.0]*length
h = [0.0]*length
l = [0.0]*length
c = [0.0]*length

df = pd.DataFrame(dict(Open=o,High=h,Low=l,Close=c))
df.index = line.index

ap = mpf.make_addplot(line,secondary_y=False)

mpf.plot(df,addplot=ap)
```

to give this plot:
![Figure_2](https://user-images.githubusercontent.com/11164790/166078547-b17460f3-a98d-45c4-bddd-46c1e44e298b.png)

**Comment by lyl1836** [comment]
@DanielGoldfarb ：
Thank you very much！

**Comment by DanielGoldfarb** [comment]
Note:  In each the above examples, you can also make the k line (candlestick) chart even more hidden by adding `type='line'` and `linecolor=background_color` to your call to `mpf.plot(df,type='line',linecolor=background_color,addplot=ap)` where background_color is a color specifier that matches the face color of the plot.  In this way the main OHLC plot will be a line and will match in color to the background so that even if small then it will be very difficult (or even impossible) to see.

I am considering for the future adding a kwarg to `mpf.plot()` to request *not* plotting the candlesticks.  Although that seems to me strange, since the main purpose of mplfinance is to display OHLC data, such a feature was requested more than once.
