### ISSUE TITLE
Feature Reuest: more plots is needed

### ISSUE THREAD

**Issue by wzlu** [matplotlib/mplfinance#53]
As far as I know, there are only two plots in mplfinance.
Sometime, I need other indicators that is simular with Volume.
I want to added them below the Vol plot.
How can I do it?

**Comment by DanielGoldfarb** [comment]
Correct, at this time only two [sub]plots are available.  I expect within the next three to four weeks to have the following enhancements:

1. kwarg `returnfig=True` to return the figure and axes that `mpf.plot()` created.
2. allow 3 subplots (instead of just two).
3. allow caller to externally create `mplfinance`-owned subplots in any arbitrary configuration, and pass these subplot axes into `mpf.plot()` and `mpf.make_addplot()`.

With the above in mind, now marking this:

Duplicate of #17
