### ISSUE TITLE
Feature Request:Remove defaulting matplotlib style

### ISSUE THREAD

**Issue by RaybenRed** [matplotlib/mplfinance#547]
First of all thank you for this amazing job!

**Is your feature request related to a problem? Please describe.**
At every `mpf.plot` call, `_styles._apply_mpfstyle` resets matplotlib style to default, this is annoying for people that either do not want to bother with matplotlib custom styles files or need to dynamically change matplotlib style.

**Describe the solution you'd like**
Commenting out the line `plt.style.use('default')` in `_styles._apply_mpfstyle`. 

Thank you

**Comment by DanielGoldfarb** [comment]
@RaybenRed -  Thank you for contributing.  I will assume that you have worked through, and thoroughly understand, [the tutorial on **mplfinance styles**](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb).   If you have not done that, please work through that now.

The reason for the line `plt.style.use('default')` in `_styles._apply_mpfstyle.py` is to **ensure that [mplfinance styles](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata) are consistent**.   

Without that line of code, it is possible (and likely) that *different* calls to `mpf.plot(...,style='style_name')` will result in plots that appear *different* from each other, despite specifying the exact same mplfinance style.

As you know from [the tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynbv), when using mplfinance you can create your own **custom mplfinance style** either by modifying and existing style or starting from scratch.  And if you have a particular custome mplfinance style that you use frequently, feel free to submit a pull request to include it in the mplfinance library (so that you can simply reference it by name instead of having to customize it in each plotting program that you write).   You can save a custom style to a file by calling `mpf.write_style_file(style, filename)`.

If you are doing additional plotting with matplotlib, and you find that mplfinance styles are interfering with that other matplotlib plotting, there are a couple of options to deal with this successfully:
1. Customize and use mplfinance styles for your matplotlib plots.   This can be done by creating your matplotlib figure objects using **`mpf.figure(style=my_custom_style)`** (instead of `plt.figure`).
2. Surround either your matplotlib work, or your mplfinance work, or both, with:
```python
with plt.rc_context():
    # do work here
```
The `with plt.rc_context()` paridigm copies and isolates matplotlib's global structures so that any work within the "`with`" section will not affect any other matplotlib work either outside of the "`with`" nor withing a different "`with`".  For more information see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.rc_context.html .

Let me know if you have any additional questions or suggestions.

**Comment by RaybenRed** [comment]
Thanks a lot for your crystal clear answer. You are of course right, consistency between styles is broken when I tried commenting that line... My initial problem was that my custom matplotlib configuration is in conflict with mpf `mpl.use(style)` calls, but I realized that in fact, mpf rcParams.update calls (from different builtin styles) would alter it too.

So the solution I inexpertly suggested would have to be extended to erase any `rcParams.update` which surely contradicts mplfinance's primar usage.

Thanks a lot for you answer, I will use these solutions.
Have a good day!

**Comment by DanielGoldfarb** [comment]
Thanks.  One thing I will point out that may be helpful for you, is the ability to customize any matplotlib rcParams values when creating an mplfinance style.  This is only mentioned briefly with no elaboration [in the "Optional Keyword Arguments" table at the end of the styles tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb) ... function **`mpf.make_mpf_style()`** accepts kwarg **`rc=`** to override any matplotlib rcParams within the mplfinance style.
