### ISSUE TITLE
How to draw line graph using dataframe including zeros?

### ISSUE THREAD

**Issue by drdoof2019** [matplotlib/mplfinance#550]
Hello, I am developing a analysis program.
In basic version I am drawing with pyplot and result is:
![a1](https://user-images.githubusercontent.com/50274757/185587842-f4782332-f9e6-4d14-9d0e-96b503c3b7e1.png)
I wanted to draw same plot with mpl finance, but result is:
![a3](https://user-images.githubusercontent.com/50274757/185588342-6768976d-999f-46cd-a55d-469b053bf183.png)

so how can I fix this problem (connect lines with each other)?

my graph code is: 
```
def plotting_datav6(frame, symbol, interval, lookback, pattern):
    lookback = lookback[:-1]
    mc = mpf.make_marketcolors(up='g',down='r',alpha=0.5,volume={'up':'g','down':'r'})
    s  = mpf.make_mpf_style(base_mpf_style='binance',marketcolors=mc,gridstyle='')
    frame = frame.fillna(0)
    print(frame.tail(10))
    fig = mpf.figure(style=s,figsize=(12,9))
    ax = fig.add_subplot()
    ax.set_title(f'{symbol} {interval} {pattern} detected.') # ,loc='left'

    apds = [mpf.make_addplot(frame['current_pattern'],ax=ax,linestyle='--',color='red')]

    mpf.plot(frame,ax=ax,type='candle',addplot=apds,xrotation=0,tight_layout=False, ylim=(min(frame.Low)*0.99, max(frame.High)*1.01)) #,mav=(5,20,50)


    mpf.show()
```

if you need  this is an example csv with needed values.
[example_dataset.csv](https://github.com/matplotlib/mplfinance/files/9380945/example_dataset.csv)
and same file in excel format.
[example_dataset.xlsx](https://github.com/matplotlib/mplfinance/files/9380951/example_dataset.xlsx)

By the way I did not wanted to convert na's to 0 but if I don't, it does not draw that red lines too.

**Comment by DanielGoldfarb** [comment]
@drdoof2019 

1. First try **`frame = frame.fillna(float("nan"))`**, instead of `frame = frame.fillna(0)`.

2. If that doesn't work, perhaps try using **`alines`** or **`tlines`** kwarg, [**as described here.**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb)

---


By the way, for what you are trying to do, there is no reason to create your own Axes object, and I strongly recommend against it.  When you use your own Axes, you limit what mplfinance can do for you.  I reccomend it ***only*** when what you are trying to accomplish cannot be done in any other way.   Also, in the rare case that you do need access the the Axes, it is always better to use `returnfig=True` rather than creating your own external Axes.

**Comment by drdoof2019** [comment]
For future learners the resulting graph:
![a4](https://user-images.githubusercontent.com/50274757/185607927-693d81d1-7484-4b9b-894a-ec787f04eae7.png)
all I did was create a list called points and add ('Date', 'Value') for alines. 
Ex: [('2022-08-14 16:00:00', 2.195), ('2022-08-15 05:00:00', 2.302)]
then add `alines=points` to `mpl.plot()` function.
Thank you for your wise advice I hope to be like you someday:)
