### ISSUE TITLE
External Axes mode with fig.add_axes 

### ISSUE THREAD

**Issue by Jrlowndes** [matplotlib/mplfinance#574]
In reviewing the documentation and examples for External Axes Mode, it is not clear to me how use multiple fig.add_axes rather than using fig.add_subplot.

An example would be a 2 x 2 layout, each with their own OHLC + separate indicator. No volume graph.

Regards

John

**Comment by DanielGoldfarb** [comment]
John, 

- The [**arguments to `fig.add_subplot()`**](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_subplot) require that you specify an Axes within a Figure **in terms of grid of axes and an `index`**, where the `index` indicates the position of the Axes object within that grid.  In other words, the Axes are organized into ***rows*** and ***columns***, and each call to `fig._add_subplot()` will create and return ***one*** Axes object within those rows and columns, as specified by the `index` value.  
Calling `fig.add_subplot()` will distribute the Axes evenly within the Figure, based on the number of rows and columns.  Multiple calls to `fig.add_subplot()` with *different or varying numbers of rows and columns* (for the same Figure), if done carefully, can be utilized to distribute Axes in various ways, since each call will evenly distribute the Axes positions within the grid *based on the number of rows and columns passed into each call*.

- The [**arguments to `fig.add_axes()`**](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_axes) require that you specify an Axes within a Figure **in terms of position and size** of the Axes within the Figure.  This gives one *greater control over the exact position and size* of each Axes within a Figure, compared with the "grid" or "rows and columns" approach.  
The size/position of each Axes is specified using a tuple of four numbers: **left, bottom, width, height**, where each number is a ***fraction of the overall*** Figure.   Thus, a `left` value of **0.0** indicates that the lower left corner of the Axes is to be on the far left of the Figure, whereas a `left` value of **0.25** would indicate that the lower left corner of the Axes is exactly 25% of the way in from the *left side of the Figure*, etc.  Similarly a `width` value of **0.33** would mean that the Axes takes up one third of the overall width of the Figure, etc.

**Both of the above methods will work with mplfinance's external axes mode.  *However***, not only does `fig.add_axes()` give the user greater control over the exact position and size of an Axes within the Figure, I have found (perhaps anecdotally) that `fig.add_axes()` is also less likely to create Axes that present difficulties for some things that mplfinance does.  It is for this reason that I encourage others to prefer using (and we use internally within mplfinance) `fig.add_axes()` (instead of `fig.add_subplot()` or any other of the matplotlib methods for creating Axes objects).

All the best.  --Daniel

**Comment by Jrlowndes** [comment]
Thanks Daniel,

Just got it working. I prefer the add_axes for the control and ability it yields.

Regards,

John
