### ISSUE TITLE
Feature Request: Idea example an all in one example to improve mpl finance

### ISSUE THREAD

**Issue by AureliusMarcusHu** [matplotlib/mplfinance#579]
Dear mister GoldFarb,

I have been working on an all in one solution to plot stock charts for a very long time. But my knowledge of matplotlib is too small to complete the job. Still, you will certainly be able to pick up some good ideas to improve mplfinance. Maybe the experienced programmers as you can complete the job. In this way my work is not completely lost, and can I contribute something to mplfinance.

The code in annex works fine on a windows 10 64 bit machine, python 3.9 32 bit and matplotlib 3.3.1 installed . The only minor is that it generate errors with the newer versions of matplotlib and it is slower than mplfinance. Maybe the wise guys can fix this. Yet I want to mention here that the developers of matplotlib don't pay any attention to the compatibility with their own previous versions and that is worthless. That in contrast to what you do and give people the opportunity to adapt to the new modules over range of time. As it should be.

**Idea explenation of my work:**
With this module I plot eod charts for stocks, etfs, and currencies as well. Still, I don't think it's stable enough to put on github as a package. In my opinion it is not finished yet.

### **Split into two major divisions:** 
**1. User Interaction**
- Custom control buttons on the bottom left using 'Tkagg' backend and 'NavigationToolbar2Tk'. In this way, the user is able to easily navigate through the entire time range of the stock or security without leaving the chart. All axes and grid are automatically updated when shifting or zooming.
- Detailed info about the chart on the right bottom provided by mouse cursor and multicursor.
- Automatic legend plotting.

**2. Plotting chart**
- Subroutine 'PlotGraph' will draw the chart. The module opens always in full zoomed size.
- All data arrays are provided by the pandas dataframe parameter 'df' except fibonacci levels will be set by a separately dict called 'fib'.
- The other parameters are mostly 'lists' containing column names of the pandas dataframe 'df' 
- Based on these parameters, the module calculates how many lines will be plotted the upper plot and how may indicators will be plotted as well.
- Examines whether there are buy or sell signals and plot them in the upper plot as you can see. Green is Buy. Red is Sell.
- The module automatically divides the figure into subplots and calculates the size of the plots.
- If the dictionary 'fib' is not empty, the fibonacci levels are automatically plotted on the chart.

**Where do I get stuck:**
As mentioned above it works well when plotting charts with eod data. But as soon as I want to plot longer-term intraday data, I can suddenly shake hands with every byte. Then it works painfully slowly. Probably due a wrong build of the module and it is there where my knowledge of matplotlib falls short. I hope I haved contributing something to mplfinance ?

Below a screenprint of a eod chart:
![image](https://user-images.githubusercontent.com/25880296/209674214-923a2def-12c8-4b8b-8ede-d36825682680.png)

The module:
[charts_eod.zip](https://github.com/matplotlib/mplfinance/files/10308436/charts_eod.zip)

**Comment by DanielGoldfarb** [comment]
The purpose of **`mplfinance`** is to provide a library of functions to make it easier to provide visualizations commonly used when trading or analyzing price movements in the financial markets.

This however does *not* include the user interface (buttons, etc), nor does it include technical analysis (other than specifically visual analyses such as renko or point-and-figure).   Instead, `mplfinance` makes it possible to use ***various*** user interfaces (such as Tkinter), which are called "backends" in `matplotlib`.  And `mplfinance` makes it possible to include technical analyses from any calculation.

If the desire is for an "all-in-one" package, I fully support the idea of writting a new package that is a "wrapper" around `mplfinance` to include specific user-interface elements, and/or specific technical analyses or data sources.   One already existing example is [**`Pandas TA`**](https://github.com/twopirllc/pandas-ta#pandas-ta---a-technical-analysis-library-in-python-3) written by Kevin Johnson

While I will continue to enhance `mplfinance` to make it easier to implement features that are otherwise available from matplotlib, it is definitely beyond the scope of `mplfinance` to include functionality that is tied to a specific user interface, or that implements technical analysis calculations (since such calculations are already available in many other libraries).  Similarly `mplfinance` will never implement the ability to fetch market data, since such functionality is already available from many other packages.  In this way, each `mplfinance` user can choose for themselves: (1) which user interface package to use, (2) which technical analysis calculations to use, and (3) from what source they want to get their market data.

All the best.   --Daniel
