### ISSUE TITLE
Trying to Identifying the last column on a P&F chart

### ISSUE THREAD

**Issue by anidealone** [matplotlib/mplfinance#588]
I'm using trying to determine whether the last column on a PNF chart is an X or O.  (I actually don't even need or want the chart just the "results".)

```python
cv = {}
mpf.plot(stock_data,  type='pnf', return_calculated_values=cv )
```

What values in return_calculated_values would tell me this? I'm assuming that's the best method to use. I'm a beginner at this so any help is much appreciated!

**Comment by DanielGoldfarb** [comment]
@anidealone 

Since the contents of the returned **calculated values dict** may vary depending on the plot `type` and other `kwargs`, and may even change over time with new versions of mplfinance, then I recommend ***as a general rule*** that you ***explore*** the contents of the calculated values dict, to see what you can figure out on your own.   Here is some example code for doing that:

```python
import pandas as pd
import mplfinance as mpf
import pprint

# code here to read data into dataframe `stock_data` ... then:

cv = {}
mpf.plot(stock_data,  type='pnf', return_calculated_values=cv )

print('cv keys=',cv.keys())

pp = pprint.PrettyPrinter(indent=4)
for key in cv.keys():
    print('====',key,'====')
    pp.pprint(cv[key])
    print()
```

If you do the above for `type='pnf'` you will see (among all the cv keys) the following three keys that may be of interest to you: `'pnf_dates'`, `'pnf_counts'`, and `'pnf_values'`

---

Using sample data from this repository, `'data/yahoofinance-SPY-20200901-20210113.csv'`, the results look something like this:

```text
==== pnf_dates ====
[   datetime.datetime(2020, 9, 2, 0, 0, tzinfo=datetime.timezone.utc),
    datetime.datetime(2020, 9, 25, 0, 0, tzinfo=datetime.timezone.utc),
    datetime.datetime(2020, 10, 23, 0, 0, tzinfo=datetime.timezone.utc),
    datetime.datetime(2020, 11, 3, 0, 0, tzinfo=datetime.timezone.utc)]

==== pnf_counts ====
[-5, 3, -2, 4]

==== pnf_values ====
[   [   347.09286264285714,
        341.5857192857143,
        336.07857592857147,
        330.5714325714286,
        325.06428921428574],
    [325.06428921428574, 330.5714325714286, 336.07857592857147],
    [336.0785759285714, 330.57143257142855],
    [   330.57143257142855,
        336.0785759285714,
        341.5857192857143,
        347.0928626428571]]
```

For your specific question, I think you want `'pnf_counts'`, which tells you how many X's or O's are stacked up in each column, with X's being a *positive* integer and O's being a *negative* integer.

All the best.   --Daniel

**Comment by anidealone** [comment]
Aha! I see how you did that, thank you so much for your help!! :)
