### ISSUE TITLE
Error with candle style?

### ISSUE THREAD

**Issue by DiSchi123** [matplotlib/mplfinance#59]
Nice package. But when I try to draw candles I get this error:

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'

[result.csv.txt](https://github.com/matplotlib/mplfinance/files/4364410/result.csv.txt)

Works fine for line or ohlc. 
`mpf.plot(rawdf[['Open','High','Low','Close','Volume']].head(10), type='candle', volume=True)`

The data looks like this (**intraday** e mini)
Also included as .txt file
	Open	High	Low	Close	Volume
DateTime					
2020-01-19 18:00:00	3325	3326.50	3323.25	3323.25	1815
2020-01-19 18:01:00	3323.25	3323.50	3323.25	3323.50	417
2020-01-19 18:02:00	3323.5	3323.50	3323.25	3323.50	231
2020-01-19 18:03:00	3323.25	3323.50	3323.25	3323.25	193
2020-01-19 18:04:00	3323.25	3323.50	3323.25	3323.50	147
2020-01-19 18:05:00	3323.5	3323.75	3323.50	3323.75	624
2020-01-19 18:06:00	3323.75	3324.25	3323.50	3324.25	148
2020-01-19 18:07:00	3324.25	3325.25	3324.00	3325.00	340
2020-01-19 18:08:00	3325	3325.50	3325.00	3325.50	217
2020-01-19 18:09:00	3325.75	3326.25	3325.25	3325.50	313

**Comment by DanielGoldfarb** [comment]
I am unable to reproduce.   It works fine for me; see here: https://github.com/DanielGoldfarb/mplfinance_issue59/blob/master/issue%2359.ipynb

It would be helpful if you can post:
- _your full code_
- _completely, all_ of the output surrounding the error:

    `TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'`

**Comment by DiSchi123** [comment]
thanks for quick reply! I can confirm that your notebook works on my environment as well.
Attaching 
1 a notebook converted to .txt containing my code. Note my pandas version is 0.25, but it works.
(pd.__version__ = 0.25.1
mpf.__version__ = 0.12.3a3)

2 the original raw file required for my code

3 the entire error message. Note that below the error message is an empty chart grid
, could not include here

attachments
[notebookastext.txt](https://github.com/matplotlib/mplfinance/files/4364554/notebookastext.txt)
[ES test file.csv.txt](https://github.com/matplotlib/mplfinance/files/4364558/ES.test.file.csv.txt)
[errormsg.txt](https://github.com/matplotlib/mplfinance/files/4364555/errormsg.txt)

**Comment by DanielGoldfarb** [comment]
@DiSchi123 Thanks for the detailed info; it definitely helps.

It appears to me that `pandas.read_csv()` is **not** converting your **'Open'** column to <class 'numpy.float64'> (as it does for the the HLCV columns) **but is leaving it as <class 'str'>.**

This is because the original file has one time-stamp-like value in the last row, so pandas decides to leave that column as `str`.   You can see this here: https://github.com/DanielGoldfarb/mplfinance_issue59/blob/master/issue%2359b.ipynb

**Comment by DiSchi123** [comment]
Nice find. I would not have thought so since the drawing of OHLC bars worked.

**Comment by DiSchi123** [comment]
That was an excellent find. Thanks!

**Comment by DanielGoldfarb** [comment]
> Nice find. I would not have thought so since the drawing of OHLC bars worked.
> So its important to ensure all input data as float, obviously.

@DiSchi123  Yes, I'm going to add a check in the beginning, so that `mpf.plot()` can report to the user what the problem is.  Thanks for bringing up this issue.

The reason it did not appear for `type=line` and `type=ohlc` is because `candle` does a comparison between High and Open and Close, and also between Low and Open and Close, in order to properly draw the candles and wicks in relation to each other; in the process, when comparing Open to other values, the comparison between `str` and `float` raised an exception.  Checking that all inputs are some flavor of float will at least notify the user about their data, instead of leaving them guessing. 
Thanks again.
