### ISSUE TITLE
Is it possible to use the current version without pandas? 

### ISSUE THREAD

**Issue by cassolmedia** [matplotlib/mplfinance#592]
I have an old script that I'm updating and it doesn't use pandas. I hand-rolled the candlestick processing originally, and I don't really wanna introduce a new library just so I can have dataframes. 

If the answer is no, then how do I draw a line using mplfinance.original_flavor?   I've figured out how to get the chart that way, but not lines. 

thanks!

**Comment by DanielGoldfarb** [comment]
By the way, on a side but related note.  I totally understand "`don't really wanna introduce a new library just so I can have dataframes.`"  I also prefer to avoid, as much as possible, increasing the number of libraries in existing code that I am maintaining.  However, I think you will find over time that the power of dataframes in general far outweighs any downside to introducing the library to existing code.  

Dataframes make data manipulation and storage far, far easier.  There have even been times when I needed a collection of objects, and in the past I would have designed a class for my purposes, and created a list of objects of that class.  But now, what I often do is just use a dataframe, where each column is a member of what would have been my class, and each row is an instance of that class.  It works well because the values stored in a dataframe do not have to be only numbers or strings, they can be any object, even methods.  I actually do this internally in `mplfinance` to keep track of which data is in each panel and Axes of the plot.  Mplfinance has an internal dataframe where one column of each row is a matplotlib Axes.  And the various other colums track which panel the Axes is on, which data goes into that Axes, whether the Axes labels are on the left or right, etc.  I hope this is making sense.  Please let me know.   Wishing you all the best.   And thank you for your interest in mplfinance.

**Comment by cassolmedia** [comment]
@DanielGoldfarb  thanks or the reply.  What I was trying to do is draw a line on the candlestick chart. I'm already generating candlesticks, just need to annotate a bit.  I feel like the old version had that, right?  or maybe I'm misremembering and I hit this same wall years ago. 

I'm sure dataframes are useful in a number of ways. But I really try not to solve for problems I'm not having, especially in legacy code!  But then again I'm also and older developer and  I'm always slow to adopt new libraries/dependencies without a strict reason... read stubborn lol

If I'm understanding correctly, this is basically a "can't be done at present" situation right?

**Comment by DanielGoldfarb** [comment]
@cassolmedia 
So you want to draw a line on the candlestick chart ... maybe a moving average, or a bollinger band, or a trend line, or support line?   All of these are *definitely possible with both the new mplfinance and the old mplfinance.original_flavor.* 

With the new mplfinance, these are trivial things to do.  See for example the following tutorials:
- [**adding your own technical studies to plots**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb),  and 
- [**adding trend lines, support lines, and arbitrary lines to plots**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb)

These things are all *also possible* with the old `mplfinance.original_flavor`, however that version of mplfinance is much lower level and requires you to know somewhat how to use `matplotlib`.   

The basic way to do it (without Pandas) is this:  After you have plotted candlesticks on your `Axes` object, then ***before*** calling `plt.show()` you would call `Axes.plot()` on your `Axes` object **once for each line that you want to plot on top of the candlesticks**.  Then call `plt.show()` to display the entire plot.  You can see [**an example of how to do this here**](https://github.com/matplotlib/mplfinance/blob/master/examples/original_flavor/finance_work2.py).

As you can see, these things are ***available with both the old and the new***.   However the *old "roll your own" way requires you to write a lot more code*, and keep track of a many more variables than the new way.   

Trust me, I am well aware of my own internal resistance to doing things a new way.  I've been coding since 1980.  For many years I resisted even learning C++.  Old habits die hard.  I learned Python and Pandas only about 5 and 4 years ago resepectively.  With Pandas, I [**proposed to give a talk on Pandas at a conference**](https://www.youtube.com/watch?v=4AXAKUlF_3c) which put me in a position where I had no choice but to learn Pandas.

May I suggest (challenge you, as a fellow older developer) that you set aside **just 2 hours** to go through **just the first four [mplfinance tutorials](https://github.com/matplotlib/mplfinance#contents-and-tutorials)** ("Basic Usage" through "Subplots").  It seems to me that after only a two hour investment, you will find it gives back far more than two hours, in just a matter of days, based on the amount of time you will save compared with making these plots [the old way](https://github.com/matplotlib/mplfinance/blob/master/examples/original_flavor/finance_work2.py).

I can also be available to help or advise if you want to post your code somewhere for me to see. 
All the best.   --Daniel

**Comment by cassolmedia** [comment]
@DanielGoldfarb  thank you!  what I was missing was how to get to the plot() function!  this is exactly what I needed :-) 

I'm sure I'll get around to pandas sooner than later... especially since it seems to be required for most ai tutorials.  I'm sure it's fine. I think it feels a bit "black box"-ish to me. I don't like that tutorials gloss over the data translation that's happening. idk...  there I go yelling at clouds again haha

I'll  set aside some time to try out the new version on a less critical project. I have a few side projects that I could add a charting feature to. 

thanks so much for the help. I really appreciate it.

**Comment by DanielGoldfarb** [comment]
@cassolmedia   

T-  I'm glad you were able to get what you needed from my response.  Would love to see some of your work.  If you feel like it, please post an image or a link.   Stay in touch.   All the best.   --Daniel
