### ISSUE TITLE
is it able to use mpld3 library with mplfinance

### ISSUE THREAD

**Issue by Baft** [matplotlib/mplfinance#593]
**Is your feature request related to a problem? Please describe.**
my mplfinance chart dose not plot correctly when try to figure it using [mpld3](https://mpld3.github.io/) library . 
i dont know what is the problem

**Comment by DanielGoldfarb** [comment]
There are some aspects of **`mpld3`** that do not work with parts of **`matplotlib`** and the owners of **`mpld3`** have classified those as enhancements.  Please see [**this answer here**](https://github.com/matplotlib/mplfinance/issues/132#issuecomment-891976073), and the continued converstation below that, for more detail.

**Comment by DanielGoldfarb** [comment]
This issue here, as I see it, is with **`mpld3`**, which purports itself as "[Bringing Matplotlib to the Browser](https://mpld3.github.io/#)."  

That sounds great in theory, but in practice it falls somewhat short, and does not completely support all of matplotlib's features. 

As you can see from [the above referenced converstation](https://github.com/matplotlib/mplfinance/issues/132#issuecomment-891976073), there are *some* workarounds for some of the issues, but not all of them.  For example, the `mpld3` ignores some of `matplotlib`'s formatting, replacing it with it's own formatting decisions.  If and when **`mpld3`** truly supports *all* of **`matplotlib's`** features, then I would expect that **`mplfinance`** will automatically be supported as well.

**Comment by DanielGoldfarb** [comment]
I would also point out one other thing that ***may be*** a suitable alternative.  

*I have never tried this myself* but apparently 
1. It is possible to use various widgets to make interactive matplotlib and mplfinance plots with jupyter notebooks, and 
2. I believe it is also possible to turn a jupyter notebook into a web app that runs in the browser. 

I recall seeing actually several applications that can do both of the above, but I have not tried any of them so I can't recommend which may be best.   I did however run across [**this**](https://runmercury.com/tutorials/dashboard-python-jupyter-notebook/) just the other day and I am hoping to find the time in the next month or so to try it out personally.
