### ISSUE TITLE
is it possible to overlay normal pyplot graphs on top of mplfinance?

### ISSUE THREAD

**Issue by DWShuo** [matplotlib/mplfinance#6]
I have a normal scatter plot that i want to overlay on top of the candle chart generated by mplfinance, is this possible?

**Comment by DanielGoldfarb** [comment]
I am working on this enhancement right now.  Hope to have it ready in a week or two.

**Comment by DanielGoldfarb** [comment]
David, would it be possible for you to send me an example of data that you want to plot, so that I can be very clear as to what you have in mind, and so that I can ensure that my implementation works for your data.  I would need a sample of both your ohlc data, and the scatter plot data that you want to overlay on top.  Can be either one csv file, or two: ohlc in one and scatter data in another.  Thanks. --Daniel

**Comment by DanielGoldfarb** [comment]
This is now working.  use `pip install --upgrade mplfinance` to get the latest version (0.12.0a0)
See https://github.com/matplotlib/mplfinance/blob/master/README.md for latest documentation.
