### ISSUE TITLE
`addplot` is not supported for `type='pnf'

### ISSUE THREAD

**Issue by nkta3m** [matplotlib/mplfinance#606]
i want add subplot line when mplfinance make plot type=pnf, i got error `addplot` is not supported for `type='pnf'.

how to add subplot to pnf plot?

**Comment by DanielGoldfarb** [comment]
Point and Figure ("pnf") is what we refer to as a **"Price Movement"** plot.  As explained in the [price-movement plots tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/price-movement_plots.ipynb) Price Movement plots (for example Renko and PNF) have a ***non-linear time axis*** that is ***compressed over some time periods, and expanded over other time periods*** *depending upon the amount of price movement within those time periods*.

Being as the time axis for these plots is *price-dependent, non-linear, and variably compressed or expanded*, the result is that plotting anything else on the same time axis may *not be mathematically well-defined*.  It is for this reason that mplfinance does not support addplot, moving averages, alines, etc. when producing a "Price Movement" type of plot.  (Let alone the complications this would add to mplfinance to ensure the same time axis compressions and expansions for anything and everything you may want to include on the same plot).

The suggestions above by @alexpvpmindustry as to how you might implement this yourself are (presently) the only way to plot additional data on top of a Price Movement style plot.  I would caution you,however, to think clearly about what additional data you want to plot, and how to interpret that data on top of the Point and Figure or other Price Movement style plot.

All the best.  --Daniel

**Comment by nkta3m** [comment]
@DanielGoldfarb @alexpvpmindustry 

Thanks a lot for the help, I understand that.

If I want to draw lines in these two green parts, how to do it?

The upper green is the resistance line, and the lower green is the support line

![2023-04-14 22_21_25-002217](https://user-images.githubusercontent.com/13484700/232073772-41849740-5751-4506-bfaa-7e092683fe4c.png)

**Comment by DanielGoldfarb** [comment]
@nkta3m 
A few pointers:
- As noted above, and in the following link: [**you will need to gain access to the matplotlib Axes objects using `returnfig=True`.**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects#1-set-returnfigtrue-when-calling-mpfplot--this-is-the-preferred-way)
- You will need also to know the PNF values, and corresponding x-axis values, in order to draw boxes around them as in your example.  
  - The PNF values can be accessed using [**the `return_calculated_values` kwarg**](https://github.com/matplotlib/mplfinance/wiki/Access-to-mplfinance-Calculated-Values)
  - The x-value of each volume will be the **list index** for the list: **`list( cv['pnf_values'].keys()) )`**, where **`cv`** is the calculated values dict returned by the `return_calculated_values` kwarg (when `type='pnf'`).
    -  In other words, the x-value will be 0.0 for the first PNF column, it will be 1.0 for the second PNF column, 2.0 for the third, etc. (althought the datetime displayed will be the actual key values in `list( cv['pnf_values'].keys()) )`; [see also here for a similar situation](https://github.com/matplotlib/mplfinance/wiki/Mplfinance-Time-Axis-Concerns,-and-Internals-of-Displaying-or-Not-Displaying-Non-Trading-periods).
- The boxes with the text inside the box can be drawn using [`matplotlib annotations`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.annotate.html)
- The boxes showing support and resistance can be draw any *one* of these ways:
  - [`Axes.axhline`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.axhline.html) and [`Axes.axvline`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.axvline.html) for the horizontal and vertical lines of each box.
  - [`rect = patches.Rectangle`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Rectangle.html) followed by [`Axes.addPatch(rect)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.add_patch.html) to create a rectangle and add it to the Axes object.
  - [`Axes.barh()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.barh.html) to create horizontal rectangles at specific locations.
  - I don't know which of the above three methods would be easiest. 
 
Hopefully above is enough information to get you started.

**Comment by nkta3m** [comment]
@DanielGoldfarb 
Thanks a lot for the help， i got it. 

This is a great project, thanks a lot for you.
![002217](https://user-images.githubusercontent.com/13484700/232184745-b7d470b3-e352-4c79-a4d1-08d3496494c7.png)
