### ISSUE TITLE
PnF charts using just close. 

### ISSUE THREAD

**Issue by boomkap** [matplotlib/mplfinance#619]
I have a dataset with only 1 column that represents close price. I am unable to generate a PnF chart as it appears that PnF expects date, open, high, low & close. 

PnF charts are drawn using either High/Low or just considering close. 

Is there a way to generate a PnF with just close?

**Comment by DanielGoldfarb** [comment]
The problem is that mplfinance, in general, expects the dataframe to contain Open, High, Low, Close (and optionally Volume).

When `type='pnf'` then you can also specify `pnf_params` as a `dict` including any one or more of 'box_size', 'atr_length', 'reversal', 'method', 'use_candle_colors', 'scale_markers', and/or 'scale_right_padding' (see [here](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L426-L463)).

`method` can be 'hilo' (the default), 'open', or 'close'.

To plot PNF with just close, `mpf.plot( df, type='pnf', pnf_params=dict(method='close'))` and you will have to make sure that the dataframe, `df`, includes column names 'Open', 'High', 'Low', and 'Close', but it will work fine even if you fill all four columns with the 'Close' data.

**Comment by boomkap** [comment]
That should work. Thank you for the clarification.

Btw: where can I find a dictionary of all the pnf_params?

From: Daniel Goldfarb ***@***.***>
Reply-To: matplotlib/mplfinance ***@***.***>
Date: Monday, May 29, 2023 at 1:30 PM
To: matplotlib/mplfinance ***@***.***>
Cc: Kapil Khanna ***@***.***>, Author ***@***.***>
Subject: Re: [matplotlib/mplfinance] PnF charts using just close. (Issue #619)


The problem is that mplfinance, in general, expects the dataframe to contain Open, High, Low, Close (and optionally Volume).

When type='pnf' then you can also specify pnf_params as a dict including any one or more of 'box_size', 'atr_length', 'reversal', 'method', 'use_candle_colors', 'scale_markers', and/or 'scale_right_padding' (see here<https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L426-L463>).

method can be 'hilo' (the default), 'open', or 'close'.

To plot PNF with just close, mpf.plot( df, type='pnf', pnf_params=dict(method='close')) and you will have to make sure that the dataframe, df, includes column names 'Open', 'High', 'Low', and 'Close', but it will work fine even if you fill all four columns with the 'Close' data.

**Comment by DanielGoldfarb** [comment]
As mentioned above, you can see the available pnf_params [**in the code here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L426-L463), or alternatively you can run the following functions to print out the available kwargs:

```python
mpf.kwarg_help()
mpf.kwarg_help('pnf')
```

**Comment by boomkap** [comment]
Perfect.

Thanks.

From: Daniel Goldfarb ***@***.***>
Reply-To: matplotlib/mplfinance ***@***.***>
Date: Monday, May 29, 2023 at 5:57 PM
To: matplotlib/mplfinance ***@***.***>
Cc: Kapil Khanna ***@***.***>, Author ***@***.***>
Subject: Re: [matplotlib/mplfinance] PnF charts using just close. (Issue #619)


As mentioned above, you can see the available pnf_params in the code here<https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L426-L463>, or alternatively you can run the following functions to print out the available kwargs:

mpf.kwarg_help()

mpf.kwarg_help('pnf')
