### ISSUE TITLE
How do i get renko values without ploting the chart?

### ISSUE THREAD

**Issue by kaleab-shumet** [matplotlib/mplfinance#651]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
How do i get renko values without ploting the chart? I used return_calculated_values to get the data but i do not want the chart to be displayed?

**Comment by DanielGoldfarb** [comment]
If you set [`returnfig=True`](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects#1-set-returnfigtrue-when-calling-mpfplot--this-is-the-preferred-way) then mplfinance will _not_ display the figure.

As noted in the documentation "when `returnfig=True` then mplfinance assumes you want to do some of your own modifications to the Figure or Axes objects before displaying them, so it does not show the figure. Therefore, when you are ready to show the figure, call `mpf.show()`."  Of course, you can always choose to never call `mpf.show()` if you don't want to display the figure.

Note: if you do this many times repeatedly, then you may want to delete the Figure and Axes objects that are returned (or allow them to go out of scope and be garbage collected) so that you don't end up with a memory leak.

**Comment by kaleab-shumet** [comment]
Ok, Thank You !
