### ISSUE TITLE
Feature Request: make "Open", "High", "Low", "Close" column names case insensitive

### ISSUE THREAD

**Issue by TensorMan** [matplotlib/mplfinance#82]
Small tweak here to work with lowercase etc sources. I love the new mplfinance -great work

**Comment by croganm** [comment]
Agreed, but there's a simple one line fix for it:

inital_data.columns = map(str.title, inital_data.columns)

Where initial_data is your dataframe of choice

**Comment by baqwas** [comment]
Agree with @croganm although the rearrangement in my case (_alphavantage_ data source) I had to explicitly rename while splitting the lower level list contain ohlc data. @TensorMan makes a suggestion (that I was originally going to request) that I am sure cuts both ways for developers.

Separately, I thought of writing to _alphavantage_ too about their format! :)

**Comment by DanielGoldfarb** [comment]
I will make the column names case insensitive.  You can also use the `columns=` kwarg to specify your own custom names for columns.  The kwarg expects a tuple of length 5 and assume whatever names you specify are in the order OHLCV.  **[See here.](https://github.com/matplotlib/mplfinance/pull/73)**

**Comment by baqwas** [comment]
Thank you ensuring a larger tent for us, @DanielGoldfarb.

Kind regards.

**Comment by DanielGoldfarb** [comment]
[I started playing with this](https://github.com/matplotlib/mplfinance/issues/82#issuecomment-619464818) and I am now _leaning towards_ ***not*** making column names case insensitive, at least not by default, and here are the reasons why:

- Pandas DataFrame column names ***are*** case sensitive, so we would be going against expected Pandas behavior if, by default, mplfinance treats DataFrame columns as case-insensitive.
- Although it is not likely to happen, **Pandas does allow** a user could have columns named 'open', 'Open', and 'OPEN' all in the same DataFrame.  (According to Murpy's law, if you allow a user to do something then, sooner or later, one or more users will indeed do it!) 
  - This means, in addition to the few extra lines of code needed to index the DataFrame columns in a case-insensitive manner, we would need some code to detect this possible situation (multiple columns with the same name when ignoring case) and raise an exception about it -- otherwise it is likely that an exception will be encountered later in the code without any obvious indication as to the reason why.
- **With the ` columns= ` kwarg, users can always specify what their OHLCV column names actually are.**
- We could accept a kwarg **` ignore_case=True `** or alternatively the **` columns= `** kwarg could accept a value of **` "ignore case" `** as an alternative to the list of column names;  **but are either of these two alternatives really any easier than simply specifying your own column names using the ` columns= ` kwarg??**

Thoughts?  Comments?

**Comment by baqwas** [comment]
@DanielGoldfarb, I am fine with your rationalization. As others have pointed out, the operation can be done by the client-side app with a single line of code. In my case, with the _alphavantage_ data, I had to strip out the numerical index and so decided to do it all (including case conversion) in one swoop. No extra line of coding for me.

I feel that end-user customization is accomplished by the use of **kwarg** as you have indicated. Thanks for being pro-active.

Kind regards.

**Comment by DanielGoldfarb** [comment]
You can thank @borgstrom for being pro-active and implementing the `columns=` kwarg ... and, I might add, in a very clean, simple (aka elegant) way!

**Comment by baqwas** [comment]
Hello @borgstrom, thank you for your contributions to the **mplfinance** repository. The use of _kwarg_ for the column names is definitely a feature that will come in handy as I use alternate sources of data.

Daniel has been very patient with my _newbie_ questions. I have had to suspend my self-paced learning with the library exercises for circumstances beyond my control. I will be in a better position to resume in about three weeks. I intend to dutifully try out as many test examples as practical for my interest in movement momentum analysis using technical time-series data. I am really glad that there are so many knowledgeable persons providing support towards embellishing the library.

Kind regards.
