### ISSUE TITLE
have some questions @ price-movement_plots

### ISSUE THREAD

**Issue by artu001** [matplotlib/mplfinance#88]
examples/price-movement_plots.ipynb

 mpf.plot(daily,type='renko')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\ProgramData\Anaconda3\lib\site-packages\mplfinance\plotting.py", line 35, in decorator
    return func(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\mplfinance\plotting.py", line 156, in plot
    config = _process_kwargs(kwargs, _valid_plot_kwargs())
  File "d:\ProgramData\Anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 114, in _process_kwargs
    raise ValueError('kwarg "'+key+'" validator returned False for value: "'+str(value)+'"\n    '+v)
ValueError: kwarg "type" validator returned False for value: "renko"
    'Validator'   : lambda value: value in ['candle','candlestick','ohlc','bars','ohlc_bars','line'] },

**Comment by coffincw** [comment]
Hi artu001,

If you are running the PyPi version of mplfinance you will have to wait for the 0.12.4a0 release mentioned here: #67 

In the meantime if you want to use the new implementations you can clone this repository to your local machine, and pip install from the repository (instead of from pypi).

Keep in mind that you may want to pull from #87 as it contains fixes to Renko plots as the version in master isn't correct.

Let me know if you have any questions about the plots!

- Caleb

**Comment by artu001** [comment]
hi Caleb,

thanks a lot.
