### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by albertusfreddi** [matplotlib/mplfinance#90]
**Describe the bug**
hi, for some ticker its normal, but for some ticker there is trouble
![image](https://user-images.githubusercontent.com/48875141/79058791-91bc4a80-7c9c-11ea-8911-4aa2e7710ba8.png)

even i try to turnoff volume, the result is still error.
please kindly help me to fix this

**Comment by DanielGoldfarb** [comment]
@albertusfreddi 
Albertus,  Can you please provide the data so that I can reproduce to debug.  If you don't already have the data in a csv file, just call `df.to_csv('filename.csv')` on the dataframe that is giving you the failure.

Thank you.  --Daniel

**Comment by albertusfreddi** [comment]
here sir, btw thanks for your fast response


[debug.zip](https://github.com/matplotlib/mplfinance/files/4465790/debug.zip)

**Comment by DanielGoldfarb** [comment]
@albertusfreddi  ... I am unable unzip the file.  When I try "Extract All" on windows, it thinks the zipped folder is empty.  And linux `unzip`, and `gunzip` both don't like it either.

**Comment by albertusfreddi** [comment]
[debuging.zip](https://github.com/matplotlib/mplfinance/files/4465854/debuging.zip)
sorry sir, here the file again. thanks

**Comment by coffincw** [comment]
Hi Albertus,

I was able to plot your data without errors with this code:

```
import pandas as pd
import mplfinance as mpf

daily = pd.read_csv('debug2.csv',index_col=0,parse_dates=True)
daily.index.name = 'Date'

mpf.plot(daily, type='candle', volume=True, figscale=2.9, style='charles')
```

This means that the issue is likely with the other arguments you are specifying for the `plot()` function.  I'm not really sure what they are, would you be able to send all the code related to the arguments in your mpf.plot() function call?

-- Caleb

**Comment by DanielGoldfarb** [comment]
You can see the arguments from the [traceback in the image provided](https://user-images.githubusercontent.com/48875141/79058791-91bc4a80-7c9c-11ea-8911-4aa2e7710ba8.png) however the traceback shows the call to `mpf.plot()` includes an `addplot`, and the traceback does not show where the data fro the addplot comes from.  

@albertusfreddi  please include the data, and the code that calls `make_addplot()`.   mplfinance is crashing on a line of code that is attempting to determine the order of magnitude for the `addplot` data.   Certainly, mplfinance should not crash, but in order to put an appropriate check in the code, we will need that data to understand what case we are not handling.  Thank you.

**Comment by DanielGoldfarb** [comment]
**[No response to previous request for data to reproduce.](https://github.com/matplotlib/mplfinance/issues/90#issuecomment-612676595)**
